import { SubjectActions } from '@/components/operational/subject-surface';
import Link from 'next/link';
import { hkNextAction, HK_MAINTENANCE_EVENT_LABELS, maintenanceAllowsContinuation } from '@/domain/housekeeping-continuity';
import { randomUUID } from 'node:crypto';
import { requireHousekeepingPageUser } from '@/server/auth/housekeeping';
import { getHkWorkday, getHkSources } from '@/server/services/housekeeping-work';
import { getHousekeepingDestinations, housekeepingSourceChanged } from '@/server/services/housekeeping';
import { canManageHousekeeping, HOUSEKEEPING_LABELS, housekeepingActions, type HousekeepingStatus } from '@/domain/housekeeping';
import { HK_WORK_LABELS, HK_KIND_LABELS, HK_ACTION_LABELS, HK_ACTION_PERMISSION, hkAllowedActions, type HkWorkKind, type HkWorkAction } from '@/domain/housekeeping-work';
import { formatDateTime } from '@/lib/format';
import { StatTile } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { HousekeepingChangeForm } from '@/components/admin/housekeeping-forms';
import { AcceptHandoverForm, NewWorkForm, WorkActionForm, PrepareDayForm, RoutineForm, AvailabilityForm, HandoverForm, ReceiveHandoverForm, DelegationForm, RevokeDelegationForm, OrganizeLegacyForm } from '@/components/housekeeping/work-forms';
import type { Prisma } from '@prisma/client';

export const metadata = { title:'Housekeeping · Trabajo del día' };
export const dynamic = 'force-dynamic';
const tabs = [['','Trabajo del día'],['mios','Mi trabajo'],['revision','Por revisar'],['solicitudes','Por asignar'],['impedimentos','Impedimentos'],['continuidad','Continuidad'],['historial','Historial']] as const;
function Snapshot({value}:{value:Prisma.JsonValue}){
  if(!value||typeof value!=='object'||Array.isArray(value))return null;
  const work=Array.isArray(value.work)?value.work:[];const loans=Array.isArray(value.loans)?value.loans:[];
  return <div className="space-y-2 text-xs text-slate-600"><p>{work.length} trabajos pendientes · {loans.length} entregas de llaves abiertas al guardar.</p><ul className="space-y-1">{work.map((w,i)=>w&&typeof w==='object'&&!Array.isArray(w)?<li key={i}>#{String(w.humanId)} · {String(w.location??'Sin ubicación')} · {HK_WORK_LABELS[String(w.status)]??String(w.status)} · {typeof w.assignedTo==='object'&&w.assignedTo&&!Array.isArray(w.assignedTo)?String(w.assignedTo.name):'Por asignar'}{w.blockReason?` · Impedimento: ${String(w.blockReason)}`:''}</li>:null)}</ul><ul className="space-y-1">{loans.map((l,i)=>l&&typeof l==='object'&&!Array.isArray(l)?<li key={i}>Entrega #{String(l.humanId)} · {String(l.collaboratorName??'Personal del área')} · {Array.isArray(l.items)?l.items.map(k=>k&&typeof k==='object'&&!Array.isArray(k)?`${String(k.keyCode)} (${String(k.destinationName)})`:'').join(', '):''}</li>:null)}</ul></div>;
}
export default async function HousekeepingPage({searchParams}:{searchParams:Promise<{vista?:string;fecha?:string;area?:string;piso?:string;responsable?:string;pagina?:string;aviso?:string;q?:string}>}){
  const user=await requireHousekeepingPageUser();const params=await searchParams;
  const view=params.vista??(user.permissions.includes('housekeeping.work')&&!user.permissions.includes('housekeeping.view')?'mios':'');
  const board=await getHkWorkday(user,{date:params.fecha,departmentId:params.area,view,floor:/^[456]$/.test(params.piso??'')?params.piso:undefined,responsible:params.responsable,page:Number(params.pagina??1),focusId:params.aviso&&/^\d+$/.test(params.aviso)?Number(params.aviso):undefined});
  const legacyManage=canManageHousekeeping(user);
  const [sources,destinations]=await Promise.all([view==='vincular'&&(board.canAssign||board.canRequest)?getHkSources(user,board.departmentId,params.q):Promise.resolve([]),legacyManage?getHousekeepingDestinations(user):Promise.resolve({departments:[],users:[]})]);
  const title=board.canPlan?'Estado de Housekeeping':board.canAssign?'Coordinar y revisar':board.canWork?'Mi trabajo de hoy':board.teamVisible?'Estado de Housekeeping':'Solicitudes a Housekeeping';
  const href=(next:string,page=1)=>`/admin/housekeeping?${new URLSearchParams({fecha:board.date,area:board.departmentId,vista:next,pagina:String(page),...(params.piso?{piso:params.piso}:{}),...(params.responsable?{responsable:params.responsable}:{})})}`;
  const allowed=(action:HkWorkAction,assignedToId:string|null)=>{
    const permission=HK_ACTION_PERMISSION[action];return permission==='housekeeping.work'?board.canWork&&assignedToId===user.id:permission==='housekeeping.inspect'?board.canInspect&&assignedToId!==user.id:board.canAssign;
  };
  return <div className="mx-auto max-w-6xl space-y-4 surface-enter">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold text-petrol-900">{title}</h1><p className="mt-1 text-sm text-slate-600">{board.areas.find(a=>a.id===board.departmentId)?.name??'Housekeeping'} · {board.date.split('-').reverse().join('/')} · Trabajo, revisión y continuidad del área.</p></div><div className="flex flex-wrap gap-2">{board.canAssign&&<PrepareDayForm departmentId={board.departmentId} date={board.date} count={board.routines.filter(r=>r.active).length}/>} {board.canRequest&&<NewWorkForm key={`${board.departmentId}-${board.date}`} requestKey={randomUUID()} date={board.date} departmentId={board.departmentId} rooms={board.rooms} zones={board.zones} team={board.workload} canAssign={board.canAssign}/>}</div></header>
    <form action="/admin/housekeeping" className="card flex flex-wrap items-end gap-3 p-3"><input type="hidden" name="vista" value={view}/><label className="min-w-0 text-xs font-medium text-slate-600">Día<input className="input-base mt-1" name="fecha" type="date" defaultValue={board.date}/></label><label className="min-w-0 text-xs font-medium text-slate-600">Área<select className="input-base mt-1" name="area" defaultValue={board.departmentId}>{board.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-xs font-medium text-slate-600">Piso<select className="input-base mt-1" name="piso" defaultValue={params.piso??''}><option value="">Todos / zonas comunes</option>{[4,5,6].map(f=><option key={f} value={f}>Piso {f}</option>)}</select></label>{board.teamVisible&&<label className="min-w-0 text-xs font-medium text-slate-600">Responsable<select className="input-base mt-1" name="responsable" defaultValue={params.responsable??''}><option value="">Todo el equipo</option>{board.workload.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<Button type="submit" variant="secondary">Ver</Button></form>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatTile label="Por asignar" value={board.counts.unassigned}/><StatTile label="Por revisar" value={board.counts.review}/><StatTile label="Con impedimento" value={board.counts.blocked}/><StatTile label="Terminados del día" value={board.counts.completed}/></div>
    {(board.counts.overdue>0||board.counts.carryover>0)&&<p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{board.counts.overdue} trabajos con plazo vencido · {board.counts.carryover} pendientes de días anteriores. Conservan su responsable y su historial.</p>}
    <nav aria-label="Trabajo de Housekeeping" className="flex flex-wrap gap-2 text-sm">{tabs.filter(([key])=>board.teamVisible||!['revision','continuidad'].includes(key)).map(([key,label])=><Link key={key} href={href(key)} aria-current={view===key?'page':undefined} className={`rounded-lg border px-3 py-2 ${view===key?'border-petrol-800 bg-petrol-800 text-white':'border-slate-200 bg-white text-petrol-800'}`}>{label}</Link>)}{(board.canAssign||board.canRequest)&&<Link href={href('vincular')} className="rounded-lg border border-slate-200 px-3 py-2">Vincular novedad</Link>}</nav>
    {view==='vincular'&&(board.canAssign||board.canRequest)?<section className="card space-y-3 p-4"><h2 className="font-semibold">Vincular una novedad existente</h2><p className="text-sm text-slate-600">La novedad conserva su estado. El resultado de Housekeeping queda asociado al mismo origen.</p><form action="/admin/housekeeping" className="flex gap-2"><input type="hidden" name="vista" value="vincular"/><input type="hidden" name="area" value={board.departmentId}/><input type="hidden" name="fecha" value={board.date}/><input name="q" aria-label="Buscar novedad" className="input-base min-w-0 flex-1" placeholder="#ID, habitación o título" defaultValue={params.q}/><Button variant="secondary" type="submit">Buscar</Button></form><ul className="divide-y">{sources.map(s=><li className="flex flex-wrap items-center justify-between gap-2 py-3" key={s.id}>{user.permissions.includes('entry.create')?<Link href={`/libro/${s.id}`}>#{s.humanId} · {s.title}</Link>:<span>#{s.humanId} · {s.title}</span>}<NewWorkForm requestKey={randomUUID()} date={board.date} departmentId={board.departmentId} rooms={board.rooms} zones={board.zones} team={board.workload} canAssign={board.canAssign} source={s}/></li>)}</ul></section>:<section className="space-y-3" aria-label="Trabajos de Housekeeping">
      {!board.requests.length&&<div className="card space-y-2 p-6 text-center"><p className="font-semibold text-petrol-900">{board.counts.active===0&&board.counts.completed>0?'El trabajo registrado para este día está terminado.':board.counts.active===0?'Todavía no hay trabajo registrado para este día.':'No hay trabajos en esta vista.'}</p><p className="text-sm text-slate-600">{board.canAssign?'Revisa las solicitudes, incorpora las rutinas y asigna responsables.':board.canWork?'Tus asignaciones aparecerán aquí cuando el supervisor organice el trabajo.':'Solicita una atención y consulta aquí su avance y resultado.'}</p></div>}
      {board.requests.map(r=>{
        const changed=housekeepingSourceChanged(r);const modern=r.workflowVersion===1;const actions=modern?hkAllowedActions(r.status,!!r.assignedToId,changed).filter(a=>allowed(a,r.assignedToId)):[];
        const waitingMaintenance=!!r.maintenanceEntry&&!maintenanceAllowsContinuation(r.maintenanceEntry);
        const actionable=actions.filter(a=>!(waitingMaintenance&&['COMENZAR','RETOMAR','TERMINAR','APROBAR'].includes(a))&&!(r.maintenanceEntryId&&a==='MANTENIMIENTO'));
        const order:HkWorkAction[]=changed?['RECONFIRMAR']:r.status==='POR_REVISAR'?['APROBAR','CORREGIR']:r.status==='BLOQUEADO'?['RETOMAR','MANTENIMIENTO','ASIGNAR']:r.status==='EN_GESTION'?['TERMINAR']:r.assignedToId?['RECIBIR','COMENZAR']:['ASIGNAR'];
        const primary=order.find(a=>actionable.includes(a));
        const secondary=actionable.filter(a=>a!==primary&&['IMPEDIMENTO','CORREGIR','MANTENIMIENTO','COMENZAR','REABRIR'].includes(a)).slice(0,2);
        const advanced=actionable.filter(a=>a!==primary&&!secondary.includes(a));
        const renderAction=(a:HkWorkAction,isPrimary=false)=><WorkActionForm key={a} id={r.id} version={r.version} action={a} team={board.workload} defaultAssignee={r.assignedToId??undefined} primary={isPrimary}/>;
        return <article key={r.id} id={`aviso-${r.humanId}`} className="card scroll-mt-28 space-y-3 p-4">
          <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-medium text-slate-500">{r.room?`Piso ${r.room.floor??r.room.number[0]} · Habitación ${r.room.number}`:r.zone?.name??r.location??r.sourceEntry?.room?.number??'Sin ubicación'} · {modern?HK_KIND_LABELS[r.workKind as HkWorkKind]:'Aviso anterior'}</p><h2 className="mt-1 font-semibold text-petrol-900">#{r.humanId} · {r.sourceEntry?.title??r.title}</h2></div><span className={`rounded-md px-2 py-1 text-xs font-semibold ${r.status==='BLOQUEADO'?'bg-amber-100 text-amber-900':r.status==='POR_REVISAR'?'bg-sky-100 text-sky-900':r.status==='RESUELTO'?'bg-emerald-100 text-emerald-900':'bg-slate-100 text-slate-700'}`}>{!r.assignedToId&&!['RESUELTO','CANCELADO'].includes(r.status)?'Por asignar':modern?HK_WORK_LABELS[r.status]:HOUSEKEEPING_LABELS[r.status as HousekeepingStatus]}</span></div>
          <p className="whitespace-pre-wrap break-words text-sm text-slate-700">{r.sourceEntry?.description??r.description}</p>
          <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600"><span>Responsable: <strong>{r.assignedTo?.name??'Por asignar'}</strong></span><span>Prioridad: {r.priority==='CRITICA'?'Urgente':r.priority.toLowerCase()}</span>{modern&&<span>Estimado: {r.effortMinutes} min</span>}<span>Plazo: {r.dueAt?formatDateTime(r.dueAt):'Sin plazo'}</span>{r.requiresInspection&&<span>Requiere inspección</span>}</div>
          {r.blockReason&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><strong>Impedimento:</strong> {r.blockReason}</p>}{changed&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">La instrucción de origen cambió. El supervisor debe revisarla antes de continuar.</p>}
          {r.resolution&&<p id={`resultado-${r.humanId}`} className="whitespace-pre-wrap text-sm text-emerald-800"><strong>Resultado:</strong> {r.resolution}{r.inspectedBy&&` · Revisado por ${r.inspectedBy.name}`}</p>}
          {r.maintenanceEntry&&<section aria-label="Resultado de Mantenimiento" className="space-y-2 rounded-lg border border-slate-200 p-3 text-sm"><p className="font-medium">Mantenimiento #{r.maintenanceEntry.humanId} · {r.maintenanceEntry.deletedAt?'Archivado':maintenanceAllowsContinuation(r.maintenanceEntry)?'Resultado disponible':'Atención pendiente'}</p>{r.maintenanceEntry.resolution&&<p className="whitespace-pre-wrap break-words"><strong>{maintenanceAllowsContinuation(r.maintenanceEntry)?'Resultado:':'Resultado anterior o avance:'}</strong> {r.maintenanceEntry.resolution}</p>}<p className="text-xs text-slate-600">Última actualización: {formatDateTime(r.maintenanceEntry.updatedAt)}. No finaliza Housekeeping ni modifica la disponibilidad comercial.</p>{user.permissions.includes('entry.create')&&<Link className="inline-block underline" href={`/libro/${r.maintenanceEntry.id}`}>Ver incidencia</Link>}</section>}
          {modern&&<p className="break-words text-sm text-petrol-900"><strong>Siguiente acción:</strong> {hkNextAction(r)}</p>}
          {r.sourceEntry&&<p className="text-xs text-slate-600">Origen: Novedad #{r.sourceEntry.humanId}{user.permissions.includes('entry.create')&&<Link href={`/libro/${r.sourceEntry.id}`} className="ml-2 underline">Ver novedad</Link>}</p>}
          <div className="flex flex-wrap gap-2">{!modern&&!r.isDemo&&!['RESUELTO','CANCELADO'].includes(r.status)&&board.canAssign&&<OrganizeLegacyForm id={r.id} version={r.version} departmentId={board.departmentId} date={board.date} rooms={board.rooms} team={board.workload}/>} {modern?<SubjectActions primary={['RESUELTO','CANCELADO'].includes(r.status)?<a href={r.resolution?`#resultado-${r.humanId}`:`#aviso-${r.humanId}`} className="btn-primary">Ver resultado</a>:primary?renderAction(primary,true):<p className="text-sm">{waitingMaintenance?'Esperando resultado de Mantenimiento':'La siguiente acción corresponde al responsable autorizado'}</p>} secondary={secondary.map(a=>renderAction(a))} more={advanced.length?advanced.map(a=>renderAction(a)):undefined}/>:legacyManage?housekeepingActions(r.status as HousekeepingStatus,changed).map(a=><HousekeepingChangeForm key={a} id={r.id} version={r.version} action={a} destinations={destinations} departmentId={r.departmentId??undefined}/>):null}</div>
          <details className="border-t border-slate-100 pt-2"><summary className="cursor-pointer text-xs text-slate-600">Historial y responsables</summary><p className="mt-2 text-xs text-slate-500">Solicitante: {r.createdBy?.name??'Registro anterior'} · Día: {r.workDate??'Aviso anterior'}{r.isDemo?' · Prueba administrativa':''}</p><ol className="mt-2 space-y-2 text-xs text-slate-600">{r.events.map(e=><li key={e.id}><strong>{e.actor.name}</strong> · {HK_ACTION_LABELS[e.action as HkWorkAction]??HK_MAINTENANCE_EVENT_LABELS[e.action]??e.action} · {formatDateTime(e.createdAt)}{e.note&&<p className="whitespace-pre-wrap">{e.note}</p>}</li>)}</ol></details>
        </article>;
      })}
      {board.total>30&&<nav className="flex gap-3 text-sm" aria-label="Páginas de trabajos"><span>Página {board.page} · {board.total} trabajos</span>{board.page>1&&<Link className="underline" href={href(view,board.page-1)}>Anterior</Link>}{board.page*30<board.total&&<Link className="underline" href={href(view,board.page+1)}>Siguiente</Link>}</nav>}
    </section>}
    {board.canAssign && <details className="card p-4"><summary className="cursor-pointer font-semibold text-petrol-900">Sugerencia de distribución · Fronti</summary><p className="mt-2 text-xs text-slate-600">Propuesta basada en disponibilidad confirmada y minutos estimados. Revisa dificultad, ubicación y plazo antes de confirmar cada asignación.</p>{!board.suggestions.length?<p className="mt-3 text-sm text-slate-600">Confirma la disponibilidad del equipo y registra trabajos por asignar para obtener una propuesta.</p>:<ul className="mt-3 space-y-3">{board.suggestions.map(s=><li key={s.id} className="rounded-lg border border-slate-200 p-3"><p className="text-sm">#{s.humanId} · {s.title} · {s.location}</p><p className="mt-1 text-sm font-medium">Propuesta: {s.name}</p><p className="mb-2 text-xs text-slate-500">{s.reason}</p><WorkActionForm id={s.id} version={s.version} action="ASIGNAR" team={board.workload} defaultAssignee={s.userId}/></li>)}</ul>}</details>}
    {board.teamVisible&&<details className="card p-4" open={board.canAssign}><summary className="cursor-pointer font-semibold text-petrol-900">Equipo y carga del día</summary><p className="mt-2 text-xs text-slate-500">Los horarios muestran programación. La disponibilidad se declara por separado y no acredita asistencia. La carga suma estimaciones del trabajo pendiente.</p>{!board.workload.length&&<p className="mt-3 text-sm text-slate-600">No hay usuarios del área habilitados para ejecutar trabajo. El administrador debe vincular las cuentas existentes al área y asignar su cargo.</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2">{board.workload.map(p=><div key={p.id} className="rounded-lg border border-slate-200 p-3"><p className="font-medium text-petrol-900">{p.name}</p><p className="mt-1 text-sm">{p.tasks} trabajos · {p.estimatedMinutes} min estimados · {p.available===null?'Disponibilidad por confirmar':p.available?'Disponible':'No disponible'}</p><p className="mt-1 text-xs text-slate-500">{p.scheduled.length?p.scheduled.map(s=>`${s.code} · ${s.startAt?formatDateTime(s.startAt):''} – ${s.endAt?formatDateTime(s.endAt):''}`).join(' / '):'Sin horario publicado para este día'}</p>{p.note&&<p className="mt-1 text-xs text-slate-600">{p.note}</p>}{board.canAssign&&<div className="mt-2"><AvailabilityForm departmentId={board.departmentId} date={board.date} person={p}/></div>}</div>)}</div></details>}
    {board.teamVisible&&<details className="card p-4" open={view==='continuidad'}><summary className="cursor-pointer font-semibold text-petrol-900">Relevo y llaves en custodia</summary><div className="mt-3 space-y-3">{board.canAssign&&<HandoverForm requestKey={randomUUID()} departmentId={board.departmentId} date={board.date}/>}<p className="text-sm">{board.loans.length} entregas de llaves abiertas.{user.permissions.includes('key.assign')&&<Link href="/llaves/personal" className="ml-2 underline">Gestionar entregas y devoluciones</Link>}</p>{board.loans.map(l=><p key={l.id} className="text-xs text-slate-600">Entrega #{l.humanId} · {l.collaboratorName??'Personal del área'} · {l.items.map(i=>`${i.keyCode} (${i.destinationName})`).join(', ')}</p>)}{board.handovers.map(h=><article className="rounded-lg border border-slate-200 p-3" key={h.id}><p className="text-xs text-slate-500">{h.createdBy.name} · {formatDateTime(h.createdAt)} · Día {h.workDate}</p><p className="mt-2 whitespace-pre-wrap text-sm">{h.note}</p><details className="mt-2"><summary className="cursor-pointer text-xs">Pendientes y llaves al entregar</summary><Snapshot value={h.snapshot}/></details>{h.acceptedAt?<p className="text-xs text-emerald-800">Continuidad aceptada · {formatDateTime(h.acceptedAt)}</p>:h.receivedById===user.id&&board.canAssign?<AcceptHandoverForm id={h.id}/>:null}{h.receivedAt?<p className="mt-2 text-xs text-emerald-800">Recibido por {h.receivedBy?.name} · {formatDateTime(h.receivedAt)}</p>:board.canAssign&&h.createdById!==user.id?<div className="mt-2"><ReceiveHandoverForm id={h.id}/></div>:<p className="mt-2 text-xs text-amber-800">Por recibir</p>}</article>)}</div></details>}
    {board.canPlan&&<details className="card p-4"><summary className="cursor-pointer font-semibold text-petrol-900">Rutinas y cobertura temporal</summary><div className="mt-3 flex flex-wrap gap-2"><RoutineForm departmentId={board.departmentId}/><DelegationForm departmentId={board.departmentId} team={board.workload.filter(p=>p.id!==user.id)}/></div><ul className="mt-3 divide-y divide-slate-100">{board.routines.map(r=><li key={r.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><p className="text-sm font-medium">{r.title} · {r.location}</p><p className="text-xs text-slate-500">{r.active?'Activa':'Inactiva'} · {r.effortMinutes} min · {r.requiresInspection?'Con inspección':'Sin inspección obligatoria'}</p></div><RoutineForm departmentId={board.departmentId} routine={r}/></li>)}</ul><ul className="mt-3 space-y-2">{board.delegations.map(d=><li key={d.id} className="rounded-lg bg-slate-50 p-3 text-sm"><p>{d.user.name} · {d.permission==='housekeeping.assign'?'Asignar trabajo':'Inspeccionar'} · {formatDateTime(d.startsAt)} – {formatDateTime(d.endsAt)}</p><p className="my-2 text-xs">{d.reason}</p><RevokeDelegationForm id={d.id}/></li>)}</ul></details>}
  </div>;
}
