import '../etapa1/guard.cjs';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
const f=JSON.parse(readFileSync('/tmp/etapa1-fixture.json','utf8'));
const browser=await chromium.launch({headless:true});
console.log("Synthetic browser",browser.version());
const results=[];
const db=new PrismaClient();
try {
 for (const width of [1280,390]) {
  const context=await browser.newContext({viewport:{width,height:900}});
  await context.addCookies([{name:'lor_session',value:f.users.admin.token,domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);
  await context.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname!=='localhost'||['/api/notifications/stream','/api/alarms','/api/auth/pulse'].some(p=>u.pathname.startsWith(p))?route.abort():route.continue();});
  const page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(15000);
  await page.goto('http://localhost:3000/fronti/procedimientos');
  await page.getByRole('heading',{name:'Procedimientos de Fronti',exact:true}).waitFor();
  const key=randomUUID();const message=`Crea una tarea: ETAPA2_FRONTI_${width}`;
  const started=performance.now();
  const response=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message,requestKey:key}});
  const body=await response.json();const elapsed=Math.round(performance.now()-started);
  assert.equal(response.status(),200,body.error);assert.match(body.reply,/Completado/);
  console.log('Fronti exact API',width,elapsed);
  assert.ok(elapsed<=2000,`Fronti exact command took ${elapsed} ms; budget 2000 ms`);
  const href=/\/fronti\/procedimientos\?ejecucion=[a-z0-9]+/.exec(body.reply)?.[0];assert.ok(href);
  const retry=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message,requestKey:key}});assert.equal(retry.status(),200);assert.ok((await retry.json()).reply.includes(href));
  await page.goto('http://localhost:3000'+href);await page.getByRole('heading',{name:'Resultado: Completado',exact:true}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  console.log("Fronti UI width",width);
  await page.getByRole('button',{name:'Abrir Fronti',exact:true}).first().click();
  const panel=page.getByRole('region',{name:'Fronti',exact:true});
  await panel.getByRole('textbox',{name:'Mensaje para Fronti',exact:true}).fill(`Crea una tarea: ETAPA2_CHAT_${width}`);
  const visibleStart=performance.now();
  const [uiResponse]=await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/fronti'),panel.getByRole('button',{name:'Enviar a Fronti',exact:true}).click()]);
  const uiBody=await uiResponse.json();assert.equal(uiResponse.status(),200,uiBody.error);assert.match(uiBody.reply,/Completado/);
  const uiId=/ejecucion=([a-z0-9]+)/.exec(uiBody.reply)?.[1];assert.ok(uiId);
  await panel.getByText(new RegExp(uiId)).waitFor();
  const visibleMs=Math.round(performance.now()-visibleStart);assert.ok(visibleMs<=3000,`Fronti visible result took ${visibleMs} ms; budget 3000 ms`);
  console.log('Fronti visible chat',width,visibleMs);
  results.push({width,scenario:'actual-chat-input-to-visible-result',ms:visibleMs,budgetMs:3000,status:'passed',provider:'not-used'});
  await panel.getByRole('link',{name:`/fronti/procedimientos?ejecucion=${uiId}`,exact:true}).click();
  await page.getByRole('heading',{name:'Resultado: Completado',exact:true}).waitFor();
  await panel.getByRole('button',{name:'Minimizar Fronti',exact:true}).click();
  // A finite delegation uses the existing executor; creation is inert, retries never repeat effects.
  const delegationTitle=`ETAPA2_DELEGATION_${width}`;
  const delegationMessage='/delegar '+JSON.stringify({objective:`Revisión delegada ${width}`,availableAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),steps:[{action:'createTaskAction',fields:{title:delegationTitle,description:'Dato sintético comunicado',priority:'MEDIA',targetType:'PROPIO'}}]});
  await page.getByRole('button',{name:'Abrir Fronti',exact:true}).first().click();
  await panel.getByRole('textbox',{name:'Mensaje para Fronti',exact:true}).fill(delegationMessage);
  const [delegationResponse]=await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/fronti'),panel.getByRole('button',{name:'Enviar a Fronti',exact:true}).click()]);
  const delegationBody=await delegationResponse.json();assert.equal(delegationResponse.status(),200,delegationBody.error);assert.match(delegationBody.reply,/Delegación registrada/);
  const delegationId=/ejecucion=([a-z0-9]+)/.exec(delegationBody.reply)?.[1];assert.ok(delegationId);
  assert.equal(await db.task.count({where:{title:delegationTitle}}),0,'Creating a mandate must not execute it');
  await panel.getByRole('textbox',{name:'Mensaje para Fronti',exact:true}).fill('/usar-delegacion '+delegationId);
  const delegationStart=performance.now();
  const [runResponse]=await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/fronti'),panel.getByRole('button',{name:'Enviar a Fronti',exact:true}).click()]);
  const runBody=await runResponse.json();assert.equal(runResponse.status(),200,runBody.error);assert.match(runBody.reply,/Completado/);
  // Creation and execution both link this mandate; wait for the second reply, not an earlier completed task.
  await panel.getByRole('link',{name:`/fronti/procedimientos?ejecucion=${delegationId}`,exact:true}).nth(1).waitFor();
  const delegationMs=Math.round(performance.now()-delegationStart);assert.ok(delegationMs<=3000,`Delegation visible ${delegationMs} ms exceeds 3000 ms`);
  const runRetry=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message:'/usar-delegacion '+delegationId,requestKey:randomUUID()}});assert.equal(runRetry.status(),200);assert.equal(await db.task.count({where:{title:delegationTitle}}),1);
  await panel.getByRole('button',{name:'Minimizar Fronti',exact:true}).click();
  await page.goto('http://localhost:3000/fronti/procedimientos?ejecucion='+delegationId);
  await page.getByRole('heading',{name:`Delegación: Revisión delegada ${width}`,exact:true}).waitFor();
  await page.getByText('Alcance y datos autorizados',{exact:true}).click();await page.getByText(delegationTitle,{exact:true}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  const revokedTitle=`ETAPA2_REVOKED_${width}`;
  const revokeInput={objective:'Revocación sintética',availableAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),steps:[{action:'createTaskAction',fields:{title:revokedTitle,description:'No ejecutar',priority:'MEDIA'}}]};
  const createdRevocation=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:'/delegar '+JSON.stringify(revokeInput),requestKey:randomUUID()}});assert.equal(createdRevocation.status(),200);
  const revokedId=/ejecucion=([a-z0-9]+)/.exec((await createdRevocation.json()).reply)?.[1];assert.ok(revokedId);
  const revoked=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:'/revocar-delegacion '+revokedId,requestKey:randomUUID()}});assert.equal(revoked.status(),200);
  const blocked=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:'/usar-delegacion '+revokedId,requestKey:randomUUID()}});assert.notEqual(blocked.status(),200);assert.equal(await db.task.count({where:{title:revokedTitle}}),0);
  await page.goto('http://localhost:3000/fronti/procedimientos?ejecucion='+revokedId);await page.getByRole('heading',{name:'Resultado: Cancelado',exact:true}).waitFor();
  results.push({width,scenario:'delegation-chat-create-inert-execute-retry-scope-revoke',ms:delegationMs,budgetMs:3000,status:'passed',provider:'not-used'});
  const dynamicPolicy={objective:`Mandato dinámico ${width}`,availableAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),maxExecutions:1,maxActions:1,rules:[{action:'createTaskAction',fixedFields:{description:'Trabajo sintético autorizado',priority:'MEDIA',targetType:'PROPIO'},variableFields:{title:{type:'text',maxLength:100}}}]};
  const dynamicCreate=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:'/delegar-dinamica '+JSON.stringify(dynamicPolicy),requestKey:randomUUID()}});const dynamicBody=await dynamicCreate.json();assert.equal(dynamicCreate.status(),200,dynamicBody.error);const dynamicId=/ejecucion=([a-z0-9]+)/.exec(dynamicBody.reply)?.[1];assert.ok(dynamicId);
  await page.goto('http://localhost:3000/fronti/procedimientos?ejecucion='+dynamicId);await page.getByRole('heading',{name:`Delegación dinámica: Mandato dinámico ${width}`,exact:true}).waitFor();
  const dynamicMessage='/usar-delegacion-dinamica '+JSON.stringify({id:dynamicId,steps:[{action:'createTaskAction',fields:{title:`ETAPA2_DYNAMIC_${width}`,description:'Trabajo sintético autorizado',priority:'MEDIA',targetType:'PROPIO'}}]});
  const dynamicStart=performance.now();const dynamicRun=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:dynamicMessage,requestKey:randomUUID()}});const dynamicResult=await dynamicRun.json();assert.equal(dynamicRun.status(),200,dynamicResult.error);assert.match(dynamicResult.reply,/Completado/);const dynamicMs=Math.round(performance.now()-dynamicStart);assert.ok(dynamicMs<=2000);
  await page.reload();await page.getByText(/Usos reservados: 1 \/ 1/).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  await page.goto('http://localhost:3000/coordinacion/indicadores');await page.getByRole('heading',{name:'Resumen e indicadores operativos',exact:true}).waitFor();await page.getByRole('heading',{name:'Tiempos observados',exact:true}).waitFor();const frontiDisclosure=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Automatizaciones y Fronti'})}).first();if(!(await frontiDisclosure.evaluate(el=>el.open)))await frontiDisclosure.locator('summary').click();assert.ok((await frontiDisclosure.innerText()).includes('No hay línea base humana'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  results.push({width,scenario:'dynamic-delegation-budget-and-indicators',ms:dynamicMs,budgetMs:2000,status:'passed',provider:'not-used'});
  const summary=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message:'/resumen',requestKey:randomUUID()}});assert.equal(summary.status(),200);assert.match((await summary.json()).reply,/Coordinación: \/coordinacion/);
  await page.goto('http://localhost:3000/coordinacion/automatizaciones');await page.getByRole('heading',{name:'Reglas y procedimientos',exact:true}).waitFor();assert.ok((await page.locator('body').innerText()).includes('deshabilitada'));
  // The same public form saves a paused version, simulates without effects, then pauses/revokes.
  const policyName=`ETAPA2_POLICY_${width}`;
  const openPolicyList=async()=>{const disclosure=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Tus últimas 50 políticas'})}).first();if(!(await disclosure.evaluate(el=>el.open)))await disclosure.locator('summary').click();return disclosure;};
  const details=page.locator('details').filter({has:page.getByText('Nuevo procedimiento o mantenimiento preventivo',{exact:true})});
  await details.locator('summary').click();
  await details.getByLabel('Nombre',{exact:true}).fill(policyName);
  await details.getByLabel('Área',{exact:true}).selectOption(f.areaId);
  await details.getByLabel('Responsable',{exact:true}).selectOption(f.users.worker.id);
  await details.getByLabel('Instrucción',{exact:true}).fill('Inspección sintética declarada por persona autorizada');
  await details.getByLabel('Siguiente acción',{exact:true}).fill('Registrar resultado de inspección');
  await details.getByLabel('Evidencia requerida',{exact:true}).fill('Resultado informado');
  await details.getByLabel('Lista: un punto por línea',{exact:true}).fill('Revisar filtro\nInformar resultado');
  await details.getByLabel('Hora de Santiago',{exact:true}).fill('00:00');
  for(const checkbox of await details.locator('input[name=weekdays]').all())await checkbox.check();
  const expiry=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000));
  await details.getByLabel('Autorización válida hasta',{exact:true}).fill(expiry);
  let operationStart=performance.now();
  await details.getByRole('button',{name:'Guardar versión en pausa',exact:true}).click();
  let policyList=await openPolicyList();let policy=policyList.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 1',exact:true})});
  await policy.getByText(/^En pausa/).waitFor();
  const saveMs=Math.round(performance.now()-operationStart);assert.ok(saveMs<=3000,`Policy save visible ${saveMs} ms exceeds 3000 ms`);
  const before={tasks:await db.task.count(),runs:await db.operationalAutomationRun.count(),notifications:await db.notification.count()};
  await policy.getByRole('button',{name:'Simular',exact:true}).click();
  await policy.getByText(/Simulación: 1 efectos propuestos/).waitFor();
  assert.deepEqual({tasks:await db.task.count(),runs:await db.operationalAutomationRun.count(),notifications:await db.notification.count()},before,'Simulation must not create tasks, attempts or notifications');
  await db.user.update({where:{id:f.users.worker.id},data:{hiddenFromSelectors:true}});
  await db.department.update({where:{id:f.areaId},data:{active:false}});
  try {
    await policy.getByRole('link',{name:'Preparar nueva versión',exact:true}).click();
    const editing=page.locator('details[open]').filter({has:page.getByText('Nueva versión del procedimiento',{exact:true})});
    try { await editing.getByLabel('Responsable',{exact:true}).waitFor(); } catch(error) { console.log('Policy editor diagnostics',page.url(),await page.locator('summary').allTextContents());throw error;}
    assert.equal(await editing.getByLabel('Responsable',{exact:true}).inputValue(),f.users.worker.id);
    assert.equal(await editing.getByLabel('Área',{exact:true}).inputValue(),f.areaId);
    assert.match(await editing.getByLabel('Responsable',{exact:true}).innerText(),/actual no disponible/);
  } finally {
    await db.user.update({where:{id:f.users.worker.id},data:{hiddenFromSelectors:false}});
    await db.department.update({where:{id:f.areaId},data:{active:true}});
  }
  await page.goto('http://localhost:3000/coordinacion/automatizaciones');
  policyList=await openPolicyList();policy=policyList.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 1',exact:true})});
  await policy.locator('select[name=state]').selectOption('pause');
  await Promise.all([page.waitForNavigation(),policy.getByRole('button',{name:'Guardar estado',exact:true}).click()]);
  policyList=await openPolicyList();policy=policyList.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 2',exact:true})});
  await policy.getByText(/^En pausa/).waitFor();
  await policy.locator('select[name=state]').selectOption('revoke');
  await Promise.all([page.waitForNavigation(),policy.getByRole('button',{name:'Guardar estado',exact:true}).click()]);
  policyList=await openPolicyList();policy=policyList.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 3',exact:true})});
  await policy.getByText(/^Revocada/).waitFor();
  assert.equal(await policy.getByRole('button',{name:'Guardar estado',exact:true}).count(),0);
  results.push({width,scenario:'policy-save-simulate-no-effects-pause-revoke-history',ms:saveMs,budgetMs:3000,status:'passed',automaticExecution:false});
  results.push({width,scenario:'authenticated-exact-command-retry-private-history-summary-paused-rules',ms:elapsed,budgetMs:2000,status:'passed',provider:'not-used'});await context.close();
 }
 console.log('Etapa 2 authenticated Fronti desktop/mobile journeys passed.');
 console.log('Synthetic Fronti and policies timings',JSON.stringify(results));
} finally {writeFileSync('etapa2-browser-results.json',JSON.stringify({browser:browser.version(),results,physicalSafari:false},null,2));await browser.close();await db.$disconnect();}
