import '../etapa1/guard.cjs';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
const f=JSON.parse(readFileSync('/tmp/etapa1-fixture.json','utf8'));
const browser=await chromium.launch({headless:true});
console.log("Synthetic browser",browser.version());
const results=[];
const db=new PrismaClient();
try {
 for (const width of [1280,390]) {
  const context=await browser.newContext({viewport:{width,height:900}});
  await context.addCookies([{name:'lor_session',value:f.users.admin.token,domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);
  await context.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname!=='localhost'||['/api/notifications/stream','/api/alarms','/api/auth/pulse'].some(p=>u.pathname.startsWith(p))?route.abort():route.continue();});
  const page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(15000);
  await page.goto('http://localhost:3000/fronti/procedimientos');
  await page.getByRole('heading',{name:'Procedimientos de Fronti',exact:true}).waitFor();
  const key=randomUUID();const message=`Crea una tarea: ETAPA2_FRONTI_${width}`;
  const started=performance.now();
  const response=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message,requestKey:key}});
  const body=await response.json();const elapsed=Math.round(performance.now()-started);
  assert.equal(response.status(),200,body.error);assert.match(body.reply,/Completado/);
  assert.ok(elapsed<=2000,`Fronti exact command took ${elapsed} ms; budget 2000 ms`);
  const href=/\/fronti\/procedimientos\?ejecucion=[a-z0-9]+/.exec(body.reply)?.[0];assert.ok(href);
  const retry=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message,requestKey:key}});assert.equal(retry.status(),200);assert.ok((await retry.json()).reply.includes(href));
  await page.goto('http://localhost:3000'+href);await page.getByRole('heading',{name:'Resultado: Completado',exact:true}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  console.log("Fronti UI width",width);
  await page.getByRole('button',{name:'Abrir Fronti',exact:true}).first().click();
  const panel=page.getByRole('region',{name:'Fronti',exact:true});
  await panel.getByRole('textbox',{name:'Mensaje para Fronti',exact:true}).fill(`Crea una tarea: ETAPA2_CHAT_${width}`);
  const visibleStart=performance.now();
  const [uiResponse]=await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/fronti'),panel.getByRole('button',{name:'Enviar a Fronti',exact:true}).click()]);
  const uiBody=await uiResponse.json();assert.equal(uiResponse.status(),200,uiBody.error);assert.match(uiBody.reply,/Completado/);
  const uiId=/ejecucion=([a-z0-9]+)/.exec(uiBody.reply)?.[1];assert.ok(uiId);
  await panel.getByText(new RegExp(uiId)).waitFor();
  const visibleMs=Math.round(performance.now()-visibleStart);assert.ok(visibleMs<=3000,`Fronti visible result took ${visibleMs} ms; budget 3000 ms`);
  results.push({width,scenario:'actual-chat-input-to-visible-result',ms:visibleMs,budgetMs:3000,status:'passed',provider:'not-used'});
  await panel.getByRole('button',{name:'Minimizar Fronti',exact:true}).click();
  const summary=await context.request.post('http://localhost:3000/api/fronti',{timeout:5000,headers:{Origin:'http://localhost:3000'},data:{message:'/resumen',requestKey:randomUUID()}});assert.equal(summary.status(),200);assert.match((await summary.json()).reply,/Coordinación: \/coordinacion/);
  await page.goto('http://localhost:3000/coordinacion/automatizaciones');await page.getByRole('heading',{name:'Reglas y procedimientos',exact:true}).waitFor();assert.ok((await page.locator('body').innerText()).includes('deshabilitada'));
  // The same public form saves a paused version, simulates without effects, then pauses/revokes.
  const policyName=`ETAPA2_POLICY_${width}`;
  const details=page.locator('details').filter({has:page.getByText('Nuevo procedimiento o mantenimiento preventivo',{exact:true})});
  await details.locator('summary').click();
  await details.getByLabel('Nombre',{exact:true}).fill(policyName);
  await details.getByLabel('Área',{exact:true}).selectOption(f.areaId);
  await details.getByLabel('Responsable',{exact:true}).selectOption(f.users.worker.id);
  await details.getByLabel('Instrucción',{exact:true}).fill('Inspección sintética declarada por persona autorizada');
  await details.getByLabel('Siguiente acción',{exact:true}).fill('Registrar resultado de inspección');
  await details.getByLabel('Evidencia requerida',{exact:true}).fill('Resultado informado');
  await details.getByLabel('Lista: un punto por línea',{exact:true}).fill('Revisar filtro\nInformar resultado');
  await details.getByLabel('Hora de Santiago',{exact:true}).fill('00:00');
  for(const checkbox of await details.locator('input[name=weekdays]').all())await checkbox.check();
  const expiry=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000));
  await details.getByLabel('Autorización válida hasta',{exact:true}).fill(expiry);
  let operationStart=performance.now();
  await details.getByRole('button',{name:'Guardar versión en pausa',exact:true}).click();
  let policy=page.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 1',exact:true})});
  await policy.getByText(/^En pausa/).waitFor();
  const saveMs=Math.round(performance.now()-operationStart);assert.ok(saveMs<=3000,`Policy save visible ${saveMs} ms exceeds 3000 ms`);
  const before={tasks:await db.task.count(),runs:await db.operationalAutomationRun.count(),notifications:await db.notification.count()};
  await policy.getByRole('button',{name:'Simular',exact:true}).click();
  await policy.getByText(/Simulación: 1 efectos propuestos/).waitFor();
  assert.deepEqual({tasks:await db.task.count(),runs:await db.operationalAutomationRun.count(),notifications:await db.notification.count()},before,'Simulation must not create tasks, attempts or notifications');
  await policy.locator('select[name=state]').selectOption('pause');
  await policy.getByRole('button',{name:'Guardar estado',exact:true}).click();
  policy=page.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 2',exact:true})});
  await policy.getByText(/^En pausa/).waitFor();
  await policy.locator('select[name=state]').selectOption('revoke');
  await policy.getByRole('button',{name:'Guardar estado',exact:true}).click();
  policy=page.locator('article').filter({has:page.getByRole('heading',{name:policyName+' · versión 3',exact:true})});
  await policy.getByText(/^Revocada/).waitFor();
  assert.equal(await policy.getByRole('button',{name:'Guardar estado',exact:true}).count(),0);
  results.push({width,scenario:'policy-save-simulate-no-effects-pause-revoke-history',ms:saveMs,budgetMs:3000,status:'passed',automaticExecution:false});
  results.push({width,scenario:'authenticated-exact-command-retry-private-history-summary-paused-rules',ms:elapsed,budgetMs:2000,status:'passed',provider:'not-used'});await context.close();
 }
 console.log('Etapa 2 authenticated Fronti desktop/mobile journeys passed.');
} finally {writeFileSync('etapa2-browser-results.json',JSON.stringify({browser:browser.version(),results,physicalSafari:false},null,2));await browser.close();await db.$disconnect();}
