'use client';

import { scheduleClock, scheduleLabel, collaboratorReference } from '@/domain/schedule-display';

import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Plus, CalendarDays } from 'lucide-react';
import { Button, SubmitButton } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { ActionForm, Field, Input, Select } from '@/components/ui/form';
import { dateDays, datePlus, SLOT_LABELS, EXTRA_LABELS } from '@/domain/schedule';
import { formatCalendarDate, formatDateTime } from '@/lib/format';
import { cn } from '@/lib/cn';
import { hotelDateKey } from '@/domain/time';
import { cancelScheduleSlotAction, moveScheduleSlotAction, changeScheduleExtraAction } from '@/server/actions/schedule';
import { ScheduleMutationFields, ScheduleReason, ScheduleSlotFields, type CalendarPlan, type CalendarSlot, type SchedulePerson, type ScheduleTemplateOption } from './schedule-forms';

type Destination = { slot: CalendarSlot; collaboratorId: string; date: string };
const hours = (minutes: number) => `${Math.floor(minutes / 60)} h${minutes % 60 ? ` ${minutes % 60} min` : ''}`;
export function ScheduleCalendar({ plan, people, templates, slots, holidays, canManage, canApprove, currentUserId, canReportOwn, now, totals }: { plan: CalendarPlan; people: SchedulePerson[]; templates: ScheduleTemplateOption[]; slots: CalendarSlot[]; holidays: { date: string; name: string }[]; canManage: boolean; canApprove: boolean; currentUserId: string; canReportOwn: boolean; now: string; totals: Record<string, number> }) {
  const [view, setView] = useState('semana'); const [cursor, setCursor] = useState(plan.startDate);
  const [selected, setSelected] = useState<CalendarSlot | null>(null); const [newCell, setNewCell] = useState<{ personId: string; date: string } | null>(null); const [destination, setDestination] = useState<Destination | null>(null); const [edit, setEdit] = useState(false);
  const days = useMemo(() => {
    if (view === 'mes') { const date = new Date(`${cursor}T00:00:00Z`); return dateDays(`${cursor.slice(0, 7)}-01`, new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0)).toISOString().slice(0, 10)); }
    const weekday = new Date(`${cursor}T00:00:00Z`).getUTCDay(); const start = view === 'semana' ? datePlus(cursor, -(weekday === 0 ? 6 : weekday - 1)) : cursor;
    return dateDays(start, datePlus(start, view === 'semana' ? 6 : 7));
  }, [cursor, view]);
  const byCell = useMemo(() => { const map = new Map<string, CalendarSlot[]>(); for (const slot of slots) { const key = `${slot.collaboratorId}:${slot.date}`; map.set(key, [...(map.get(key) ?? []), slot]); } return map; }, [slots]);
  const holidayMap = useMemo(() => new Map(holidays.map((h) => [h.date, h.name])), [holidays]);
  const canChange = (slot: CalendarSlot) => canManage && (slot.startAt ? slot.startAt > now : slot.date >= hotelDateKey(new Date(now)));
  const visiblePeople = people.filter((p) => canManage || slots.some((s) => s.collaboratorId === p.id));
  const jump = (direction: number) => { if (view === 'mes') { const d = new Date(`${cursor}T00:00:00Z`); setCursor(new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + direction, 1)).toISOString().slice(0, 10)); } else setCursor(datePlus(cursor, direction * (view === 'ciclo' ? 8 : 7))); };
  return <section className="card overflow-hidden" aria-label="Calendario del equipo">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-3"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-petrol-700" /><h2 className="font-semibold text-petrol-900">{formatCalendarDate(days[0])}–{formatCalendarDate(days[days.length - 1])}</h2></div><div className="flex items-center gap-2"><Button size="sm" variant="secondary" onClick={() => jump(-1)} disabled={days[0]! <= plan.startDate} aria-label="Periodo anterior"><ChevronLeft className="h-4 w-4" /></Button><select className="input-base text-sm" aria-label="Vista del calendario" value={view} onChange={(e) => { setView(e.target.value); setCursor(plan.startDate); }}><option value="semana">Semana calendario · 7 días</option><option value="ciclo">Ciclo · 8 días</option><option value="mes">Mes</option></select><Button size="sm" variant="secondary" onClick={() => jump(1)} disabled={days[days.length - 1]! >= plan.endDate} aria-label="Periodo siguiente"><ChevronRight className="h-4 w-4" /></Button></div></div>
    <p className="px-3 py-2 text-xs text-slate-600">{canManage ? 'Pulsa una casilla para programar. Arrastra una asignación o abre «Cambiar asignación» para mover, reasignar, intercambiar o agregar cobertura.' : 'Horario programado. La presencia y el turno operativo se confirman por separado.'}</p>
    <div className="overflow-x-auto"><table className="w-full border-separate border-spacing-0 text-sm"><caption className="sr-only">Malla por colaborador y fecha. Los turnos nocturnos indican su término al día siguiente.</caption><thead><tr><th scope="col" className="sticky left-0 top-0 z-30 min-w-[190px] border-b border-r border-slate-200 bg-slate-50 p-3 text-left">Persona / turnos</th>{days.map((date) => <th scope="col" key={date} className={cn('sticky top-0 z-20 min-w-[126px] border-b border-r border-slate-200 p-2 text-center', holidayMap.has(date) ? 'bg-purple-50' : 'bg-slate-50')}><span className="block text-xs font-normal capitalize">{new Date(`${date}T12:00:00Z`).toLocaleDateString('es-CL', { timeZone: 'UTC', weekday: 'short' })}</span>{date.slice(8)}/{date.slice(5, 7)}{holidayMap.has(date) && <span className="mt-1 block max-w-[126px] text-[10px] font-medium text-purple-800" title={holidayMap.get(date)}>Feriado · {holidayMap.get(date)}</span>}</th>)}<th scope="col" className="sticky top-0 min-w-[160px] border-b bg-slate-50 p-3">Horas programadas</th></tr></thead><tbody>{visiblePeople.map((person) => {
      const personSlots = slots.filter((s) => s.collaboratorId === person.id); const total = personSlots.reduce((n, s) => n + s.plannedMinutes, 0); const excess = Object.entries(totals).filter(([key, value]) => key.startsWith(`${person.id}:`) && person.weeklyMinutes && value > person.weeklyMinutes);
      return <tr key={person.id}><th scope="row" className="sticky left-0 z-10 border-b border-r border-slate-200 bg-white p-3 text-left align-top"><span className="block font-semibold text-petrol-900">{person.name}</span><span className="block text-xs font-normal text-slate-500">{collaboratorReference(person) ? `${collaboratorReference(person)} · ` : ''}{person.functionName}</span><span className="mt-1 block text-[10px] font-normal text-slate-500">{[...new Set(personSlots.filter((s) => s.kind === 'TURNO').map((s) => scheduleLabel(s)))].join(' · ') || 'Sin turnos asignados'}</span></th>{days.map((date) => {
        const entries = byCell.get(`${person.id}:${date}`) ?? []; const inPeriod = date >= plan.startDate && date <= plan.endDate;
        return <td key={date} className={cn('border-b border-r border-slate-200 p-1.5 align-top', !inPeriod && 'bg-slate-100', holidayMap.has(date) && 'bg-purple-50/40')} onDragOver={(e) => { if (canManage && inPeriod) e.preventDefault(); }} onDrop={(e) => { e.preventDefault(); const slot = slots.find((s) => s.id === e.dataTransfer.getData('text/aroh-schedule')); if (slot && inPeriod && canChange(slot)) setDestination({ slot, collaboratorId: person.id, date }); }}>
          {entries.map((slot) => <button key={slot.id} type="button" draggable={canChange(slot) && slot.extraKind === 'NINGUNO'} onDragStart={(e) => { e.dataTransfer.setData('text/aroh-schedule', slot.id); e.dataTransfer.effectAllowed = 'copyMove'; }} onClick={() => { setSelected(slot); setEdit(false); }} className={cn('mb-1 w-full rounded-md border px-2 py-2 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-petrol-500', slot.kind === 'LIBRE' ? 'border-amber-200 bg-amber-50 text-amber-900' : slot.kind === 'TURNO' ? 'border-petrol-200 bg-petrol-50 text-petrol-900 hover:bg-petrol-100' : 'border-slate-300 bg-slate-100 text-slate-700')} aria-label={`${person.name}, ${formatCalendarDate(date)}, ${scheduleLabel(slot)}`}><span className="block text-xs font-semibold">{slot.kind === 'TURNO' ? slot.code : SLOT_LABELS[slot.kind as keyof typeof SLOT_LABELS]}</span>{slot.kind === 'TURNO' && <span className="block tabular text-[11px]">{scheduleClock(slot)}</span>}{slot.extraKind !== 'NINGUNO' && <span className="mt-1 block text-[10px] font-medium">{EXTRA_LABELS[slot.extraKind]}{slot.extraMinutes ? ` · +${hours(slot.extraMinutes)}` : ''}<br />{EXTRA_LABELS[slot.extraStatus]}</span>}</button>)}
          {canManage && inPeriod && <button type="button" onClick={() => setNewCell({ personId: person.id, date })} className="flex min-h-8 w-full items-center justify-center rounded text-xs text-slate-500 hover:bg-slate-100" aria-label={`Programar a ${person.name} el ${formatCalendarDate(date)}`}><Plus className="h-3 w-3" />{!entries.length && <span className="ml-1">Programar</span>}</button>}{!entries.length && !canManage && inPeriod && <span className="text-[10px] text-slate-400">Sin programación</span>}
        </td>;
      })}<td className="border-b border-slate-200 p-3 align-top"><strong>{hours(total)}</strong><span className="block text-[10px] text-slate-500">Periodo completo · incluye extras solicitados</span>{excess.map(([key, value]) => <span key={key} className="mt-1 block text-[10px] text-amber-800">Semana {formatCalendarDate(key.slice(person.id.length + 1))}: {hours(value)}; referencia configurada {hours(person.weeklyMinutes!)}.</span>)}</td></tr>;
    })}</tbody></table>{!visiblePeople.length && <p className="p-6 text-center text-sm text-slate-600">{canManage ? 'Crea colaboradores del área para comenzar a programar.' : 'No hay asignaciones publicadas disponibles.'}</p>}</div>
    {newCell && <Dialog open onOpenChange={(open) => { if (!open) setNewCell(null); }} title="Programar colaborador"><ScheduleSlotFields plan={plan} people={people} templates={templates} personId={newCell.personId} date={newCell.date} onSaved={() => setNewCell(null)} /></Dialog>}
    {destination && <MoveDialog key={`${destination.slot.id}:${destination.collaboratorId}:${destination.date}`} destination={destination} plan={plan} people={people} slots={slots} onClose={() => setDestination(null)} />}
    {selected && <Dialog open onOpenChange={(open) => { if (!open) setSelected(null); }} title={`${scheduleLabel(selected)} · ${people.find((p) => p.id === selected.collaboratorId)?.name ?? 'Colaborador'}`} description={`${formatCalendarDate(selected.date)}${selected.startAt ? ` · ${formatDateTime(selected.startAt)} → ${formatDateTime(selected.endAt)}` : ''}`}>
      {edit ? <ScheduleSlotFields plan={plan} people={people} templates={templates} slot={selected} onSaved={() => setSelected(null)} /> : <><div className="space-y-2 text-sm"><p>{selected.note || 'Sin observación operativa.'}</p>{selected.extraKind !== 'NINGUNO' && <p><strong>{EXTRA_LABELS[selected.extraKind]}</strong> · {EXTRA_LABELS[selected.extraStatus]}{selected.reportedExtraMinutes !== null && ` · realización informada: ${hours(selected.reportedExtraMinutes)}`}</p>}</div>
        {canChange(selected) && <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setEdit(true)}>Editar / registrar extra</Button>{selected.extraKind === 'NINGUNO' && <Button size="sm" variant="secondary" onClick={() => { setDestination({ slot: selected, collaboratorId: selected.collaboratorId, date: selected.date }); setSelected(null); }}>Cambiar asignación</Button>}<CancelDialog plan={plan} slot={selected} onSaved={() => setSelected(null)} /></div>}
        {selected.extraKind !== 'NINGUNO' && <ExtraActions plan={plan} slot={selected} canApprove={canApprove} canReport={canManage || (canReportOwn && people.find((p) => p.id === selected.collaboratorId)?.userId === currentUserId)} now={now} onSaved={() => setSelected(null)} />}
      </>}
    </Dialog>}
  </section>;
}
function MoveDialog({ destination, plan, people, slots, onClose }: { destination: Destination; plan: CalendarPlan; people: SchedulePerson[]; slots: CalendarSlot[]; onClose: () => void }) {
  const [person, setPerson] = useState(destination.collaboratorId); const [date, setDate] = useState(destination.date); const [mode, setMode] = useState(destination.slot.collaboratorId === destination.collaboratorId ? 'MOVER' : 'REASIGNAR'); const [requestKey] = useState(() => crypto.randomUUID());
  const targets = slots.filter((s) => s.collaboratorId === person && s.date === date && s.id !== destination.slot.id && s.extraKind === 'NINGUNO');
  const options = [{ value: destination.slot.collaboratorId === person ? 'MOVER' : 'REASIGNAR', label: destination.slot.collaboratorId === person ? 'Mover a otra fecha' : 'Reasignar al colaborador de destino' }, ...(targets.length ? [{ value: 'INTERCAMBIAR', label: 'Intercambiar ambas asignaciones' }] : []), { value: 'AGREGAR', label: 'Agregar cobertura y conservar el original' }];
  const activeMode = options.some((o) => o.value === mode) ? mode : options[0]!.value;
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }} title="Cambiar asignación" description="Revisa origen y destino. El sistema comprobará pertenencia al área, horarios que se cruzan antes de guardar.">
    <ActionForm action={moveScheduleSlotAction} closeOnSuccess refreshOnSuccess onSuccess={onClose}><ScheduleMutationFields plan={plan} requestKey={requestKey} /><input type="hidden" name="slotId" value={destination.slot.id} /><p className="rounded bg-slate-50 p-2 text-sm">Origen: <strong>{people.find((p) => p.id === destination.slot.collaboratorId)?.name}</strong> · {formatCalendarDate(destination.slot.date)} · {scheduleLabel(destination.slot)}</p><Field label="Colaborador de destino" name="targetCollaboratorId"><Select name="targetCollaboratorId" value={person} onChange={(e) => setPerson(e.target.value)} options={people.map((p) => ({ value: p.id, label: p.name }))} /></Field><Field label="Fecha de destino" name="targetDate"><Input name="targetDate" type="date" value={date} onChange={(e) => setDate(e.target.value)} min={plan.startDate} max={plan.endDate} required /></Field><Field label="Qué hacer" name="mode"><Select name="mode" value={activeMode} onChange={(e) => setMode(e.target.value)} options={options} /></Field>{activeMode === 'INTERCAMBIAR' && <Field label="Asignación que vuelve al origen" name="targetSlotId"><Select name="targetSlotId" required options={targets.map((s) => ({ value: s.id, label: scheduleLabel(s) }))} /></Field>}<p className="text-xs text-slate-600">{activeMode === 'AGREGAR' ? 'El original permanece y se crea otra asignación.' : activeMode === 'INTERCAMBIAR' ? 'Las dos asignaciones cambian juntas. Si una falla, no se aplica ninguna.' : 'El destino sustituye la asignación original, cuyo historial se conserva.'}</p><ScheduleReason required={plan.status === 'PUBLICADO'} /><SubmitButton>Confirmar cambio</SubmitButton></ActionForm>
  </Dialog>;
}
function CancelDialog({ plan, slot, onSaved }: { plan: CalendarPlan; slot: CalendarSlot; onSaved: () => void }) { const [requestKey] = useState(() => crypto.randomUUID()); return <Dialog trigger="Cancelar asignación" triggerVariant="danger" triggerSize="sm" title="Cancelar asignación" description="Se retira del calendario vigente y se conserva en el historial."><ActionForm action={cancelScheduleSlotAction} closeOnSuccess refreshOnSuccess onSuccess={onSaved}><ScheduleMutationFields plan={plan} requestKey={requestKey} /><input type="hidden" name="slotId" value={slot.id} /><ScheduleReason /><SubmitButton variant="danger">Confirmar cancelación</SubmitButton></ActionForm></Dialog>; }
function ExtraActions({ plan, slot, canApprove, canReport, now, onSaved }: { plan: CalendarPlan; slot: CalendarSlot; canApprove: boolean; canReport: boolean; now: string; onSaved: () => void }) {
  const actions = [...(canApprove && slot.extraStatus === 'PENDIENTE' ? ['APROBAR', 'RECHAZAR'] : []), ...(canReport && slot.extraStatus === 'APROBADO' && slot.endAt && slot.endAt <= now ? ['REPORTAR'] : []), ...(canApprove && slot.extraStatus === 'REPORTADO' ? ['VALIDAR'] : [])];
  const labels: Record<string, string> = { APROBAR: 'Aprobar extra', RECHAZAR: 'Rechazar extra', REPORTAR: 'Informar realización', VALIDAR: 'Validar realización' };
  return <div className="mt-3 flex flex-wrap gap-2">{actions.map((action) => <ExtraAction key={action} plan={plan} slot={slot} action={action} label={labels[action]!} onSaved={onSaved} />)}</div>;
}
function ExtraAction({ plan, slot, action, label, onSaved }: { plan: CalendarPlan; slot: CalendarSlot; action: string; label: string; onSaved: () => void }) { const [requestKey] = useState(() => crypto.randomUUID()); return <Dialog trigger={label} triggerVariant="secondary" triggerSize="sm" title={label} description="La aprobación y la realización son registros distintos. Este módulo no calcula remuneraciones."><ActionForm action={changeScheduleExtraAction} closeOnSuccess refreshOnSuccess onSuccess={onSaved}><ScheduleMutationFields plan={plan} requestKey={requestKey} /><input type="hidden" name="slotId" value={slot.id} /><input type="hidden" name="action" value={action} />{action === 'REPORTAR' && <Field label="Minutos adicionales efectivamente realizados" name="reportedMinutes"><Input name="reportedMinutes" type="number" min={0} max={2160} required defaultValue={slot.extraMinutes || slot.plannedMinutes} /></Field>}<ScheduleReason /><SubmitButton>{label}</SubmitButton></ActionForm></Dialog>; }
