'use client';

import { ActionForm, Field, Input, Select } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { saveScheduleCollaboratorAction, saveScheduleTemplateAction, saveScheduleCoverageAction, saveScheduleGrantAction, saveScheduleHolidayAction } from '@/server/actions/schedule';

type Area = { id: string; name: string };
type Account = { id: string; name: string };
export type CatalogPerson = { id: string; version: number; employeeCode: string; name: string; functionName: string; active: boolean; userId: string | null; weeklyMinutes: number | null; minRestMinutes: number; memberships: { departmentId: string; active: boolean }[] };
export function ScheduleCollaboratorForm({ areas, accounts, departmentId, person, editable = true }: { areas: Area[]; accounts: Account[]; departmentId: string; person?: CatalogPerson; editable?: boolean }) {
  if (!editable) return <p className="text-xs text-slate-500">Perfil compartido con otra área: solicita al administrador su modificación.</p>;
  if (person?.userId && !person.active) return <p className="text-xs text-slate-500">Usuario inactivo u oculto. Su historial se conserva; no admite nuevas asignaciones.</p>;
  return <Dialog trigger={person ? person.userId ? 'Editar planificación' : 'Vincular usuario' : 'Añadir usuario al área'} triggerVariant={person ? 'secondary' : 'gold'} triggerSize={person ? 'sm' : 'md'} title="Planificación del usuario" description="La persona se crea una sola vez en Usuarios. Aquí sólo se definen sus áreas y horas semanales; no se crea otra cuenta ni otro colaborador.">
    <ActionForm action={saveScheduleCollaboratorAction} closeOnSuccess refreshOnSuccess>
      {person && <input type="hidden" name="id" value={person.id} />}<input type="hidden" name="version" value={person?.version ?? 0} />
      {person?.userId ? <><input type="hidden" name="userId" value={person.userId} /><p className="rounded bg-slate-50 p-3 text-sm"><strong>{person.name}</strong><br />{person.functionName}</p></> : <Field label="Usuario existente" name="userId" hint="Selecciona una cuenta ya creada. El nombre, rol y estado se toman de Usuarios."><Select name="userId" required defaultValue="" options={[{ value: '', label: 'Seleccionar usuario…' }, ...accounts.map((a) => ({ value: a.id, label: a.name }))]} /></Field>}
      <fieldset><legend className="mb-2 text-sm font-medium text-slate-700">Áreas donde puede trabajar</legend><div className="grid gap-2 sm:grid-cols-2">{areas.map((area) => <label key={area.id} className="flex gap-2 text-sm"><input type="checkbox" name="departmentIds" value={area.id} defaultChecked={person ? person.memberships.some((m) => m.active && m.departmentId === area.id) : area.id === departmentId} />{area.name}</label>)}</div></fieldset>
      <Field label="Horas semanales de referencia" name="weeklyHours" hint="Ejemplo: 42 o 42,5 horas. 0 = sin referencia. No incluye descuentos ni controles de descanso."><Input name="weeklyHours" type="number" min={0} max={168} step="any" required defaultValue={(person?.weeklyMinutes ?? 0) / 60} /></Field>
      <SubmitButton>Guardar planificación</SubmitButton>
    </ActionForm>
  </Dialog>;
}
export function ScheduleTemplateForm({ departmentId, template }: { departmentId: string; template?: { code: string; label: string; startTime: string; endTime: string; crossesMidnight: boolean; breakStartTime: string | null; breakMinutes: number; breakPaid: boolean } }) {
  return <Dialog trigger={template ? 'Crear revisión' : 'Crear plantilla'} triggerVariant={template ? 'secondary' : 'gold'} triggerSize={template ? 'sm' : 'md'} title={template ? `Nueva revisión de ${template.code}` : 'Crear plantilla del área'} description="Una revisión nueva se utiliza para asignaciones futuras. Los horarios ya guardados conservan su código y horas originales.">
    <ActionForm action={saveScheduleTemplateAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Código" name="code"><Input name="code" required maxLength={16} defaultValue={template?.code} readOnly={!!template} placeholder="RD01" /></Field><Field label="Descripción" name="label"><Input name="label" required maxLength={100} defaultValue={template?.label} /></Field><Field label="Inicio" name="startTime"><Input type="time" name="startTime" required defaultValue={template?.startTime} /></Field><Field label="Término" name="endTime"><Input type="time" name="endTime" required defaultValue={template?.endTime} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="crossesMidnight" defaultChecked={template?.crossesMidnight} />Termina al día siguiente</label><p className="text-xs text-slate-600">Las horas programadas corresponden al intervalo completo entre inicio y término. Este módulo no gestiona descansos ni colaciones.</p><SubmitButton>Guardar plantilla</SubmitButton></ActionForm>
  </Dialog>;
}
export function ScheduleCoverageForm({ departmentId, rule }: { departmentId: string; rule?: { id: string; name: string; functionName: string | null; weekdays: number[]; startTime: string; endTime: string; crossesMidnight: boolean; minimum: number; active: boolean } }) {
  const weekdays = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
  return <Dialog trigger={rule ? 'Editar regla' : 'Definir cobertura mínima'} triggerVariant={rule ? 'secondary' : 'gold'} triggerSize={rule ? 'sm' : 'md'} title="Cobertura mínima por franja" description="El sistema comparará personas habilitadas y disponibles en cada intervalo, no sólo el total de personas del día."><ActionForm action={saveScheduleCoverageAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} />{rule && <input type="hidden" name="id" value={rule.id} />}<Field label="Nombre de la regla" name="name"><Input name="name" required defaultValue={rule?.name} maxLength={100} placeholder="Refuerzo de tarde" /></Field><Field label="Función requerida (opcional)" name="functionName" hint="Vacío = cualquier función del área. Con función, sólo se cuentan coincidencias exactas."><Input name="functionName" maxLength={100} defaultValue={rule?.functionName ?? ''} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Desde" name="startTime"><Input type="time" name="startTime" required defaultValue={rule?.startTime ?? '00:00'} /></Field><Field label="Hasta" name="endTime"><Input type="time" name="endTime" required defaultValue={rule?.endTime ?? '00:00'} /></Field></div><label className="flex gap-2 text-sm"><input name="crossesMidnight" type="checkbox" defaultChecked={rule?.crossesMidnight ?? true} />Termina al día siguiente</label><Field label="Personas necesarias" name="minimum"><Input type="number" name="minimum" min={1} max={100} required defaultValue={rule?.minimum ?? 1} /></Field><fieldset><legend className="mb-2 text-sm font-medium text-slate-700">Días de aplicación</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{weekdays.map((label, value) => <label key={label} className="flex gap-2 text-sm"><input type="checkbox" name="weekdays" value={value} defaultChecked={rule ? rule.weekdays.includes(value) : true} />{label}</label>)}</div></fieldset><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={rule?.active ?? true} />Regla activa</label><SubmitButton>Guardar regla</SubmitButton></ActionForm></Dialog>;
}
export function ScheduleGrantForm({ areas, accounts }: { areas: Area[]; accounts: Account[] }) { return <ActionForm action={saveScheduleGrantAction} refreshOnSuccess><Field label="Cuenta" name="userId"><Select name="userId" required options={accounts.map((a) => ({ value: a.id, label: a.name }))} /></Field><Field label="Área adicional" name="departmentId"><Select name="departmentId" required options={areas.map((a) => ({ value: a.id, label: a.name }))} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked />Habilitar alcance adicional (desmarcar para retirarlo)</label><p className="text-xs text-slate-600">El alcance no concede permisos. Habilita las acciones del rol desde Roles y permisos. El área principal de la cuenta también determina su alcance.</p><SubmitButton variant="secondary">Guardar alcance</SubmitButton></ActionForm>; }
export function ScheduleHolidayForm({ holiday }: { holiday?: { date: string; name: string; source: string; active: boolean } }) { return <Dialog trigger={holiday ? 'Editar' : 'Añadir feriado'} triggerVariant="secondary" triggerSize="sm" title="Feriado del alojamiento"><ActionForm action={saveScheduleHolidayAction} closeOnSuccess refreshOnSuccess><Field label="Fecha" name="date"><Input name="date" type="date" required defaultValue={holiday?.date} readOnly={!!holiday} /></Field><Field label="Nombre" name="name"><Input name="name" required maxLength={160} defaultValue={holiday?.name} /></Field><Field label="Fuente / motivo" name="source"><Input name="source" required maxLength={1000} defaultValue={holiday?.source} placeholder="Fuente oficial o motivo del feriado aplicable" /></Field><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={holiday?.active ?? true} />Feriado activo</label><SubmitButton>Guardar feriado</SubmitButton></ActionForm></Dialog>; }
