'use client';

import { ActionForm, Field, Input, Select } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { saveScheduleCollaboratorAction, saveScheduleTemplateAction, saveScheduleCoverageAction, saveScheduleGrantAction, saveScheduleHolidayAction } from '@/server/actions/schedule';

type Area = { id: string; name: string };
type Account = { id: string; name: string };
export type CatalogPerson = { id: string; version: number; employeeCode: string; name: string; functionName: string; active: boolean; userId: string | null; weeklyMinutes: number | null; minRestMinutes: number; memberships: { departmentId: string; active: boolean }[] };
export function ScheduleCollaboratorForm({ areas, accounts, departmentId, person, editable = true }: { areas: Area[]; accounts: Account[]; departmentId: string; person?: CatalogPerson; editable?: boolean }) {
  if (!editable) return <p className="text-xs text-slate-500">Perfil compartido con otra área: solicita al administrador su modificación.</p>;
  return <Dialog trigger={person ? 'Editar colaborador' : 'Crear colaborador'} triggerVariant={person ? 'secondary' : 'gold'} triggerSize={person ? 'sm' : 'md'} title={person ? 'Editar colaborador' : 'Crear colaborador'} description="El colaborador puede tener horarios sin una cuenta de acceso. Vincula una cuenta sólo si corresponde a la misma persona.">
    <ActionForm action={saveScheduleCollaboratorAction} closeOnSuccess refreshOnSuccess>{person && <input type="hidden" name="id" value={person.id} />}<input type="hidden" name="version" value={person?.version ?? 0} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Código de colaborador" name="employeeCode" hint="Identificador estable para reconocer las cargas; no se usa el nombre como clave."><Input name="employeeCode" required maxLength={32} pattern="[A-Za-z0-9_-]+" defaultValue={person?.employeeCode} placeholder="COL001" /></Field><Field label="Nombre" name="name"><Input name="name" required maxLength={160} defaultValue={person?.name} /></Field></div><Field label="Función operativa" name="functionName" hint="Usa la misma denominación que en las reglas de cobertura."><Input name="functionName" required maxLength={100} defaultValue={person?.functionName} placeholder="Recepcionista, camarera, técnico…" /></Field><fieldset><legend className="mb-2 text-sm font-medium text-slate-700">Áreas donde puede trabajar</legend><div className="grid gap-2 sm:grid-cols-2">{areas.map((area) => <label key={area.id} className="flex gap-2 text-sm"><input type="checkbox" name="departmentIds" value={area.id} defaultChecked={person ? person.memberships.some((m) => m.active && m.departmentId === area.id) : area.id === departmentId} />{area.name}</label>)}</div></fieldset><Field label="Cuenta vinculada (opcional)" name="userId"><Select name="userId" defaultValue={person?.userId ?? ''} options={[{ value: '', label: 'Sin cuenta de acceso' }, ...accounts.map((a) => ({ value: a.id, label: a.name }))]} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Referencia semanal en minutos (opcional)" name="weeklyMinutes" hint="0 = sin referencia. Configúrala según el contrato y régimen aplicable."><Input name="weeklyMinutes" type="number" min={0} max={10080} defaultValue={person?.weeklyMinutes ?? 0} /></Field><Field label="Descanso mínimo entre jornadas (minutos)" name="minRestMinutes" hint="0 = no configurado. Si se define, bloquea cambios que lo incumplan."><Input name="minRestMinutes" type="number" min={0} max={2880} defaultValue={person?.minRestMinutes ?? 0} /></Field></div><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={person?.active ?? true} />Colaborador activo</label><SubmitButton>Guardar colaborador</SubmitButton></ActionForm>
  </Dialog>;
}
export function ScheduleTemplateForm({ departmentId, template }: { departmentId: string; template?: { code: string; label: string; startTime: string; endTime: string; crossesMidnight: boolean; breakStartTime: string | null; breakMinutes: number; breakPaid: boolean } }) {
  return <Dialog trigger={template ? 'Crear revisión' : 'Crear plantilla'} triggerVariant={template ? 'secondary' : 'gold'} triggerSize={template ? 'sm' : 'md'} title={template ? `Nueva revisión de ${template.code}` : 'Crear plantilla del área'} description="Una revisión nueva se utiliza para asignaciones futuras. Los horarios ya guardados conservan su código, horas y colación originales.">
    <ActionForm action={saveScheduleTemplateAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Código" name="code"><Input name="code" required maxLength={16} defaultValue={template?.code} readOnly={!!template} placeholder="RD01" /></Field><Field label="Descripción" name="label"><Input name="label" required maxLength={100} defaultValue={template?.label} /></Field><Field label="Inicio" name="startTime"><Input type="time" name="startTime" required defaultValue={template?.startTime} /></Field><Field label="Término" name="endTime"><Input type="time" name="endTime" required defaultValue={template?.endTime} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="crossesMidnight" defaultChecked={template?.crossesMidnight} />Termina al día siguiente</label><div className="grid gap-3 sm:grid-cols-2"><Field label="Inicio de colación" name="breakStartTime"><Input type="time" name="breakStartTime" defaultValue={template?.breakStartTime ?? ''} /></Field><Field label="Duración de colación (minutos)" name="breakMinutes"><Input type="number" name="breakMinutes" min={0} max={180} defaultValue={template?.breakMinutes ?? 0} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="breakPaid" defaultChecked={template?.breakPaid} />Colación incluida en el cómputo de horas</label><p className="text-xs text-slate-600">La colación siempre se descuenta de la cobertura disponible durante ese intervalo, aunque esté incluida en el cómputo de horas.</p><SubmitButton>Guardar plantilla</SubmitButton></ActionForm>
  </Dialog>;
}
export function ScheduleCoverageForm({ departmentId, rule }: { departmentId: string; rule?: { id: string; name: string; functionName: string | null; weekdays: number[]; startTime: string; endTime: string; crossesMidnight: boolean; minimum: number; active: boolean } }) {
  const weekdays = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
  return <Dialog trigger={rule ? 'Editar regla' : 'Definir cobertura mínima'} triggerVariant={rule ? 'secondary' : 'gold'} triggerSize={rule ? 'sm' : 'md'} title="Cobertura mínima por franja" description="El sistema comparará personas habilitadas y disponibles en cada intervalo, no sólo el total de personas del día."><ActionForm action={saveScheduleCoverageAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} />{rule && <input type="hidden" name="id" value={rule.id} />}<Field label="Nombre de la regla" name="name"><Input name="name" required defaultValue={rule?.name} maxLength={100} placeholder="Refuerzo de tarde" /></Field><Field label="Función requerida (opcional)" name="functionName" hint="Vacío = cualquier función del área. Con función, sólo se cuentan coincidencias exactas."><Input name="functionName" maxLength={100} defaultValue={rule?.functionName ?? ''} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Desde" name="startTime"><Input type="time" name="startTime" required defaultValue={rule?.startTime ?? '00:00'} /></Field><Field label="Hasta" name="endTime"><Input type="time" name="endTime" required defaultValue={rule?.endTime ?? '00:00'} /></Field></div><label className="flex gap-2 text-sm"><input name="crossesMidnight" type="checkbox" defaultChecked={rule?.crossesMidnight ?? true} />Termina al día siguiente</label><Field label="Personas necesarias" name="minimum"><Input type="number" name="minimum" min={1} max={100} required defaultValue={rule?.minimum ?? 1} /></Field><fieldset><legend className="mb-2 text-sm font-medium text-slate-700">Días de aplicación</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{weekdays.map((label, value) => <label key={label} className="flex gap-2 text-sm"><input type="checkbox" name="weekdays" value={value} defaultChecked={rule ? rule.weekdays.includes(value) : true} />{label}</label>)}</div></fieldset><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={rule?.active ?? true} />Regla activa</label><SubmitButton>Guardar regla</SubmitButton></ActionForm></Dialog>;
}
export function ScheduleGrantForm({ areas, accounts }: { areas: Area[]; accounts: Account[] }) { return <ActionForm action={saveScheduleGrantAction} refreshOnSuccess><Field label="Cuenta" name="userId"><Select name="userId" required options={accounts.map((a) => ({ value: a.id, label: a.name }))} /></Field><Field label="Área adicional" name="departmentId"><Select name="departmentId" required options={areas.map((a) => ({ value: a.id, label: a.name }))} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked />Habilitar alcance adicional (desmarcar para retirarlo)</label><p className="text-xs text-slate-600">El alcance no concede permisos. Habilita las acciones del rol desde Roles y permisos. El área principal de la cuenta también determina su alcance.</p><SubmitButton variant="secondary">Guardar alcance</SubmitButton></ActionForm>; }
export function ScheduleHolidayForm({ holiday }: { holiday?: { date: string; name: string; source: string; active: boolean } }) { return <Dialog trigger={holiday ? 'Editar' : 'Añadir feriado'} triggerVariant="secondary" triggerSize="sm" title="Feriado del alojamiento"><ActionForm action={saveScheduleHolidayAction} closeOnSuccess refreshOnSuccess><Field label="Fecha" name="date"><Input name="date" type="date" required defaultValue={holiday?.date} readOnly={!!holiday} /></Field><Field label="Nombre" name="name"><Input name="name" required maxLength={160} defaultValue={holiday?.name} /></Field><Field label="Fuente / motivo" name="source"><Input name="source" required maxLength={1000} defaultValue={holiday?.source} placeholder="Fuente oficial o motivo del feriado aplicable" /></Field><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={holiday?.active ?? true} />Feriado activo</label><SubmitButton>Guardar feriado</SubmitButton></ActionForm></Dialog>; }
