'use client';

import { ActionForm, Field, Input, Select } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { saveScheduleCollaboratorAction, saveScheduleTemplateAction, saveScheduleCoverageAction, saveScheduleGrantAction, saveScheduleHolidayAction } from '@/server/actions/schedule';

type Area = { id: string; name: string };
type Account = { id: string; name: string };
export type CatalogPerson = { id: string; version: number; employeeCode: string; name: string; functionName: string; active: boolean; userId: string | null; weeklyMinutes: number | null; minRestMinutes: number; memberships: { departmentId: string; active: boolean }[] };
export function ScheduleCollaboratorForm({ accounts, departmentId, person, editable = true }: { areas: Area[]; accounts: Account[]; departmentId: string; person?: CatalogPerson; editable?: boolean }) {
  if (!editable) return <p className="text-xs text-slate-500">Perfil compartido: el administrador puede editar su referencia global.</p>;
  return <Dialog trigger={person ? 'Editar referencia' : 'Añadir usuario al área'} title={person ? 'Referencia del usuario' : 'Añadir usuario al área'} description="Selecciona una cuenta existente. Añadir un área conserva sus otras áreas, referencia e historial.">
    <ActionForm action={saveScheduleCollaboratorAction} closeOnSuccess refreshOnSuccess>
      {person && <><input type="hidden" name="id" value={person.id} /><input type="hidden" name="version" value={person.version} /></>}
      <Field label="Usuario" name="userId"><Select name="userId" required defaultValue={person?.userId ?? ''} options={[{ value: '', label: 'Seleccionar usuario' }, ...accounts.filter(a => !person?.userId || a.id === person.userId).map(a => ({ value: a.id, label: a.name }))]} /></Field>
      <Field label="Función operativa" name="functionName"><Input name="functionName" maxLength={100} defaultValue={person?.functionName} placeholder="Se usa el rol del usuario si no indicas otra función" /></Field>
      <input type="hidden" name="departmentIds" value={departmentId} />
      {person && <><Field label="Referencia semanal (horas)" name="weeklyHours" hint="0 = sin referencia."><Input name="weeklyHours" type="number" min={0} max={168} step="0.01" defaultValue={Math.round((person.weeklyMinutes ?? 0) / 60 * 100) / 100} /></Field><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={person.active} />Usuario habilitado para el horario</label></>}
      <SubmitButton>{person ? 'Guardar referencia' : 'Añadir usuario'}</SubmitButton>
    </ActionForm>
  </Dialog>;
}
export function ScheduleTemplateForm({ departmentId, template }: { departmentId: string; template?: { code: string; label: string; startTime: string; endTime: string; crossesMidnight: boolean; breakStartTime: string | null; breakMinutes: number; breakPaid: boolean } }) {
  return <Dialog trigger={template ? 'Crear revisión' : 'Crear plantilla'} triggerVariant={template ? 'secondary' : 'gold'} triggerSize={template ? 'sm' : 'md'} title={template ? `Nueva revisión de ${template.code}` : 'Crear plantilla del área'} description="Una revisión nueva se utiliza para asignaciones futuras. Los horarios ya guardados conservan su código, horas originales.">
    <ActionForm action={saveScheduleTemplateAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Código" name="code"><Input name="code" required maxLength={16} defaultValue={template?.code} readOnly={!!template} placeholder="RD01" /></Field><Field label="Descripción" name="label"><Input name="label" required maxLength={100} defaultValue={template?.label} /></Field><Field label="Inicio" name="startTime"><Input type="time" name="startTime" required defaultValue={template?.startTime} /></Field><Field label="Término" name="endTime"><Input type="time" name="endTime" required defaultValue={template?.endTime} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="crossesMidnight" defaultChecked={template?.crossesMidnight} />Termina al día siguiente</label><SubmitButton>Guardar plantilla</SubmitButton></ActionForm>
  </Dialog>;
}
export function ScheduleCoverageForm({ departmentId, rule }: { departmentId: string; rule?: { id: string; name: string; functionName: string | null; weekdays: number[]; startTime: string; endTime: string; crossesMidnight: boolean; minimum: number; active: boolean } }) {
  const weekdays = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
  return <Dialog trigger={rule ? 'Editar regla' : 'Definir cobertura mínima'} triggerVariant={rule ? 'secondary' : 'gold'} triggerSize={rule ? 'sm' : 'md'} title="Cobertura mínima por franja" description="El sistema comparará personas habilitadas y disponibles en cada intervalo, no sólo el total de personas del día."><ActionForm action={saveScheduleCoverageAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId} />{rule && <input type="hidden" name="id" value={rule.id} />}<Field label="Nombre de la regla" name="name"><Input name="name" required defaultValue={rule?.name} maxLength={100} placeholder="Refuerzo de tarde" /></Field><Field label="Función requerida (opcional)" name="functionName" hint="Vacío = cualquier función del área. Con función, sólo se cuentan coincidencias exactas."><Input name="functionName" maxLength={100} defaultValue={rule?.functionName ?? ''} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Desde" name="startTime"><Input type="time" name="startTime" required defaultValue={rule?.startTime ?? '00:00'} /></Field><Field label="Hasta" name="endTime"><Input type="time" name="endTime" required defaultValue={rule?.endTime ?? '00:00'} /></Field></div><label className="flex gap-2 text-sm"><input name="crossesMidnight" type="checkbox" defaultChecked={rule?.crossesMidnight ?? true} />Termina al día siguiente</label><Field label="Personas necesarias" name="minimum"><Input type="number" name="minimum" min={1} max={100} required defaultValue={rule?.minimum ?? 1} /></Field><fieldset><legend className="mb-2 text-sm font-medium text-slate-700">Días de aplicación</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{weekdays.map((label, value) => <label key={label} className="flex gap-2 text-sm"><input type="checkbox" name="weekdays" value={value} defaultChecked={rule ? rule.weekdays.includes(value) : true} />{label}</label>)}</div></fieldset><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={rule?.active ?? true} />Regla activa</label><SubmitButton>Guardar regla</SubmitButton></ActionForm></Dialog>;
}
export function ScheduleGrantForm({ areas, accounts }: { areas: Area[]; accounts: Account[] }) { return <ActionForm action={saveScheduleGrantAction} refreshOnSuccess><Field label="Cuenta" name="userId"><Select name="userId" required options={accounts.map((a) => ({ value: a.id, label: a.name }))} /></Field><Field label="Área adicional" name="departmentId"><Select name="departmentId" required options={areas.map((a) => ({ value: a.id, label: a.name }))} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked />Habilitar alcance adicional (desmarcar para retirarlo)</label><p className="text-xs text-slate-600">El alcance no concede permisos. Habilita las acciones del rol desde Roles y permisos. El área principal de la cuenta también determina su alcance.</p><SubmitButton variant="secondary">Guardar alcance</SubmitButton></ActionForm>; }
export function ScheduleHolidayForm({ holiday }: { holiday?: { date: string; name: string; source: string; active: boolean } }) { return <Dialog trigger={holiday ? 'Editar' : 'Añadir feriado'} triggerVariant="secondary" triggerSize="sm" title="Feriado del alojamiento"><ActionForm action={saveScheduleHolidayAction} closeOnSuccess refreshOnSuccess><Field label="Fecha" name="date"><Input name="date" type="date" required defaultValue={holiday?.date} readOnly={!!holiday} /></Field><Field label="Nombre" name="name"><Input name="name" required maxLength={160} defaultValue={holiday?.name} /></Field><Field label="Fuente / motivo" name="source"><Input name="source" required maxLength={1000} defaultValue={holiday?.source} placeholder="Fuente oficial o motivo del feriado aplicable" /></Field><label className="flex gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={holiday?.active ?? true} />Feriado activo</label><SubmitButton>Guardar feriado</SubmitButton></ActionForm></Dialog>; }
