import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { prisma } from '@/lib/prisma';
import { requirePageAnyPermission } from '@/server/auth/guard';
import { hasPermission } from '@/server/auth/current-user';
import { ROLE_KEYS } from '@/lib/permissions';
import { listStaffLoans, listSupervisorKeys } from '@/server/services/key-staff';
import { saveKeyAreaAction, createAreaKeyAction, saveSupervisorKeyAction, returnStaffKeyAction } from '@/server/actions/key-staff';
import { StaffLoanForm } from '@/components/keys/staff-loan-form';
import { Card, CardHeader } from '@/components/ui/card';
import { ActionForm, Field, Input } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { formatDateTime } from '@/lib/format';
import { KEY_STATUS_LABELS } from '@/domain/rooms';
export const metadata = { title: 'Áreas y entregas a personal' };
export const dynamic = 'force-dynamic';
export default async function StaffKeysPage() {
  const user = await requirePageAnyPermission(['key.assign', 'key.inventory', 'key.stock']);
  const canAssign = hasPermission(user, 'key.assign');
  const canStock = hasPermission(user, 'key.stock');
  const supervisor = user.roleKey === ROLE_KEYS.SUPERVISOR;
  const [areas, rooms, departments, people, loans, stock, history, sharedKeys] = await Promise.all([
    prisma.keyArea.findMany({ orderBy: { name: 'asc' }, include: { keys: { orderBy: { code: 'asc' } } } }),
    prisma.room.findMany({ where: { active: true }, orderBy: { number: 'asc' }, select: { id: true, number: true, keys: { where: { status: 'DISPONIBLE' }, select: { id: true, code: true } } } }),
    prisma.department.findMany({ where: { active: true }, orderBy: { order: 'asc' }, select: { id: true, name: true } }),
    prisma.user.findMany({ where: { active: true, deletedAt: null }, orderBy: { name: 'asc' }, select: { id: true, name: true, departmentId: true, scheduleCollaborator:{select:{active:true,memberships:{where:{active:true},select:{departmentId:true}}}}, role: { select: { level: true } } } }),
    listStaffLoans(user),
    supervisor ? listSupervisorKeys(user) : Promise.resolve([]),
    prisma.keyStaffLoan.findMany({orderBy:{createdAt:'desc'},take:20,select:{id:true,humanId:true,departmentName:true,createdAt:true}}),
    prisma.roomKey.findMany({where:{roomId:null,areaId:null,status:'DISPONIBLE',type:{not:'PRINCIPAL'}},orderBy:{code:'asc'},select:{id:true,code:true}}),
  ]);
  const destinations = [...rooms.map(r => ({ id: r.id, name: `Habitación ${r.number}`, kind: 'ROOM' as const })), ...areas.filter(a => a.active).map(a => ({ id: a.id, name: `Área: ${a.name}`, kind: 'AREA' as const }))];
  const keys = [...rooms.flatMap(r => r.keys.map(k => ({ ...k, destination: { id: r.id, name: `Habitación ${r.number}`, kind: 'ROOM' as const } }))), ...areas.filter(a => a.active).flatMap(a => a.keys.filter(k => k.status === 'DISPONIBLE').map(k => ({ id: k.id, code: k.code, destination: { id: a.id, name: `Área: ${a.name}`, kind: 'AREA' as const } })))];
  return <div className="space-y-5"><Link href="/llaves" className="underline">Volver a inventario de llaves</Link><h1 className="text-2xl font-semibold">Áreas y entregas a personal</h1>
    {canAssign && <Card><CardHeader title="Entregar llave a personal" /><div className="p-4"><StaffLoanForm initialRequestKey={randomUUID()} departments={departments} collaborators={people.map(p => ({id:p.id,name:p.name,departmentIds:[...(p.departmentId ? [p.departmentId] : []),...(p.scheduleCollaborator?.active ? p.scheduleCollaborator.memberships.map(m => m.departmentId) : [])]}))} authorizers={people.filter(p => p.role.level >= 60)} keys={keys} sharedKeys={sharedKeys.map(k => ({...k,destination:'Copia libre de recepción'}))} privateKeys={stock.filter(k => !k.retired && k.status === 'DISPONIBLE').map(k => ({ id:k.id,code:k.code,destination:k.destination }))} destinations={destinations} /></div></Card>}
    <Card><CardHeader title="Custodia de personal · entregas abiertas" count={loans.length} /><div className="divide-y">{!loans.length && <p className="p-4 text-sm">Sin entregas pendientes de devolución.</p>}{loans.map(loan => <section key={loan.id} className="space-y-2 p-4"><Link href={`/llaves/personal/${loan.id}`} className="font-semibold underline">Entrega #{loan.humanId} · {loan.departmentName}</Link><p className="text-sm">{loan.collaboratorName ?? 'Personal del área'} · Autorizó: {loan.authorizedByName} · {formatDateTime(loan.createdAt)}</p>{loan.items.filter(i => !i.returnedAt).map(item => <div key={item.id} className="rounded border p-2"><p>{item.destinationName} · {item.keyCode}</p>{canAssign && (!item.supervisorKeyId || stock.some(k => k.id === item.supervisorKeyId)) && <ActionForm action={returnStaffKeyAction}><input type="hidden" name="itemId" value={item.id} /><Input name="notes" required maxLength={180} placeholder="Recepción física y observación" aria-label="Observación de devolución" /><SubmitButton size="sm">Recibir llave</SubmitButton></ActionForm>}</div>)}</section>)}</div></Card>
    <Card><CardHeader title="Historial de entregas · documentos" /><ul className="space-y-2 p-4">{history.map(l => <li key={l.id}><Link className="text-sm underline" href={`/llaves/personal/${l.id}`}>#{l.humanId} · {l.departmentName} · {formatDateTime(l.createdAt)}</Link></li>)}</ul></Card>
    <Card><CardHeader title="Destinos que son áreas" /><div className="space-y-4 p-4"><p className="text-sm text-slate-600">Bodega, oficinas u otros destinos independientes de las 89 habitaciones. El área receptora de una entrega corresponde al departamento del personal.</p>{canStock && <ActionForm action={saveKeyAreaAction}><Field label="Nueva área" name="name"><Input name="name" required maxLength={80} placeholder="Ej.: Bodega de pisos" /></Field><SubmitButton>Crear área</SubmitButton></ActionForm>}{areas.map(area => <section key={area.id} className="space-y-2 rounded border p-3"><h3 className="font-semibold">{area.name}{!area.active && ' · Inactiva'}</h3><ul className="text-sm">{area.keys.map(k => <li key={k.id}>{k.code} · {KEY_STATUS_LABELS[k.status]}</li>)}</ul>{canStock && <><ActionForm action={saveKeyAreaAction}><input type="hidden" name="id" value={area.id} /><Input aria-label="Nombre del área" name="name" required maxLength={80} defaultValue={area.name} /><select className="input-base w-full" aria-label="Estado del área" name="active" defaultValue={String(area.active)}><option value="true">Activa</option><option value="false">Inactiva</option></select><SubmitButton size="sm">Guardar área</SubmitButton></ActionForm>{area.active && <ActionForm action={createAreaKeyAction}><input type="hidden" name="areaId" value={area.id} /><Input name="code" required maxLength={60} placeholder="Código de nueva llave" aria-label="Código de llave del área" /><SubmitButton size="sm">Agregar llave</SubmitButton></ActionForm>}</>}</section>)}</div></Card>
    {supervisor && <Card><CardHeader title="Mi stock privado de llaves" count={stock.filter(k => !k.retired).length} /><div className="space-y-4 p-4"><p className="text-sm">Solo tú puedes ver y modificar esta reserva. Al entregar una llave, su código y destino figuran en la custodia del inventario.</p><ActionForm action={saveSupervisorKeyAction}><div className="grid gap-2 sm:grid-cols-3"><Field label="Código físico" name="code"><Input name="code" required maxLength={60} /></Field><Field label="Destino o uso" name="destination"><Input name="destination" required maxLength={180} /></Field><Field label="Observación" name="notes"><Input name="notes" maxLength={300} /></Field></div><SubmitButton>Agregar a mi stock</SubmitButton></ActionForm>{stock.map(k => <details key={k.id} className="rounded border p-3"><summary className="cursor-pointer">{k.code} · {k.destination} · {k.retired ? 'Baja' : KEY_STATUS_LABELS[k.status]}</summary>{!k.retired && k.status !== 'ENTREGADA_PERSONAL' && <ActionForm action={saveSupervisorKeyAction}><input type="hidden" name="id" value={k.id} /><input type="hidden" name="version" value={k.version} /><Field label="Código" name="code"><Input name="code" required defaultValue={k.code} maxLength={60} /></Field><Field label="Destino" name="destination"><Input name="destination" required defaultValue={k.destination} maxLength={180} /></Field><Field label="Observación" name="notes"><Input name="notes" defaultValue={k.notes ?? ''} maxLength={300} /></Field><Field label="Estado" name="status"><select className="input-base w-full" name="status" defaultValue={k.status}><option value="DISPONIBLE">Disponible</option><option value="EXTRAVIADA">Extraviada</option><option value="FUERA_DE_SERVICIO">Fuera de servicio</option></select></Field><Field label="Retirar del stock" name="retired"><select className="input-base w-full" name="retired"><option value="false">Conservar</option><option value="true">Dar de baja · conservar historial</option></select></Field><SubmitButton size="sm">Actualizar llave</SubmitButton></ActionForm>}<ul className="mt-2 text-xs text-slate-600">{k.movements.map(m => <li key={m.id}>{formatDateTime(m.at)} · {m.action}</li>)}</ul></details>)}</div></Card>}
  </div>;
}
