import {subjectDistributionEnabled} from '@/server/services/subject-distribution-gate';
import Link from 'next/link';
import {requirePageUser} from '@/server/auth/guard';
import {listAreaAttentions,attentionPeople} from '@/server/services/subject-distribution';
import {AreaDecisionForm} from '@/components/operational/area-decision-form';
import {formatDateTime} from '@/lib/format';
import {TASK_STATUS_LABEL,PRIORITY_LABEL} from '@/domain/labels';
import {HK_WORK_LABELS,isHkFocused} from '@/domain/housekeeping-work';
export const dynamic='force-dynamic';
export const metadata={title:'Bandeja de áreas · AROH'};
const labels:Record<string,string>={POR_REVISAR:'Por revisar por jefatura',ACLARACION:'Aclaración pendiente',INFORMADA:'Información publicada al área',ASIGNADA:'Trabajo del área'};
export default async function AreaInbox({searchParams}:{searchParams:Promise<{area?:string;atencion?:string;pagina?:string}>}){
  const enabled=subjectDistributionEnabled();
  const user=await requirePageUser({allowAreaOperation:true});const p=await searchParams;
  const {rows,hasMore,page,areas}=await listAreaAttentions(user,{departmentId:p.area,id:p.atencion,page:Number(p.pagina)});
  const people=new Map(await Promise.all([...new Set(rows.filter(r=>r.canReview).map(r=>r.departmentId))].map(async id=>[id,await attentionPeople(id)] as const)));
  return <div className="mx-auto max-w-5xl space-y-4"><header>{!enabled&&<p className="mb-2 rounded-lg border p-3 text-sm">Consulta de continuidad. La nueva distribución está deshabilitada; los trabajos y resultados existentes conservan acceso.</p>}<h1 className="text-xl font-semibold">Bandeja de áreas</h1><p className="text-sm text-slate-600">Un mismo asunto, conocimiento y decisiones por área. Las urgencias pueden atenderse antes de la revisión de jefatura.</p></header><nav className="flex gap-4 text-sm"><Link className="underline" href="/coordinacion">Trabajo y continuidad</Link><Link className="underline" href="/coordinacion/areas">Todas mis áreas</Link></nav><form className="flex items-end gap-2" action="/coordinacion/areas"><label className="text-sm">Área<select className="input-base" name="area" defaultValue={p.area??''}><option value="">Todas dentro de mi acceso</option>{areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select></label><button className="rounded-lg border px-3 py-2 text-sm" type="submit">Filtrar</button></form>{!rows.length&&<p className="card p-4">No hay distribuciones dentro de tu acceso en esta vista.</p>}{rows.map(row=><article className="card space-y-3 p-4" key={row.id}>
    <div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Asunto #{row.entry.humanId} · {row.entry.title}</h2><span className="text-sm">{row.department.name} · {labels[row.status]}</span></div>
    <p className="whitespace-pre-wrap text-sm">{row.entry.description}</p><p className="text-sm">Importancia: {PRIORITY_LABEL[row.entry.priority]} · Urgencia: {row.urgent?'Atención inmediata':'Revisión normal'}{row.entry.dueAt?` · Plazo original: ${formatDateTime(row.entry.dueAt)}`:' · Sin plazo definido'}</p>
    {row.urgent&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{row.urgencyReason} · {row.decisionAt?'Revisión de jefatura registrada':'Revisión posterior de jefatura pendiente'}. El aviso no acredita contacto efectivo ni trabajo realizado.</p>}
    <p className="text-xs text-slate-600">{row.knownAt?`Conocimiento registrado: ${formatDateTime(row.knownAt)}`:'Sin conocimiento registrado por jefatura'}. Leer no aprueba ni termina.</p>
    {row.decisionNote&&<p className="whitespace-pre-wrap text-sm">Decisión / instrucción: {row.decisionNote}</p>}
    {row.task&&<p className="text-sm"><Link className="underline" href={`/tareas/${row.task.id}`}>Trabajo #{row.task.humanId}</Link> · {TASK_STATUS_LABEL[row.task.status]} · {row.task.assignee?.name??'Por asignar'}{row.task.evidenceProvided&&<span className="block whitespace-pre-wrap">Resultado: {row.task.evidenceProvided}</span>}</p>}
    {row.housekeeping&&<p className="text-sm"><Link className="underline" href={`/housekeeping?area=${row.departmentId}&aviso=${row.housekeeping.humanId}`}>Atención especializada #{row.housekeeping.humanId}</Link> · {HK_WORK_LABELS[row.housekeeping.status]} · {row.housekeeping.assignedTo?.name??'Por asignar'}{row.housekeeping.resolution&&<span className="block whitespace-pre-wrap">Resultado: {row.housekeeping.resolution}</span>}</p>}
    {!isHkFocused(user)&&<Link className="block text-sm underline" href={`/libro/${row.entryId}#distribucion-areas`}>Ver el asunto y el avance de todas las áreas</Link>}
    {enabled&&!['RESUELTO','CERRADO'].includes(row.entry.status)&&<div className="space-y-3">{row.canReview&&!row.knownAt&&<AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="CONOCER"/>}{row.canClaim&&<AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="TOMAR_URGENCIA"/>}{row.canRespond&&row.status==='ACLARACION'&&<AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="RESPONDER"/>}{(row.canRespond||row.canReview)&&row.status!=='POR_REVISAR'&&(row.task?['VALIDADA','COMPLETADA','CANCELADA'].includes(row.task.status):row.housekeeping?['RESUELTO','CANCELADO'].includes(row.housekeeping.status):row.status==='INFORMADA')&&<AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="REABRIR"/>}{row.canReview&&(!row.taskId&&!row.housekeepingId||row.status==='POR_REVISAR'&&(row.task?['VALIDADA','COMPLETADA','CANCELADA'].includes(row.task.status):row.housekeeping?['RESUELTO','CANCELADO'].includes(row.housekeeping.status):false))&&<details><summary className="cursor-pointer font-medium text-sm">Decidir atención del área</summary><div className="mt-3 grid gap-4 sm:grid-cols-3"><AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="INFORMAR"/><AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="ASIGNAR" people={people.get(row.departmentId)??[]}/><AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="ACLARACION"/></div></details>}{row.canReview&&row.urgent&&(row.taskId||row.housekeepingId)&&row.status!=='ASIGNADA'&&<AreaDecisionForm id={row.id} version={row.version} sourceRevision={row.entry.updatedAt.toISOString()} action="REVISAR_URGENCIA"/>}</div>}
  </article>)}<nav className="flex justify-between text-sm" aria-label="Páginas de bandeja de áreas">{page>1?<Link href={`/coordinacion/areas?area=${encodeURIComponent(p.area??'')}&pagina=${page-1}`}>← Anterior</Link>:<span/>}{hasMore&&<Link href={`/coordinacion/areas?area=${encodeURIComponent(p.area??'')}&pagina=${page+1}`}>Siguiente →</Link>}</nav></div>;
}
