import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { requirePageUser } from '@/server/auth/guard';
import { getCoordinationBoard, getCoordinationTeam, coordinationMetrics } from '@/server/services/coordination';
import { CoordinationForm } from '@/components/operational/coordination-form';
import { formatDateTime } from '@/lib/format';
import { RECEIPT_MINUTES, receiptDueAt } from '@/domain/coordination';
import { ENTRY_STATUS_LABEL, TASK_STATUS_LABEL, FOLLOWUP_STATUS_LABEL } from '@/domain/labels';
import { HK_WORK_LABELS } from '@/domain/housekeeping-work';
export const dynamic='force-dynamic';
export const metadata={title:'Coordinación · Pendientes y continuidad'};
export default async function CoordinationPage({searchParams}:{searchParams:Promise<{area?:string;mios?:string;pagina?:string;historial?:string}>}){
  const user=await requirePageUser({allowAreaOperation:true});const p=await searchParams;
  const board=await getCoordinationBoard(user,{departmentId:p.area,mine:p.mios==='1',page:Number(p.pagina)||1,history:p.historial==='1'});
  const team=p.area?await getCoordinationTeam(user,p.area):[];const metrics=coordinationMetrics(board.rows);
  const href=(page:number)=>`/coordinacion?${new URLSearchParams({...p,pagina:String(page)} as Record<string,string>)}`;
  const labels:Record<string,string>={...ENTRY_STATUS_LABEL,...TASK_STATUS_LABEL,...HK_WORK_LABELS,...FOLLOWUP_STATUS_LABEL};
  return <div className="mx-auto max-w-6xl space-y-4 surface-enter">
    <header><h1 className="text-xl font-semibold text-petrol-900">Coordinación y continuidad</h1><p className="mt-1 text-sm text-slate-600">Qué sigue, quién lo recibe y dónde registrar el resultado. Los pendientes permanecen aquí entre turnos.</p></header>
    <div className="flex flex-wrap gap-3 text-sm">{user.permissions.includes('entry.create')&&<Link className="underline" href="/libro">Registrar novedad o incidencia</Link>}{user.permissions.some(v=>v.startsWith('housekeeping.'))&&<Link className="underline" href="/admin/housekeeping">Trabajo de Housekeeping</Link>}{user.permissions.some(v=>v==='shift.start'||v==='shift.manage')&&<Link className="underline" href="/turno">Entrega y recepción de turno</Link>}{user.permissions.includes('cash.view')&&<Link className="underline" href="/caja">Caja y arqueos</Link>}{user.permissions.includes('key.assign')&&<Link className="underline" href="/llaves">Llaves y custodia</Link>}</div>
    <form className="card flex flex-wrap items-end gap-3 p-3" action="/coordinacion"><label className="text-sm">Área<select className="input-base mt-1" name="area" defaultValue={p.area??''}><option value="">Todas las áreas accesibles</option>{board.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm">Vista<select className="input-base mt-1" name="historial" defaultValue={p.historial??''}><option value="">Pendientes</option><option value="1">Resultados</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="mios" value="1" defaultChecked={p.mios==='1'}/>Mis responsabilidades</label><button className="btn-secondary" type="submit">Ver</button></form>
    <nav className="flex flex-wrap gap-4 text-sm"><Link className="underline" href="/fronti/procedimientos">Mis procedimientos de Fronti</Link>{user.permissions.includes('system.configure')&&<Link className="underline" href="/coordinacion/automatizaciones">Reglas y procedimientos</Link>}</nav>
    <section className="card space-y-2 p-4"><h2 className="font-semibold">{board.total} asuntos {p.historial==='1'?'en resultados':'pendientes'} dentro de tu acceso</h2><p className="text-sm">En esta página: {metrics.unassigned} sin responsable · {metrics.unreceived} sin recepción registrada · {metrics.overdue} con plazo vencido · {metrics.blocked} con impedimento.</p><p className="text-xs text-slate-600">Confirmación: {metrics.confirmation.minutes??'—'} min ({metrics.confirmation.samples} muestras) · Inicio tras recepción: {metrics.attention.minutes??'—'} min ({metrics.attention.samples} muestras) · Resolución desde inicio: {metrics.resolution.minutes??'—'} min ({metrics.resolution.samples} muestras). Promedios de los registros visibles; sin tiempos inventados para el historial.</p><p className="text-xs text-slate-600">Las nuevas asignaciones requieren recepción en {RECEIPT_MINUTES} minutos desde su inicio disponible. La recepción no confirma asistencia ni resuelve el trabajo.</p></section>
    {board.byArea.length>0&&<section className="card p-4"><h2 className="font-semibold">Carga por área dentro de tu acceso</h2><ul className="mt-2 grid gap-2 text-sm sm:grid-cols-2">{board.byArea.map(a=><li key={a.departmentId}><Link className="underline" href={`/coordinacion?area=${a.departmentId}${p.historial==='1'?'&historial=1':''}${p.mios==='1'?'&mios=1':''}`}>{a.name}</Link> · {a.total} asuntos · {a.blocked} con impedimento</li>)}</ul><p className="mt-2 text-xs text-slate-600">Incluye todas las páginas del filtro. Las tareas vinculadas se agrupan bajo su asunto.</p></section>}
    {team.length>0&&<details className="card p-3"><summary className="cursor-pointer text-sm font-semibold">Equipo del área y horario actual</summary><p className="my-2 text-xs text-slate-600">El horario publicado orienta la asignación. La disponibilidad real se confirma con la persona.</p><ul className="grid gap-1 text-sm sm:grid-cols-2">{team.map(u=><li key={u.id}>{u.name} · {u.scheduled?'Horario vigente':u.scheduleVisible?'Sin horario vigente':'Horario fuera de tu acceso'}</li>)}</ul></details>}
    {board.rows.length===0&&<p className="card p-6 text-sm">No hay asuntos para estos filtros.</p>}
    {board.rows.map(r=><article key={`${r.kind}:${r.id}`} className="card space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold text-petrol-900"><Link href={r.href}>#{r.humanId} · {r.title}</Link></h2><span className="text-xs">{labels[r.status]??r.status}</span></div><p className="text-sm">{r.department} · Responsable: <strong>{r.owner}</strong></p><p className="text-sm"><strong>Siguiente acción:</strong> {r.nextAction}</p><p className="text-xs text-slate-600">{r.kind==='followup'?'Continuidad de Supervisión; recepción en el trabajo vinculado':r.receivedAt?`Recibido: ${formatDateTime(r.receivedAt)}`:'Recepción pendiente o sin registro histórico'}{r.dueAt?` · Plazo: ${formatDateTime(r.dueAt)}`:''}{!r.receivedAt&&receiptDueAt(r.assignedAt,r.availableAt)?` · Confirmar antes de ${formatDateTime(receiptDueAt(r.assignedAt,r.availableAt))}`:''}</p>
      {r.children.length>0&&<details><summary className="cursor-pointer text-sm">Trabajo vinculado al mismo asunto</summary><ul className="mt-2 space-y-1 text-sm">{r.children.map(c=><li key={c.href}><Link className="underline" href={c.href}>{c.label}</Link></li>)}</ul></details>}
      <Link className="inline-block text-sm font-medium underline" href={r.href}>Abrir trabajo, atender y registrar resultado →</Link>
      {p.historial!=='1'&&(r.kind==='entry'||r.kind==='task')&&(r.ownerId===user.id||r.canAssign)&&<details><summary className="cursor-pointer text-sm font-medium">Recepción, siguiente acción y relevo</summary><div className="mt-3 grid gap-4 sm:grid-cols-2">{r.ownerId===user.id&&<CoordinationForm id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action={r.receivedAt?'SIGUIENTE':'RECIBIR'} ownerId={r.ownerId} nextAction={r.nextAction} team={[]}/>}{r.canAssign&&(p.area===r.departmentId&&team.length>0?<CoordinationForm id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action="ASIGNAR" ownerId={r.ownerId} nextAction={r.nextAction} team={team}/>:<p className="text-sm">Selecciona el área en el filtro para asignar a su equipo. Si falta el área, complétala en el registro.</p>)}</div></details>}
    </article>)}
    <nav className="flex justify-between text-sm" aria-label="Páginas de coordinación">{board.page>1?<Link href={href(board.page-1)}>← Anterior</Link>:<span/>}{board.hasMore&&<Link href={href(board.page+1)}>Siguiente →</Link>}</nav>
  </div>;
}
