import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import {prisma} from '@/lib/prisma';
import {ListFilterBar} from '@/components/ui/list-controls';
import { requirePageUser } from '@/server/auth/guard';
import { getCoordinationBoard, getCoordinationTeam, coordinationMetrics, type CoordinationView, type CoordinationState } from '@/server/services/coordination';
import { CoordinationForm } from '@/components/operational/coordination-form';
import { formatDateTime } from '@/lib/format';
import { RECEIPT_MINUTES, receiptDueAt } from '@/domain/coordination';
import { ENTRY_STATUS_LABEL, TASK_STATUS_LABEL, FOLLOWUP_STATUS_LABEL } from '@/domain/labels';
import { HK_WORK_LABELS } from '@/domain/housekeeping-work';
import { DisclosureCard } from '@/components/ui/card';
export const dynamic='force-dynamic';
export const metadata={title:'Coordinación · Pendientes y continuidad'};
export default async function CoordinationPage({searchParams}:{searchParams:Promise<{area?:string;mios?:string;pagina?:string;historial?:string;vista?:string;q?:string;estado?:string;responsable?:string;fecha?:string}>}){
  const user=await requirePageUser({allowAreaOperation:true});const p=await searchParams;
  const area=user.departmentId?await prisma.department.findUnique({where:{id:user.departmentId},select:{key:true}}):null;
  const maintenance=area?.key==='MANTENIMIENTO';
  const departmentId=p.area??(maintenance?user.departmentId??undefined:undefined);
  const allowedViews:CoordinationView[]=['all','reception','unassigned','unreceived','blocked','clarification','carryover'];
  const view=allowedViews.includes(p.vista as CoordinationView)?p.vista as CoordinationView:maintenance?'unreceived':'all';
  const state=['abierto','atencion','bloqueado','revision','resuelto'].includes(p.estado??'')?p.estado as CoordinationState:undefined;
  const history=state?state==='resuelto':p.historial==='1';
  const board=await getCoordinationBoard(user,{departmentId,mine:p.mios==='1',page:Number(p.pagina)||1,history,view,q:p.q,ownerId:p.responsable,state,date:p.fecha});
  const areaIds=[...new Set([...board.rows.map(r=>r.departmentId),departmentId].filter((id):id is string=>!!id))];
  const teams=await Promise.all(areaIds.map(async id=>[id,await getCoordinationTeam(user,id)] as const));
  const teamByArea=new Map(teams);const team=departmentId?teamByArea.get(departmentId)??[]:[];const people=[...new Map(teams.flatMap(([,team])=>team).map(person=>[person.id,person])).values()];
  const metrics=coordinationMetrics(board.rows);
  const query=(changes:Record<string,string>)=>new URLSearchParams({...Object.fromEntries(Object.entries(p).filter(([,v])=>typeof v==='string')),area:departmentId??'',vista:view,...changes}).toString();
  const href=(page:number)=>`/coordinacion?${query({pagina:String(page)})}`;
  const shortcuts=maintenance?[['Por recibir',{vista:'unreceived',mios:'',historial:'',estado:''}],['Mi trabajo',{vista:'all',mios:'1',historial:'',estado:''}],['Impedimentos',{vista:'blocked',mios:'',historial:'',estado:''}],['Aclaraciones',{vista:'clarification',mios:'',historial:'',estado:''}],['Resultados por devolver',{vista:'all',mios:'1',historial:'1',estado:''}]] as const:[['Coordinar pendientes',{vista:'all',mios:'',historial:'',estado:''}],['Mis responsabilidades',{vista:'all',mios:'1',historial:'',estado:''}],['Resultados recibidos',{vista:'all',mios:'',historial:'1',estado:''}],['Sin responsable',{vista:'unassigned',mios:'',historial:'',estado:''}],['Continuidad',{vista:'carryover',mios:'',historial:'',estado:''}]] as const;
  const labels:Record<string,string>={...ENTRY_STATUS_LABEL,...TASK_STATUS_LABEL,...HK_WORK_LABELS,...FOLLOWUP_STATUS_LABEL};
  return <div className="mx-auto max-w-6xl space-y-4 surface-enter">
    <Link className="underline text-sm" href="/coordinacion/indicadores">Resumen e indicadores por período</Link>
    <header><h1 className="text-xl font-semibold text-petrol-900">{maintenance?'Mi trabajo · Mantenimiento':'Coordinación y continuidad'}</h1><p className="mt-1 text-sm text-slate-600">Qué sigue, quién lo recibe y dónde registrar el resultado. Los pendientes permanecen aquí entre turnos.</p></header>
    <div className="flex flex-wrap gap-3 text-sm">{user.permissions.includes('entry.create')&&<Link className="underline" href="/libro">Registrar novedad o incidencia</Link>}{user.permissions.some(v=>v.startsWith('housekeeping.'))&&<Link className="underline" href="/admin/housekeeping">Trabajo de Housekeeping</Link>}{user.permissions.some(v=>v==='shift.start'||v==='shift.manage')&&<Link className="underline" href="/turno">Entrega y recepción de turno</Link>}{user.permissions.includes('cash.view')&&<Link className="underline" href="/caja">Caja y arqueos</Link>}{user.permissions.includes('key.assign')&&<Link className="underline" href="/llaves">Llaves</Link>}{user.permissions.some(v=>v==='custody.view'||v==='custody.manage')&&<Link className="underline" href="/custodia">Objetos olvidados y custodia</Link>}</div>
    <ListFilterBar clearHref="/coordinacion?area=&vista=all" searchValue={p.q} searchPlaceholder="Buscar folio, asunto o habitación…">
      <input type="hidden" name="vista" value={view}/>
      <label className="min-w-0 text-sm">Área<select className="input-base mt-1" name="area" defaultValue={departmentId??''}><option value="">Todas las áreas accesibles</option>{board.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
      <label className="min-w-0 text-sm">Estado<select className="input-base mt-1" name="estado" defaultValue={state??''}><option value="">{history?'Resultados':'Pendientes'}</option><option value="abierto">Abierto / por recibir</option><option value="atencion">En atención</option><option value="bloqueado">Con impedimento</option><option value="revision">Por revisar</option><option value="resuelto">Resuelto</option></select></label>
      <details className="w-full border-t border-slate-100 pt-2"><summary className="cursor-pointer text-sm font-medium">Más filtros</summary><div className="mt-3 flex flex-wrap items-end gap-3">
        <label className="text-sm">Responsable<select className="input-base mt-1" name="responsable" defaultValue={p.responsable??(p.mios==='1'?user.id:'')}><option value="">Todos dentro de mi acceso</option><option value={user.id}>Mis responsabilidades</option>{people.filter(u=>u.id!==user.id).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
        <label className="text-sm">Fecha de plazo<input className="input-base mt-1" name="fecha" type="date" defaultValue={p.fecha}/></label>
        <label className="text-sm">Vista<select className="input-base mt-1" name="historial" defaultValue={history?'1':''}><option value="">Pendientes</option><option value="1">Resultados</option></select></label>
      </div></details>
    </ListFilterBar>
    <nav aria-label="Vistas de coordinación" className="flex flex-wrap gap-2 text-sm">{shortcuts.map(([label,changes])=><Link key={label} href={'/coordinacion?'+query({...changes,pagina:'1',responsable:''})} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-petrol-800">{label}</Link>)}<details className="rounded-lg border border-slate-200 px-3 py-2"><summary className="cursor-pointer">Más vistas</summary><div className="mt-3 flex flex-wrap gap-3">{([['reception','Solicitudes de Recepción'],['unassigned','Sin responsable'],['unreceived','Sin confirmar'],['blocked','Impedimentos'],['clarification','Aclaraciones'],['carryover','Turnos anteriores']] as Array<[CoordinationView,string]>).map(([key,label])=><Link key={key} className="underline" href={'/coordinacion?'+query({vista:key,pagina:'1',historial:'',estado:''})}>{label}</Link>)}</div></details></nav>
    <nav className="flex flex-wrap gap-4 text-sm"><Link className="underline" href="/fronti/procedimientos">Mis procedimientos de Fronti</Link>{user.permissions.includes('system.configure')&&<Link className="underline" href="/coordinacion/automatizaciones">Reglas y procedimientos</Link>}</nav>
    <DisclosureCard title={`${board.total} asuntos ${history?'en resultados':'pendientes'} dentro de tu acceso`} description="Resumen del filtro actual y tiempos observados." defaultOpen contentClassName="space-y-2 p-4"><p className="text-sm">En esta página: {metrics.unassigned} sin responsable · {metrics.unreceived} sin recepción registrada · {metrics.overdue} con plazo vencido · {metrics.blocked} con impedimento.</p><p className="text-xs text-slate-600">Confirmación: {metrics.confirmation.minutes??'—'} min ({metrics.confirmation.samples} muestras) · Inicio tras recepción: {metrics.attention.minutes??'—'} min ({metrics.attention.samples} muestras) · Resolución desde inicio: {metrics.resolution.minutes??'—'} min ({metrics.resolution.samples} muestras). Promedios de los registros visibles; sin tiempos inventados para el historial.</p><p className="text-xs text-slate-600">Las nuevas asignaciones requieren recepción en {RECEIPT_MINUTES} minutos desde su inicio disponible. La recepción no confirma asistencia ni resuelve el trabajo.</p></DisclosureCard>
    {board.byArea.length>0&&<DisclosureCard title="Carga por área dentro de tu acceso" description="Distribución de pendientes e impedimentos por área."><ul className="mt-2 grid gap-2 text-sm sm:grid-cols-2">{board.byArea.map(a=><li key={a.departmentId}><Link className="underline" href={`/coordinacion?area=${a.departmentId}${history?'&historial=1':''}${p.mios==='1'?'&mios=1':''}`}>{a.name}</Link> · {a.total} asuntos · {a.blocked} con impedimento</li>)}</ul><p className="mt-2 text-xs text-slate-600">Incluye todas las páginas del filtro. Las tareas vinculadas se agrupan bajo su asunto.</p></DisclosureCard>}
    {team.length>0&&<details className="card p-3"><summary className="cursor-pointer text-sm font-semibold">Equipo del área y horario actual</summary><p className="my-2 text-xs text-slate-600">El horario publicado orienta la asignación. La disponibilidad real se confirma con la persona.</p><ul className="grid gap-1 text-sm sm:grid-cols-2">{team.map(u=><li key={u.id}>{u.name} · {u.scheduled?'Horario vigente':u.scheduleVisible?'Sin horario vigente':'Horario fuera de tu acceso'}</li>)}</ul></details>}
    {board.rows.length===0&&<p className="card p-6 text-sm">No hay asuntos para estos filtros.</p>}
    {board.rows.map(r=><article key={`${r.kind}:${r.id}`} className="card space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold text-petrol-900"><Link href={r.href}>{r.source?`Asunto #${r.source.humanId} · `:`#${r.humanId} · `}{r.title}</Link></h2><span className="text-xs">{labels[r.status]??r.status}</span></div><p className="text-sm">{r.department} · Responsable: <strong>{r.owner}</strong></p><p className="text-sm"><strong>Siguiente acción:</strong> {r.nextAction}</p><p className="text-xs text-slate-600">{r.kind==='followup'?'Continuidad de Supervisión; recepción en el trabajo vinculado':r.receivedAt?`Recibido: ${formatDateTime(r.receivedAt)}`:'Recepción pendiente o sin registro histórico'}{r.dueAt?` · Plazo: ${formatDateTime(r.dueAt)}`:''}{!r.receivedAt&&receiptDueAt(r.assignedAt,r.availableAt)?` · Confirmar antes de ${formatDateTime(receiptDueAt(r.assignedAt,r.availableAt))}`:''}</p>
      {r.children.length>0&&<details><summary className="cursor-pointer text-sm">Trabajo vinculado al mismo asunto</summary><ul className="mt-2 space-y-1 text-sm">{r.children.map(c=><li key={c.href}><Link className="underline" href={c.href}>{c.label}</Link></li>)}</ul></details>}
      <Link className="inline-block text-sm font-medium underline" href={r.href}>Abrir trabajo, atender y registrar resultado →</Link>
      {!history&&(r.kind==='entry'||r.kind==='task')&&r.nextAction.startsWith('Aclaración requerida:')&&(r.createdById===user.id||r.canAssign)&&<details open={view==='clarification'}><summary className="cursor-pointer text-sm font-medium">Responder aclaración</summary><div className="mt-3 max-w-xl"><p className="mb-2 text-sm text-amber-900">{r.nextAction}</p><CoordinationForm returnTo={href(Number(p.pagina)||1)} id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action="RESPONDER_ACLARACION" ownerId={r.ownerId} nextAction="" team={[]}/></div></details>}
      {!history&&(r.kind==='entry'||r.kind==='task')&&(r.ownerId===user.id||r.canAssign)&&<details><summary className="cursor-pointer text-sm font-medium">Recepción, siguiente acción y relevo</summary><div className="mt-3 grid gap-4 sm:grid-cols-2">{r.ownerId===user.id&&<div className="space-y-3"><CoordinationForm returnTo={href(Number(p.pagina)||1)} id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action={r.receivedAt?'SIGUIENTE':'RECIBIR'} ownerId={r.ownerId} nextAction={r.nextAction} team={[]}/>{r.receivedAt&&<details><summary className="cursor-pointer text-sm">Necesito una aclaración</summary><div className="mt-2"><CoordinationForm returnTo={href(Number(p.pagina)||1)} id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action="ACLARACION" ownerId={r.ownerId} nextAction="" team={[]}/></div></details>}</div>}{r.canAssign&&(r.departmentId&&(teamByArea.get(r.departmentId)?.length??0)>0?<CoordinationForm returnTo={href(Number(p.pagina)||1)} id={r.id} kind={r.kind} updatedAt={r.updatedAt.toISOString()} requestKey={randomUUID()} action="ASIGNAR" ownerId={r.ownerId} nextAction={r.nextAction} team={teamByArea.get(r.departmentId!)??[]}/>:<p className="text-sm">No hay equipo asignable en el área de este asunto. Revisa el área o las cuentas habilitadas.</p>)}</div></details>}
    </article>)}
    <nav className="flex justify-between text-sm" aria-label="Páginas de coordinación">{board.page>1?<Link href={href(board.page-1)}>← Anterior</Link>:<span/>}{board.hasMore&&<Link href={href(board.page+1)}>Siguiente →</Link>}</nav>
  </div>;
}
