import Link from 'next/link';
import { DisclosureCard } from '@/components/ui/card';
import { requirePageUser } from '@/server/auth/guard';
import { operationalIndicators } from '@/server/services/operational-indicators';
import { formatDateTime } from '@/lib/format';
import { hotelDateKey, parseHotelDateInput } from '@/domain/time';
export const dynamic='force-dynamic';
export default async function IndicatorsPage({searchParams}:{searchParams:Promise<{desde?:string;hasta?:string;area?:string}>}){
  const user=await requirePageUser({allowAreaOperation:true});const p=await searchParams;
  const now=new Date();const from=p.desde?parseHotelDateInput(p.desde+'T00:00'):new Date(now.getTime()-86400000);const to=p.hasta?parseHotelDateInput(p.hasta+'T23:59:59.999'):now;
  if(!from||!to||to<from||to.getTime()-from.getTime()>31*86400000)return <p>Selecciona un período válido de hasta 31 días. <Link href="/coordinacion/indicadores">Restablecer</Link></p>;
  const data=await operationalIndicators(user,{from,to,departmentId:p.area});
  const ratio=(n:number,d:number)=>d?`${n}/${d} (${Math.round(n/d*100)} %)`: 'Sin muestras (denominador 0)';
  return <div className="mx-auto max-w-6xl space-y-4"><header><h1 className="text-xl font-semibold">Resumen e indicadores operativos</h1><p>{formatDateTime(from)} a {formatDateTime(to)} · America/Santiago · {data.complete?'Lectura completa dentro del alcance':'Lectura parcial: se alcanzó el límite de 10 páginas por estado'}.</p><p className="text-sm">Alcance: {data.scope}. Las consultas respetan el acceso actual de tu usuario.</p></header><Link className="underline" href="/coordinacion">Volver a Coordinación</Link><form className="flex flex-wrap gap-3"><label>Desde<input className="input-base" type="date" name="desde" defaultValue={hotelDateKey(from)}/></label><label>Hasta<input className="input-base" type="date" name="hasta" defaultValue={hotelDateKey(to)}/></label>{p.area&&<input type="hidden" name="area" value={p.area}/>}<button className="rounded border px-3" type="submit">Consultar período</button></form>
  <DisclosureCard title="Pendientes actuales" defaultOpen contentClassName="space-y-2 p-4"><p>{data.pending.pending} registros observados · {data.pending.unassigned} sin responsable · {data.pending.unreceived} asignados sin recibir · {data.pending.overdue} vencidos · {data.pending.blocked} bloqueados.</p><p className="text-xs">Denominador: {data.pending.denominator}. {data.pending.complete?'Todas las páginas.':'Muestra parcial.'} Los resultados del período se presentan aparte.</p><ul className="mt-3 space-y-2">{data.pending.sources.map(row=><li key={row.kind+row.id}><Link className="underline" href={row.href}>{row.title}</Link> · {row.owner} · {row.nextAction}{row.dueAt?' · Plazo '+formatDateTime(row.dueAt):''}</li>)}</ul><p className="text-xs">Se muestran {data.pending.sources.length} fuentes de {data.pending.denominator} registros observados.</p></DisclosureCard>
  <DisclosureCard title="Carga por área" contentClassName="space-y-2 p-4"><ul>{data.byArea.map(area=><li key={area.departmentId}><Link className="underline" href={`?${new URLSearchParams({area:area.departmentId,desde:hotelDateKey(from),hasta:hotelDateKey(to)})}`}>{area.name}</Link>: {area.total} asuntos, {area.blocked} bloqueados.</li>)}</ul><p className="text-xs">{data.byAreaComplete?'Conteo completo del tablero actual dentro de tu acceso.':'Conteo parcial: se alcanzó el límite de identidades del tablero; las cifras son mínimos observados.'} Agrupa trabajo vinculado al mismo asunto.</p></DisclosureCard>
  <DisclosureCard title="Tiempos observados" contentClassName="space-y-2 p-4"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Tramo</th><th>Media, min</th><th>P95, min</th><th>Muestras / eventos finales</th><th>Sin tiempo inicial</th></tr></thead><tbody>{Object.entries(data.durations).map(([key,m])=><tr key={key}><td>{({receipt:'Asignación a recepción',attention:'Recepción a inicio',resolution:'Inicio a resolución'})[key as keyof typeof data.durations]}</td><td>{m.minutes?.toFixed(1)??'Sin datos'}</td><td>{m.p95Minutes?.toFixed(1)??'Sin datos'}</td><td>{m.samples}/{m.denominator}</td><td>{m.missing}</td></tr>)}</tbody></table></div><p className="text-xs">El evento final debe estar dentro del período. No se sustituyen fechas faltantes por cero.</p></DisclosureCard>
  <DisclosureCard title="Continuidad de turno" contentClassName="space-y-2 p-4"><p>{data.shift.current?`Turno #${data.shift.current.humanId}, apertura ${formatDateTime(data.shift.current.actualStart!)}`:'Sin apertura real propia registrada.'}{data.shift.previous?` · Anterior #${data.shift.previous.humanId}`:''}</p><p className="text-xs">{data.shift.note}</p><ul>{data.shift.changes?.slice(0,30).map(row=><li key={row.kind+row.id}><Link className="underline" href={row.href}>{row.title}</Link>: {row.created?'creado; ':''}{row.received?'recepción registrada; ':''}{row.completed?'resultado registrado; ':''}actualizado {formatDateTime(row.updatedAt)} · {row.owner} · {row.nextAction}</li>)}</ul><p className="text-xs">{data.shift.changes===null?'Sin comparación de turno disponible.':`Se muestran hasta 30 de ${data.shift.changes.length} cambios observados desde la apertura. No se reconstruyen estados anteriores sin eventos.`}</p></DisclosureCard>
  <DisclosureCard title="Reincidencias y cumplimiento" contentClassName="space-y-2 p-4"><p>{data.recurrence.reopened} reaperturas · {data.recurrence.blockEvents} eventos de bloqueo · {data.recurrence.denominator} eventos examinados. {data.recurrence.complete?'Consulta de eventos completa.':'Consulta de eventos parcial.'}</p><p className="text-xs">{data.recurrence.definition}</p><p>Procedimientos cumplidos: {ratio(data.procedures.compliant,data.procedures.denominator)}. {data.procedures.complete?'Todas las ocurrencias del alcance.':'Primeras 1000 ocurrencias.'}</p><p className="text-xs">{data.procedures.definition}</p></DisclosureCard>
  <DisclosureCard title="Automatizaciones y Fronti" contentClassName="space-y-2 p-4"><p>{data.automation.scope} · {data.automation.denominator} ejecuciones del período.</p><ul>{data.automation.statuses.map(row=><li key={row.status}>{row.status}: {row.count}</li>)}</ul><p>{data.fronti.scope}: {data.fronti.successful} completadas / {data.fronti.denominator} resultados; {data.fronti.failed} requieren intervención y {data.fronti.changed} detenidas por cambio. {data.fronti.complete?'Consulta completa.':'Muestra de 1000 resultados.'}</p><p>P95 de ejecución registrada: {data.fronti.p95Ms===null?'sin datos':data.fronti.p95Ms+' ms'} ({data.fronti.durationSamples} muestras). Este tiempo no mide la espera del usuario hasta ver el resultado.</p><p>Envíos manuales de formulario evitados, estimados: {data.fronti.estimatedManualSubmissionsAvoided}.</p><p className="text-xs">{data.fronti.estimate} No hay línea base humana de la etapa 1 ni ahorro de tiempo medido. Las pruebas de navegador registran tiempos observados por separado.</p><Link href="/fronti/procedimientos" className="underline">Consultar acciones y resultados propios</Link></DisclosureCard><p className="text-xs text-slate-600">{data.note}</p></div>;
}
