import {randomUUID} from 'node:crypto';
import {requirePageUser} from '@/server/auth/guard';
import {listLostFound,lostFoundTeam} from '@/server/services/lost-found';
import {NewLostFoundForm,LostFoundAction} from '@/components/operational/lost-found-forms';
import {formatDateTime} from '@/lib/format';
export const dynamic='force-dynamic';
export const metadata={title:'Objetos olvidados y custodia'};
const labels:Record<string,string>={EN_CUSTODIA:'En custodia',ENTREGADO:'Entregado',DISPUESTO:'Disposición final'};
export default async function CustodiaPage({searchParams}:{searchParams:Promise<{estado?:string;q?:string}>}){
 const user=await requirePageUser({allowAreaOperation:true});const p=await searchParams;
 const canManage=user.roleKey==='ADMINISTRADOR_SISTEMA'||user.permissions.includes('custody.manage');
 const [items,team]=await Promise.all([listLostFound(user,{status:p.estado,q:p.q}),canManage?lostFoundTeam(user):Promise.resolve([])]);
 return <div className="mx-auto max-w-6xl space-y-4 surface-enter">
  <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold text-petrol-900">Objetos olvidados y custodia</h1><p className="mt-1 text-sm text-slate-600">Hallazgo, ubicación física, responsable e historial hasta su entrega o disposición final.</p></div>{canManage&&<NewLostFoundForm requestKey={randomUUID()} team={team}/>}</header>
  <form action="/custodia" className="card flex flex-wrap items-end gap-3 p-3"><label className="text-sm">Estado<select className="input-base mt-1" name="estado" defaultValue={p.estado??''}><option value="">Todos</option><option value="EN_CUSTODIA">En custodia</option><option value="ENTREGADO">Entregados</option><option value="DISPUESTO">Disposición final</option></select></label><label className="min-w-0 flex-1 text-sm">Buscar<input className="input-base mt-1 w-full" name="q" defaultValue={p.q??''} placeholder="Objeto, lugar o ubicación de custodia"/></label><button className="btn-secondary" type="submit">Ver</button></form>
  <section className="card p-4"><p className="text-sm"><strong>{items.filter(i=>i.status==='EN_CUSTODIA').length}</strong> en custodia · {items.length} registros visibles con estos filtros.</p><p className="mt-1 text-xs text-slate-600">Este registro no administra reservas, estadías ni disponibilidad de habitaciones.</p></section>
  {items.length===0&&<p className="card p-6 text-sm">No hay objetos con estos filtros.</p>}
  {items.map(i=><article key={i.id} className="card space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs text-slate-500">#{i.humanId} · {formatDateTime(i.foundAt)}</p><h2 className="font-semibold text-petrol-900">{i.item}</h2></div><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold">{labels[i.status]??i.status}</span></div><div className="grid gap-1 text-sm sm:grid-cols-2"><p><strong>Hallazgo:</strong> {i.foundLocation}</p><p><strong>Custodia:</strong> {i.custodyLocation}</p><p><strong>Registró:</strong> {i.registeredBy.name}</p><p><strong>Responsable:</strong> {i.custodian?.name??'Sin responsable individual'}</p></div>{i.finalAction&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900"><strong>Resultado:</strong> {i.finalAction}{i.evidenceNote?' · Evidencia: '+i.evidenceNote:''}{i.closedBy?' · Responsable: '+i.closedBy.name:''}</p>}{canManage&&<div className="flex flex-wrap gap-2">{i.status==='EN_CUSTODIA'?<><LostFoundAction id={i.id} version={i.version} action="MOVER" team={team} currentLocation={i.custodyLocation} currentCustodian={i.custodianId}/><LostFoundAction id={i.id} version={i.version} action="ENTREGAR" team={team} currentLocation={i.custodyLocation}/><LostFoundAction id={i.id} version={i.version} action="DISPONER" team={team} currentLocation={i.custodyLocation}/></>:<LostFoundAction id={i.id} version={i.version} action="REABRIR" team={team} currentLocation={i.custodyLocation} currentCustodian={i.custodianId}/>}</div>}<details><summary className="cursor-pointer text-xs text-slate-600">Historial</summary><ol className="mt-2 space-y-1 text-xs text-slate-600">{i.events.map(e=><li key={e.id}>{formatDateTime(e.createdAt)} · {e.action}{e.note?' · '+e.note:''}</li>)}</ol></details></article>)}
 </div>
}
