import {acknowledgeAlert} from '@/server/services/alerts';
import {executeFrontiPageContextTool} from '@/server/ai/fronti-v2/page-context-tool';
import {resolveFrontiPageContext} from '@/server/ai/fronti-v2/page-context';
import {getRoomMonitorDetail,getRoomMonitorOverview} from '@/server/services/room-monitor';
import {searchOperationalRecords} from '@/server/services/global-search';
import {getSupervisionData} from '@/server/services/supervision';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {prisma,seedCatalog,resetOperationalData,createUser,ROLE_KEYS} from './helpers';
import {getFormOptions} from '@/server/services/options';
import {getHistory} from '@/server/services/history';
import {getBookItems} from '@/server/services/book';
import {taskFollowUpReadWhere,followUpReadWhere} from '@/server/services/followup-access';
import {createEntry,getSubjectEntry,changeEntryStatus} from '@/server/services/entries';
import {createTask,changeTaskStatus,getTask,assignTask,toggleChecklistItem,softDeleteTask,restoreTask} from '@/server/services/tasks';
import {changeTaskStatusAction} from '@/server/actions/tasks';
const auth=vi.hoisted(()=>({current:vi.fn()}));
vi.mock('@/server/auth/current-user',async original=>({...await original<object>(),getCurrentUserFresh:auth.current}));
vi.mock('@/server/services/legal-acceptance',()=>({hasAcceptedCurrentTerms:async()=>true}));
vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));

describe('AROH Simple · reserva y revisión independiente',()=>{
  beforeAll(seedCatalog);beforeEach(resetOperationalData);
  it('filtra Housekeeping histórico reservado antes del contexto sin ocultar la novedad',async()=>{
    const admin=await createUser({roleKey:ROLE_KEYS.SYSTEM_ADMIN});
    const reader=await createUser({roleKey:ROLE_KEYS.SUPERVISOR});
    const source=await createEntry(admin,{type:'NOVEDAD',title:'Origen público',description:'Contexto',priority:'MEDIA',requiresFollowUp:false,tags:[]});
    await prisma.housekeepingRequest.create({data:{requestKey:randomUUID(),sourceEntryId:source.id,isDemo:true,resolution:'Resultado reservado',createdById:admin.id}});
    expect((await getSubjectEntry(reader,source.id)).title).toBe('Origen público');
    expect((await getSubjectEntry(reader,source.id)).housekeepingRequest).toBeNull();
    expect((await getSubjectEntry(admin,source.id)).housekeepingRequest?.resolution).toBe('Resultado reservado');
  });
  it('no proyecta seguimiento privado de otra persona ni la tarea que lo ejecuta',async()=>{
    const reader=await createUser({roleKey:ROLE_KEYS.SYSTEM_ADMIN});
    const owner=await createUser({roleKey:ROLE_KEYS.SUPERVISOR});
    const source=await createEntry(reader,{type:'NOVEDAD',title:'Origen común',description:'Contexto',priority:'MEDIA',requiresFollowUp:false,tags:[]});
    const room=await prisma.room.findFirstOrThrow({where:{number:'512'}});
    const reserved=await prisma.followUp.create({data:{action:'Reservado',visibility:'PRIVADO',createdById:owner.id,ownerId:owner.id,entryId:source.id}});
    const task=await prisma.task.create({data:{title:'Trabajo reservado',createdById:owner.id,entryId:source.id,followUpId:reserved.id,roomId:room.id,dueAt:new Date(Date.now()-3600000)}});
    expect(await prisma.followUp.count({where:{entryId:source.id,AND:[followUpReadWhere(reader)]}})).toBe(0);
    expect(await prisma.task.count({where:{entryId:source.id,AND:[taskFollowUpReadWhere(reader)]}})).toBe(0);
    expect(JSON.stringify((await getFormOptions(reader)).openTasks)).not.toContain('Trabajo reservado');
    await prisma.comment.create({data:{entryId:source.id,followUpId:reserved.id,authorId:owner.id,body:'Comentario reservado'}});
    const history=await getHistory({entity:'OperationalEntry',entityId:source.id},reader);
    expect(history.some(event=>event.id===reserved.id)).toBe(false);
    expect(JSON.stringify(history)).not.toContain('Comentario reservado');
    expect((await getHistory({entity:'OperationalEntry',entityId:source.id},owner)).some(event=>event.id===reserved.id)).toBe(true);
    expect((await getBookItems({},reader)).items.some(item=>item.id===task.id||item.id===reserved.id)).toBe(false);
    expect((await getBookItems({kinds:['task']},owner)).items.some(item=>item.id===task.id)).toBe(true);
    for(const origin of [{followUpId:reserved.id},{taskId:task.id}]){
      const alert=await prisma.alert.create({data:{title:'Aviso reservado',message:'Resultado reservado del origen',type:'TAREA_VENCIDA',level:'CRITICA',createdById:owner.id,...origin}});
      expect((await searchOperationalRecords(reader,'Aviso reservado')).some(row=>row.entityId===alert.id)).toBe(false);
      expect((await searchOperationalRecords(owner,'Aviso reservado')).some(row=>row.entityId===alert.id)).toBe(true);
      await expect(acknowledgeAlert(reader,alert.id)).rejects.toThrow();
      expect((await prisma.alert.findUniqueOrThrow({where:{id:alert.id}})).status).toBe('NUEVA');
    }
    await expect(getTask(task.id,reader)).rejects.toThrow();
    const context=await executeFrontiPageContextTool(reader,resolveFrontiPageContext({pathname:`/tareas/${task.id}`}));
    expect(context).toMatchObject({snapshot:{found:false}});
    expect(JSON.stringify(context)).not.toContain('Trabajo reservado');
    expect((await getTask(task.id,owner)).title).toBe('Trabajo reservado');
    expect((await getRoomMonitorOverview(reader)).rooms.find(r=>r.number==='512')?.openTasks).toBe(0);
    expect((await getRoomMonitorOverview(owner)).rooms.find(r=>r.number==='512')?.openTasks).toBe(1);
    expect((await getRoomMonitorDetail('512',reader)).tasks).toHaveLength(0);
    expect((await searchOperationalRecords(reader,'Trabajo reservado')).some(row=>row.entityId===task.id)).toBe(false);
    expect((await searchOperationalRecords(owner,'Trabajo reservado')).some(row=>row.entityId===task.id)).toBe(true);
    expect(JSON.stringify(await getSupervisionData(reader))).not.toContain('Trabajo reservado');
    const item=await prisma.taskChecklistItem.create({data:{taskId:task.id,text:'Paso reservado',order:0}});
    await expect(assignTask(reader,{id:task.id,assigneeId:reader.id})).rejects.toThrow();
    await expect(toggleChecklistItem(reader,{itemId:item.id,done:true})).rejects.toThrow();
    await expect(softDeleteTask(reader,{id:task.id,reason:'ID conocido fuera de alcance'})).rejects.toThrow();
    expect((await prisma.taskChecklistItem.findUniqueOrThrow({where:{id:item.id}})).done).toBe(false);
    await softDeleteTask(owner,{id:task.id,reason:'Archivo autorizado'});
    await expect(restoreTask(reader,{id:task.id})).rejects.toThrow();
    await restoreTask(owner,{id:task.id});
    await expect(changeTaskStatus(reader,{id:task.id,status:'EN_CURSO'})).rejects.toThrow();
    const attempt=new FormData();attempt.set('id',task.id);attempt.set('status','EN_CURSO');
    auth.current.mockResolvedValue(reader);
    await expect(changeTaskStatusAction(null,attempt)).resolves.toMatchObject({ok:false});
    expect((await prisma.task.findUniqueOrThrow({where:{id:task.id}})).status).toBe('PENDIENTE');
  });
  it('resolver o cerrar una incidencia exige un resultado real en el servicio',async()=>{
    const actor=await createUser({roleKey:ROLE_KEYS.SYSTEM_ADMIN});
    for(const status of ['RESUELTO','CERRADO'] as const){
      const incident=await createEntry(actor,{type:'INCIDENCIA',title:'Falla que requiere resultado',description:'Contexto real del procedimiento',priority:'ALTA',severity:'ALTA',requiresFollowUp:false,tags:[]});
      await expect(changeEntryStatus(actor,{id:incident.id,status})).rejects.toThrow('resolvió');
      await expect(changeEntryStatus(actor,{id:incident.id,status,resolution:'   '})).rejects.toThrow('resolvió');
      expect((await prisma.operationalEntry.findUniqueOrThrow({where:{id:incident.id}})).status).toBe('ABIERTO');
      await changeEntryStatus(actor,{id:incident.id,status,resolution:'Falla reparada y comprobada'});
      expect((await prisma.operationalEntry.findUniqueOrThrow({where:{id:incident.id}})).resolution).toBe('Falla reparada y comprobada');
    }
  });
  it('la aceptación registra recepción sólo por el responsable asignado',async()=>{
    const creator=await createUser({roleKey:ROLE_KEYS.SYSTEM_ADMIN});
    const receiver=await createUser({roleKey:ROLE_KEYS.SUPERVISOR});
    const task=await createTask(creator,{title:'Por recibir',assigneeId:receiver.id,priority:'MEDIA',tags:[],checklist:[]});
    await expect(changeTaskStatus(creator,{id:task.id,status:'ACEPTADA'})).rejects.toThrow('responsable');
    expect((await prisma.task.findUniqueOrThrow({where:{id:task.id}})).workAcknowledgedAt).toBeNull();
    await changeTaskStatus(receiver,{id:task.id,status:'ACEPTADA'});
    expect((await prisma.task.findUniqueOrThrow({where:{id:task.id}})).workAcknowledgedById).toBe(receiver.id);
  });
  it('permite validar con el permiso específico y conserva separación de ejecutor y reserva',async()=>{
    const executor=await createUser({roleKey:ROLE_KEYS.SYSTEM_ADMIN});
    const reviewer=await createUser({roleKey:ROLE_KEYS.MANAGEMENT});
    reviewer.permissions=['supervision.task.validate'];
    const task=await createTask(executor,{title:'Trabajo sujeto a revisión',priority:'MEDIA',tags:[],checklist:[],requiresIndependentValidation:true});
    await changeTaskStatus(executor,{id:task.id,status:'EN_CURSO'});
    await changeTaskStatus(executor,{id:task.id,status:'REALIZADA',evidenceProvided:'Resultado del ejecutor'});
    const form=new FormData();form.set('id',task.id);form.set('status','VALIDADA');
    auth.current.mockResolvedValue(executor);
    expect((await changeTaskStatusAction(null,form)).ok).toBe(false);
    auth.current.mockResolvedValue(reviewer);
    expect((await changeTaskStatusAction(null,form)).ok).toBe(true);
    expect(await prisma.task.findUnique({where:{id:task.id}})).toMatchObject({status:'VALIDADA',validatedById:reviewer.id,completedById:executor.id});
    const reserved=await prisma.followUp.create({data:{action:'Reservado',visibility:'PRIVADO',createdById:executor.id,ownerId:executor.id}});
    const privateTask=await prisma.task.create({data:{title:'Trabajo reservado',createdById:executor.id,followUpId:reserved.id,status:'REALIZADA',completedById:executor.id}});
    form.set('id',privateTask.id);
    expect((await changeTaskStatusAction(null,form)).ok).toBe(false);
    expect((await prisma.task.findUniqueOrThrow({where:{id:privateTask.id}})).status).toBe('REALIZADA');
  });
});
