import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {dynamicDelegationSchema,minorUnits,matchDelegatedStep} from '@/domain/fronti-delegation';
import {validateDynamicCatalog} from '@/server/ai/execution/delegation-scope';
const policy=()=>dynamicDelegationSchema.parse({requestKey:randomUUID(),instruction:'Delegación explícita sintética',objective:'Registrar importes acotados',availableAt:'2026-10-02T12:00:00-03:00',expiresAt:'2026-10-03T12:00:00-03:00',maxExecutions:3,maxActions:3,budget:{currency:'CLP',maxMinorUnits:5000},rules:[{action:'createManualCashMovementAction',fixedFields:{direction:'ENTRADA',currency:'CLP',reference:'Referencia autorizada'},variableFields:{amount:{type:'integer',min:1,max:2000}},cost:{field:'amount',currency:'CLP'}}]});
describe('Delegación dinámica: ámbito y presupuesto',()=>{
 it('cuenta moneda con enteros y rechaza redondeo o notación ambigua',()=>{expect(minorUnits('10.01','USD')).toBe(1001);expect(minorUnits('100.00','CLP')).toBe(100);for(const input of ['1.001','1e3','-1','1,000','NaN'])expect(()=>minorUnits(input,'USD')).toThrow();expect(()=>minorUnits('1.01','CLP')).toThrow();});
 it('no permite cambiar moneda, destino, importe máximo ni añadir identidad',()=>{const p=policy();const step={action:'createManualCashMovementAction',fields:{direction:'ENTRADA',currency:'CLP',reference:'Referencia autorizada',amount:'1500'}};expect(matchDelegatedStep(p,step).cost).toBe(1500);for(const patch of ([{currency:'USD'},{reference:'Otro destino'},{amount:'2001'},{executionIdentity:'otro'}] as Array<Record<string,string>>))expect(()=>matchDelegatedStep(p,{...step,fields:{...step.fields,...patch}})).toThrow();});
 it('valida catálogo y prohíbe identificadores arbitrarios en texto libre',()=>{const p=policy();expect(()=>validateDynamicCatalog(p)).not.toThrow();expect(()=>validateDynamicCatalog({...p,rules:[{action:'changeTaskStatusAction',fixedFields:{status:'EN_CURSO'},variableFields:{id:{type:'text',maxLength:100}}}]})).toThrow('identificadores');expect(()=>validateDynamicCatalog({...p,rules:[{action:'changeTaskStatusAction',fixedFields:{},variableFields:{id:{type:'record',kind:'entry',departmentId:'area',statuses:['PENDIENTE']}}}]})).toThrow('registro nativo');});
 it('ningún importe variable puede eludir el presupuesto',()=>{const p=policy();const rule=p.rules[0]!;expect(()=>validateDynamicCatalog({...p,rules:[{...rule,cost:undefined}]})).toThrow('monetario');expect(()=>dynamicDelegationSchema.parse({...p,budget:{currency:'USD',maxMinorUnits:5}})).toThrow();expect(()=>dynamicDelegationSchema.parse({...p,expiresAt:'2027-01-01T12:00:00Z'})).toThrow();});
});
