'use client';
import { useState } from 'react';
import { ActionForm, Field, Input, Select, Textarea } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { HK_WORK_KINDS, HK_KIND_LABELS, HK_ACTION_LABELS, HK_NOTE_REQUIRED, hkInspectionRequired, type HkWorkAction, type HkWorkKind } from '@/domain/housekeeping-work';
import { acceptHkHandoverAction, createHkWorkAction, changeHkWorkAction, saveHkRoutineAction, prepareHkDayAction, confirmHkAvailabilityAction, saveHkHandoverAction, receiveHkHandoverAction, delegateHkAction, revokeHkDelegationAction, organizeLegacyHkWorkAction } from '@/server/actions/housekeeping-work';

type Person = { id:string;name:string };
type Place = { id:string;number?:string;name?:string };
export function NewWorkForm({requestKey,date,departmentId,rooms,zones,team,canAssign,source}:{requestKey:string;date:string;departmentId:string;rooms:Place[];zones:Place[];team:Person[];canAssign:boolean;source?:{id:string;title:string;description:string;room:{id:string;number:string}|null}}) {
  const [kind,setKind]=useState<HkWorkKind>('ATENCION'); const [place,setPlace]=useState('room');
  return <Dialog title={canAssign?'Nuevo trabajo':'Solicitar atención'} description="Indica la necesidad real. Housekeeping organizará y confirmará el resultado." trigger={source?'Vincular trabajo':canAssign?'Nuevo trabajo':'Solicitar atención'} triggerVariant="gold" width="md">
    <ActionForm action={createHkWorkAction} refreshOnSuccess closeOnSuccess>
      <input type="hidden" name="requestKey" value={requestKey}/><input type="hidden" name="departmentId" value={departmentId}/>
      <Field label="Tipo de trabajo" name="workKind"><Select name="workKind" value={kind} onChange={e=>{const next=e.target.value as HkWorkKind;setKind(next);if(next==='LIMPIEZA')setPlace('room');}} options={HK_WORK_KINDS.map(k=>({value:k,label:HK_KIND_LABELS[k]}))}/></Field>
      <input type="hidden" name="sourceEntryId" value={source?.id??''}/><Field label="Qué se necesita" name="title"><Input name="title" required maxLength={160} placeholder="Preparar habitación / reponer toallas…" defaultValue={source?.title} readOnly={!!source}/></Field>
      <Field label="Instrucción" name="description"><Textarea name="description" required maxLength={3000} rows={3} defaultValue={source?.description} readOnly={!!source}/></Field>
      {kind!=='LIMPIEZA'&&<Field label="Dónde" name="place"><Select name="place" value={place} onChange={e=>setPlace(e.target.value)} options={[{value:'room',label:'Habitación'},{value:'zone',label:'Área registrada'},{value:'other',label:'Otra zona'}]}/></Field>}
      {place==='room'?<Field label="Habitación" name="roomId"><Select name="roomId" required defaultValue={source?.room?.id??''} options={[{value:'',label:'Seleccionar habitación'},...rooms.map(p=>({value:p.id,label:p.number!}))]}/></Field>:place==='zone'?<Field label="Área registrada" name="zoneId"><Select name="zoneId" required options={[{value:'',label:'Seleccionar área'},...zones.map(p=>({value:p.id,label:p.name!}))]}/></Field>:<Field label="Zona" name="location"><Input name="location" required maxLength={160} placeholder="Vestíbulo, pasillo del piso 5…"/></Field>}
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Día del trabajo" name="workDate"><Input type="date" name="workDate" defaultValue={date} required/></Field><Field label="Prioridad" name="priority"><Select name="priority" defaultValue="MEDIA" options={[{value:'BAJA',label:'Baja'},{value:'MEDIA',label:'Normal'},{value:'ALTA',label:'Alta'},{value:'CRITICA',label:'Urgente'}]}/></Field></div>
      {canAssign&&<Field label="Responsable" name="assignedToId" hint="Se usan cuentas existentes del área."><Select name="assignedToId" defaultValue="" options={[{value:'',label:'Por asignar'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field>}
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Tiempo estimado (minutos)" name="effortMinutes" hint="Sirve para comparar cargas; no registra horas trabajadas."><Input type="number" name="effortMinutes" min={1} max={480} defaultValue={20} required/></Field><Field label="Atender antes de" name="dueAt" hint="Opcional · hora de Chile"><Input type="datetime-local" name="dueAt"/></Field></div>
      {hkInspectionRequired(kind)?<p className="text-sm text-petrol-800">Este trabajo requiere inspección de otra persona.</p>:<label className="flex items-center gap-2 text-sm"><input name="requiresInspection" type="checkbox"/> Requiere revisión del supervisor</label>}
      <SubmitButton pendingLabel="Guardando…">{canAssign?'Guardar trabajo':'Enviar solicitud'}</SubmitButton>
    </ActionForm>
  </Dialog>;
}
export function WorkActionForm({id,version,action,team,defaultAssignee}:{id:string;version:number;action:HkWorkAction;team:Person[];defaultAssignee?:string}) {
  const hidden=<><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="action" value={action}/></>;
  if(!HK_NOTE_REQUIRED.includes(action))return <ActionForm action={changeHkWorkAction} refreshOnSuccess hideSuccess className="space-y-0">{hidden}<SubmitButton variant="secondary" size="sm" pendingLabel="Guardando…">{HK_ACTION_LABELS[action]}</SubmitButton></ActionForm>;
  return <Dialog title={HK_ACTION_LABELS[action]} trigger={HK_ACTION_LABELS[action]} triggerVariant="secondary" triggerSize="sm" width="sm" description={action==='APROBAR'?'Confirma sólo después de revisar el trabajo. Tu nombre quedará registrado.':'La instrucción o el resultado se conservará en el historial.'}>
    <ActionForm action={changeHkWorkAction} refreshOnSuccess closeOnSuccess>{hidden}
      {action==='ASIGNAR'&&<><Field label="Responsable" name="assignedToId"><Select name="assignedToId" required defaultValue={defaultAssignee??''} options={[{value:'',label:'Seleccionar persona'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Atender antes de" name="dueAt" hint="Opcional · conserva el plazo si se deja vacío"><Input type="datetime-local" name="dueAt"/></Field></>}
      {action==='MANTENIMIENTO'&&<Field label="Gravedad" name="severity"><Select name="severity" required options={[{value:'',label:'Seleccionar gravedad'},...['BAJA','MEDIA','ALTA','CRITICA'].map(v=>({value:v,label:v}))]}/></Field>}
      <Field label={action==='TERMINAR'?'Qué se hizo':action==='APROBAR'?'Resultado de la inspección':action==='CORREGIR'?'Qué debe corregirse':action==='ASIGNAR'?'Instrucción / motivo':action==='MANTENIMIENTO'?'Qué debe revisar Mantenimiento':'Motivo / información'} name="note"><Textarea name="note" required maxLength={3000} rows={3}/></Field>
      <SubmitButton pendingLabel="Guardando…">Confirmar</SubmitButton>
    </ActionForm>
  </Dialog>;
}
export function PrepareDayForm({departmentId,date,count}:{departmentId:string;date:string;count:number}){return <Dialog title="Preparar rutinas del día" trigger="Preparar rutinas" triggerVariant="secondary" width="sm" description={`${count} rutinas activas. Se incorporan una vez por día y después deben asignarse.`}><ActionForm action={prepareHkDayAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="departmentId" value={departmentId}/><Field label="Día" name="workDate"><Input name="workDate" type="date" required defaultValue={date}/></Field><p className="text-sm">Los pendientes anteriores continúan visibles. No se generan limpiezas sin una necesidad registrada.</p><SubmitButton pendingLabel="Preparando…">Incorporar rutinas</SubmitButton></ActionForm></Dialog>;}
export function RoutineForm({departmentId,routine}:{departmentId:string;routine?:{id:string;version:number;title:string;description:string;location:string;effortMinutes:number;requiresInspection:boolean;active:boolean}}){return <Dialog title={routine?'Editar rutina':'Nueva rutina'} trigger={routine?'Editar':'Nueva rutina'} triggerVariant="secondary" triggerSize="sm" width="sm"><ActionForm action={saveHkRoutineAction} refreshOnSuccess closeOnSuccess><input type="hidden" name="departmentId" value={departmentId}/>{routine&&<><input type="hidden" name="id" value={routine.id}/><input type="hidden" name="version" value={routine.version}/></>}<Field label="Trabajo recurrente" name="title"><Input name="title" required maxLength={160} defaultValue={routine?.title}/></Field><Field label="Instrucción" name="description"><Textarea name="description" required maxLength={3000} defaultValue={routine?.description}/></Field><Field label="Zona" name="location"><Input name="location" required maxLength={160} defaultValue={routine?.location}/></Field><Field label="Tiempo estimado (minutos)" name="effortMinutes"><Input name="effortMinutes" type="number" min={1} max={480} defaultValue={routine?.effortMinutes??20} required/></Field><label className="flex items-center gap-2 text-sm"><input name="requiresInspection" type="checkbox" defaultChecked={routine?.requiresInspection}/>Requiere inspección</label><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={routine?.active??true}/>Rutina activa</label><SubmitButton pendingLabel="Guardando…">Guardar rutina</SubmitButton></ActionForm></Dialog>;}
export function AvailabilityForm({departmentId,date,person}:{departmentId:string;date:string;person:Person&{available:boolean|null;note:string|null}}){return <Dialog title={`Disponibilidad · ${person.name}`} description="Confirma si está disponible para organizar trabajo. Esto no registra asistencia." trigger="Disponibilidad" triggerVariant="secondary" triggerSize="sm" width="sm"><ActionForm action={confirmHkAvailabilityAction} refreshOnSuccess closeOnSuccess><input type="hidden" name="departmentId" value={departmentId}/><input type="hidden" name="workDate" value={date}/><input type="hidden" name="userId" value={person.id}/><Field label="Disponibilidad" name="available"><Select name="available" defaultValue={person.available===false?'false':'true'} options={[{value:'true',label:'Disponible'},{value:'false',label:'No disponible'}]}/></Field><Field label="Observación" name="note" hint="Obligatoria si no está disponible"><Textarea name="note" maxLength={3000} defaultValue={person.note??''}/></Field><SubmitButton pendingLabel="Guardando…">Confirmar disponibilidad</SubmitButton></ActionForm></Dialog>;}
export function HandoverForm({departmentId,date,requestKey}:{departmentId:string;date:string;requestKey:string}){return <Dialog title="Dejar relevo del área" description="Conserva una copia de los pendientes y las llaves en custodia. El trabajo sigue abierto hasta completarse." trigger="Dejar relevo" triggerVariant="secondary" width="sm"><ActionForm action={saveHkHandoverAction} refreshOnSuccess closeOnSuccess><input type="hidden" name="departmentId" value={departmentId}/><input type="hidden" name="workDate" value={date}/><input type="hidden" name="requestKey" value={requestKey}/><Field label="Qué debe saber el equipo que recibe" name="note"><Textarea name="note" required maxLength={3000} rows={4}/></Field><SubmitButton pendingLabel="Guardando…">Guardar relevo</SubmitButton></ActionForm></Dialog>;}
export function ReceiveHandoverForm({id}:{id:string}){return <ActionForm action={receiveHkHandoverAction} refreshOnSuccess className="space-y-0"><input type="hidden" name="id" value={id}/><SubmitButton variant="secondary" size="sm" pendingLabel="Guardando…">Confirmar recepción del relevo</SubmitButton></ActionForm>;}
export function DelegationForm({departmentId,team}:{departmentId:string;team:Person[]}){return <Dialog title="Delegar cobertura temporal" description="Habilita una función del área durante un período de hasta 31 días. La inspección propia sigue bloqueada." trigger="Delegar cobertura" triggerVariant="secondary" width="sm"><ActionForm action={delegateHkAction} refreshOnSuccess closeOnSuccess><input type="hidden" name="departmentId" value={departmentId}/><Field label="Persona que cubre" name="userId"><Select name="userId" required options={[{value:'',label:'Seleccionar persona'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Función" name="permission"><Select name="permission" options={[{value:'housekeeping.assign',label:'Organizar y asignar trabajo'},{value:'housekeeping.inspect',label:'Inspeccionar trabajo de otras personas'}]}/></Field><Field label="Desde" name="startsAt" hint="Hora de Chile"><Input name="startsAt" type="datetime-local" required/></Field><Field label="Hasta" name="endsAt" hint="Hora de Chile"><Input name="endsAt" type="datetime-local" required/></Field><Field label="Motivo de la cobertura" name="reason"><Textarea name="reason" required maxLength={3000}/></Field><SubmitButton pendingLabel="Guardando…">Habilitar cobertura</SubmitButton></ActionForm></Dialog>;}
export function RevokeDelegationForm({id}:{id:string}){return <ActionForm action={revokeHkDelegationAction} refreshOnSuccess hideSuccess className="space-y-0"><input type="hidden" name="id" value={id}/><SubmitButton size="sm" variant="secondary" pendingLabel="Guardando…">Revocar cobertura</SubmitButton></ActionForm>;}

export function OrganizeLegacyForm({id,version,departmentId,date,rooms,team}:{id:string;version:number;departmentId:string;date:string;rooms:Place[];team:Person[]}){return <Dialog title="Organizar aviso existente" description="Conserva el folio y el historial. El trabajo vuelve a pendiente para confirmar la nueva asignación." trigger="Organizar trabajo" triggerVariant="secondary" triggerSize="sm" width="sm"><ActionForm action={organizeLegacyHkWorkAction} refreshOnSuccess closeOnSuccess><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="departmentId" value={departmentId}/><Field label="Día" name="workDate"><Input name="workDate" type="date" required defaultValue={date}/></Field><Field label="Tipo de trabajo" name="workKind"><Select name="workKind" defaultValue="ATENCION" options={HK_WORK_KINDS.map(k=>({value:k,label:HK_KIND_LABELS[k]}))}/></Field><Field label="Habitación" name="roomId" hint="Opcional salvo limpieza de habitación. Si se deja vacío se conserva la zona del aviso."><Select name="roomId" options={[{value:'',label:'Conservar zona del aviso'},...rooms.map(r=>({value:r.id,label:r.number!}))]}/></Field><Field label="Responsable" name="assignedToId"><Select name="assignedToId" options={[{value:'',label:'Por asignar'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field><Field label="Tiempo estimado (minutos)" name="effortMinutes"><Input name="effortMinutes" type="number" min={1} max={480} defaultValue={20} required/></Field><label className="flex items-center gap-2 text-sm"><input name="requiresInspection" type="checkbox"/>Requiere inspección (obligatoria en limpieza o revisión)</label><Field label="Instrucción / motivo" name="note"><Textarea name="note" required maxLength={3000}/></Field><SubmitButton pendingLabel="Guardando…">Incorporar al día</SubmitButton></ActionForm></Dialog>;}

export function AcceptHandoverForm({id}:{id:string}) {return <ActionForm action={acceptHkHandoverAction} refreshOnSuccess className="space-y-0"><input type="hidden" name="id" value={id}/><SubmitButton size="sm" pendingLabel="Guardando…">Pendientes revisados: aceptar continuidad</SubmitButton></ActionForm>;}
