import '../etapa1/guard.cjs';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
const f=JSON.parse(readFileSync('/tmp/etapa1-fixture.json','utf8'));const db=new PrismaClient(),browser=await chromium.launch({headless:true}),results=[];
try{
 for(const width of [1280,390]){
  const context=await browser.newContext({viewport:{width,height:900}});await context.addCookies([{name:'lor_session',value:f.users.admin.token,domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);await context.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname!=='localhost'||['/api/notifications/stream','/api/alarms','/api/auth/pulse'].some(p=>u.pathname.startsWith(p))?route.abort():route.continue();});const page=await context.newPage();page.setDefaultTimeout(12000);
  const response=await page.goto('http://localhost:3000/custodia');const heading=page.getByRole('heading',{name:'Objetos olvidados y custodia'});if(!(await heading.isVisible())){console.error('Custodia route diagnostic',JSON.stringify({status:response?.status(),url:page.url(),title:await page.title(),main:(await page.locator('main').innerText().catch(()=>'' )).slice(0,3000)}));}await heading.waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  await page.getByRole('button',{name:'Registrar objeto',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Registrar objeto encontrado'});await dialog.locator('input[name=item]').fill('Objeto sintético '+width);await dialog.locator('input[name=foundLocation]').fill('Lobby sintético');const local=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(Date.now()-60000)).replace(' ','T');await dialog.locator('input[name=foundAt]').fill(local);await dialog.locator('input[name=custodyLocation]').fill('Gabinete sintético');await dialog.getByRole('button',{name:'Guardar en custodia'}).click();await dialog.waitFor({state:'hidden'});
  await page.getByRole('heading',{name:'Objeto sintético '+width,exact:true}).waitFor();let row=await db.lostFoundItem.findFirstOrThrow({where:{item:'Objeto sintético '+width}});const fronti=await context.request.post('http://localhost:3000/api/fronti',{headers:{Origin:'http://localhost:3000'},data:{message:'/ejecutar '+JSON.stringify([{action:'changeLostFoundAction',fields:{id:row.id,version:String(row.version),action:'MOVER',custodyLocation:'Custodia Fronti '+width,note:'Reubicación autorizada'}}]),requestKey:randomUUID()}});const frontiBody=await fronti.json();assert.equal(fronti.status(),200,frontiBody.error);assert.match(frontiBody.reply,/Completado/);row=await db.lostFoundItem.findUniqueOrThrow({where:{id:row.id}});assert.equal(row.custodyLocation,'Custodia Fronti '+width);await page.goto('http://localhost:3000/custodia?q='+row.humanId);await page.locator('#objeto-'+row.humanId).waitFor();
  const article=page.locator('article').filter({hasText:'Objeto sintético '+width});await article.locator('[data-list-item][aria-haspopup="dialog"]').click();const custodyPanel=page.locator('[data-custody-detail="'+row.id+'"]');await custodyPanel.getByRole('button',{name:'Registrar entrega'}).click();dialog=page.getByRole('dialog',{name:'Registrar entrega'});await dialog.locator('textarea[name=note]').fill('Entrega sintética completada');await dialog.locator('textarea[name=evidenceNote]').fill('Acta sintética '+width);// Arm the document load event before submit: the preceding history.replaceState is only same-document navigation.
  await Promise.all([page.waitForEvent('load'),dialog.getByRole('button',{name:'Cerrar custodia'}).click()]);await dialog.waitFor({state:'hidden'});await article.getByText('Entregado',{exact:true}).waitFor();
  const final=await db.lostFoundItem.findUniqueOrThrow({where:{id:row.id}});assert.equal(final.status,'ENTREGADO');assert.equal(final.evidenceNote,'Acta sintética '+width);assert.equal(await db.lostFoundEvent.count({where:{itemId:row.id}}),3);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));results.push({width,scenario:'lost-found-register-custody-delivery-evidence',status:'passed',physicalSafari:false});
  const workerContext=await browser.newContext({viewport:{width,height:900}});await workerContext.addCookies([{name:'lor_session',value:f.users.worker.token,domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);await workerContext.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname!=='localhost'||['/api/notifications/stream','/api/alarms','/api/auth/pulse'].some(p=>u.pathname.startsWith(p))?route.abort():route.continue();});const workerPage=await workerContext.newPage();workerPage.setDefaultTimeout(12000);
  const clarificationEntry=await db.operationalEntry.create({data:{type:'NOVEDAD',title:'ACLARACION_E3_'+width,description:'Requiere dato del solicitante',departmentId:f.areaId,createdById:f.users.admin.id,ownerId:f.users.worker.id,workAssignedAt:new Date(),workAcknowledgedAt:new Date(),workAcknowledgedById:f.users.worker.id,workStartedAt:new Date(),workNextAction:'Revisar contexto'}});
  await workerPage.goto('http://localhost:3000/coordinacion?area='+f.areaId+'&mios=1');let card=workerPage.locator('article').filter({hasText:'ACLARACION_E3_'+width});await card.waitFor();await card.locator('[data-list-item][aria-haspopup="dialog"]').click();const workerPanel=workerPage.locator('[data-worklist-panel="registro-entry-'+clarificationEntry.id+'"]');await workerPanel.waitFor();await workerPanel.getByText('Recepción, siguiente acción y relevo',{exact:true}).click();const clarificationSummary=workerPanel.locator('summary').filter({hasText:'Necesito una aclaración'});await clarificationSummary.click();const clarificationDetails=clarificationSummary.locator('xpath=..');await clarificationDetails.locator('textarea[name=nextAction]').fill('¿La novedad sigue vigente?');await Promise.all([workerPage.waitForNavigation(),clarificationDetails.getByRole('button',{name:'Solicitar aclaración',exact:true}).click()]);
  const waiting=await db.operationalEntry.findUniqueOrThrow({where:{id:clarificationEntry.id}});assert.equal(waiting.status,'EN_ESPERA');assert.equal(waiting.workNextAction,'Aclaración requerida: ¿La novedad sigue vigente?');
  await page.goto('http://localhost:3000/coordinacion?area='+f.areaId+'&vista=clarification');card=page.locator('article').filter({hasText:'ACLARACION_E3_'+width});await card.waitFor();await card.locator('[data-list-item][aria-haspopup="dialog"]').click();const responsePanel=page.locator('[data-worklist-panel="registro-entry-'+clarificationEntry.id+'"]');await responsePanel.waitFor();const respondSummary=responsePanel.locator('summary').filter({hasText:'Responder aclaración'});const respond=respondSummary.locator('xpath=..');await respond.locator('textarea[name=nextAction]').fill('Sí, continúa vigente y requiere atención.');await Promise.all([page.waitForNavigation(),respond.getByRole('button',{name:'Responder aclaración',exact:true}).click()]);
  const resumed=await db.operationalEntry.findUniqueOrThrow({where:{id:clarificationEntry.id}});assert.equal(resumed.status,'EN_ESPERA');assert.match(resumed.workNextAction??'',/Aclaración recibida: Sí/);await workerPage.goto('http://localhost:3000/coordinacion?area='+f.areaId+'&mios=1');card=workerPage.locator('article').filter({hasText:'ACLARACION_E3_'+width});const nextAction=card.locator('p').filter({hasText:'Siguiente acción:'}).first();await nextAction.waitFor();assert.match(await nextAction.innerText(),/Aclaración recibida: Sí/);assert.ok(await workerPage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));results.push({width,scenario:'clarification-request-response-same-source',status:'passed',physicalSafari:false});
  await workerContext.close();await context.close();
 }
 console.log('Etapa 3 block 2 coordination/custody desktop/mobile journeys passed.',JSON.stringify(results));
}finally{writeFileSync('etapa3-block2-browser-results.json',JSON.stringify(results,null,2));await browser.close();await db.$disconnect();}
