'use server';
import { revalidatePath } from 'next/cache';
import type { KeyStatus } from '@prisma/client';
import { runAction, type ActionState } from '@/server/action';
import { requirePermission, requireUser } from '@/server/auth/guard';
import { RuleError } from '@/server/errors';
import { createAreaKey, lendStaffKeys, returnStaffKey, saveKeyArea, saveSupervisorKey, type StaffLoanInput } from '@/server/services/key-staff';
const value = (f: FormData, k: string) => String(f.get(k) ?? '').trim();
const refresh = () => { revalidatePath('/llaves'); revalidatePath('/llaves/personal'); revalidatePath('/llaves/personal/[id]', 'page'); revalidatePath('/habitaciones'); };
export async function saveKeyAreaAction(_: ActionState | null, f: FormData) { return runAction(async () => { const user = await requirePermission('key.stock'); const row = await saveKeyArea(user, { id: value(f,'id') || undefined, name: value(f,'name'), active: value(f,'active') !== 'false' }); refresh(); return { ok: true, id: row.id, message: 'Área guardada.' }; }); }
export async function createAreaKeyAction(_: ActionState | null, f: FormData) { return runAction(async () => { const user = await requirePermission('key.stock'); const row = await createAreaKey(user, { areaId: value(f,'areaId'), code: value(f,'code') }); refresh(); return { ok: true, id: row.id, message: 'Llave del área registrada.' }; }); }
export async function saveSupervisorKeyAction(_: ActionState | null, f: FormData) { return runAction(async () => { const user = await requireUser(); const row = await saveSupervisorKey(user, { id: value(f,'id') || undefined, version: Number(value(f,'version')), code: value(f,'code'), destination: value(f,'destination'), notes: value(f,'notes'), status: value(f,'status') as KeyStatus || undefined, retired: value(f,'retired') === 'true' }); refresh(); return { ok: true, id: row.id, message: 'Stock privado actualizado.' }; }); }
export async function lendStaffKeysAction(_: ActionState | null, f: FormData) { return runAction(async () => { const user = await requirePermission('key.assign'); const ids = f.getAll('keySelection').map(String); if (ids.length > 100) throw new RuleError('Selecciona hasta cien llaves.'); const items: StaffLoanInput['items'] = ids.map(id => ({ keyId: value(f,`key:${id}`), source: value(f,`source:${id}`) as 'public' | 'private', destinationId: value(f,`destination:${id}`), destinationKind: value(f,`kind:${id}`) as 'ROOM' | 'AREA' })); const row = await lendStaffKeys(user, { requestKey: value(f,'requestKey'), departmentId: value(f,'departmentId'), collaboratorId: value(f,'collaboratorId') || undefined, authorizedById: value(f,'authorizedById'), notes: value(f,'notes'), items }); refresh(); return { ok: true, id: row.id, message: `Entrega #${row.humanId} registrada. Ya figura en el inventario.` }; }); }
export async function returnStaffKeyAction(_: ActionState | null, f: FormData) { return runAction(async () => { const user = await requirePermission('key.assign'); await returnStaffKey(user, value(f,'itemId'), value(f,'notes')); refresh(); return { ok: true, message: 'Llave recibida y disponible.' }; }); }
