'use server';
import {z} from 'zod';
import {revalidatePath} from 'next/cache';
import {requireUser} from '@/server/auth/guard';
import {runAction,formDataToObject,type ActionState} from '@/server/action';
import {distributeSubject,decideAreaAttention} from '@/server/services/subject-distribution';
const dispatch=z.object({entryId:z.string().min(1).max(100),revision:z.string().datetime(),requestKey:z.string().uuid(),departmentIds:z.string().max(6000).transform(v=>JSON.parse(v)).pipe(z.array(z.string().min(1).max(100)).min(1).max(100)),location:z.string().trim().max(160).optional(),urgent:z.enum(['true','false']).transform(v=>v==='true'),urgencyReason:z.string().trim().max(1000).optional(),urgentContacts:z.string().max(6000).optional().transform(v=>v?JSON.parse(v):{}).pipe(z.record(z.string().max(100))),requiresValidation:z.enum(['true','false']).transform(v=>v==='true')});
const decision=z.object({id:z.string().min(1).max(100),version:z.coerce.number().int().positive(),sourceRevision:z.string().datetime(),action:z.enum(['CONOCER','INFORMAR','ASIGNAR','ACLARACION','RESPONDER','REVISAR_URGENCIA','TOMAR_URGENCIA','REABRIR']),note:z.string().trim().max(2000).optional(),assigneeId:z.string().max(100).optional()});
function refresh(entryId:string){for(const path of [`/libro/${entryId}`,'/coordinacion','/coordinacion/areas','/housekeeping','/tareas'])revalidatePath(path);}
export async function distributeSubjectAction(_state:ActionState|null,form:FormData):Promise<ActionState>{return runAction(async()=>{const user=await requireUser();const input=dispatch.parse(formDataToObject(form));const rows=await distributeSubject(user,input);refresh(input.entryId);return {ok:true as const,message:`Distribución interna conservada en ${rows.length} área(s).`,id:input.entryId,navigateTo:`/libro/${encodeURIComponent(input.entryId)}#distribucion-areas`};});}
export async function decideAreaAttentionAction(_state:ActionState|null,form:FormData):Promise<ActionState>{return runAction(async()=>{const user=await requireUser();const input=decision.parse(formDataToObject(form));const row=await decideAreaAttention(user,input);refresh(row.entryId);return {ok:true as const,message:input.action==='CONOCER'?'Conocimiento registrado; la publicación y la ejecución siguen separadas.':'Decisión registrada y vinculada al mismo asunto.',id:row.id,navigateTo:`/coordinacion/areas?atencion=${encodeURIComponent(row.id)}`};});}
