import {FrontiExecutionControls} from '@/components/operational/fronti-execution-controls';
import { ActionForm } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { completeProtectedFrontiStep } from '@/server/actions/fronti-protected';
import { getResetPreview } from '@/server/services/factory-reset';
import Link from 'next/link';
import { DELEGATION_STOPS, executionStatus } from '@/domain/fronti-execution';
import { executionActor, readExecution, executionCard } from '@/server/ai/execution/service';
import { FRONTI_ACTIONS } from '@/server/ai/execution/catalog';
import { prisma } from '@/lib/prisma';
import { formatDateTime } from '@/lib/format';
import { DisclosureCard } from '@/components/ui/card';

export const dynamic = 'force-dynamic';
export default async function ProceduresPage({ searchParams }: { searchParams: Promise<{ ejecucion?: string; delegaciones?: string }> }) {
  const user = await executionActor();
  const { ejecucion, delegaciones } = await searchParams;
  const detail = ejecucion ? await readExecution(ejecucion) : null;
  const pendingIndex = detail?.steps.findIndex(step=>step.status !== 'SUCCEEDED') ?? -1;
  const pending = pendingIndex >= 0 ? detail?.steps[pendingIndex] : undefined;
  const protectedAction = pending?.status === 'PENDING' && pending.requiresProtectedInput ? FRONTI_ACTIONS.find(action=>action.name===pending.action) : undefined;
  const card=detail&&['PREPARED','AUTHORIZED','PARTIAL'].includes(detail.status)&&!['DELEGATION','DYNAMIC','DELEGATED_USE'].includes(detail.authorizationKind)&&!detail.cancelledAt&&detail.expiresAt>new Date()?await executionCard(detail.id):null;
  const resetPreview = protectedAction?.name === 'factoryResetAction' && user.isSystemAdmin && user.permissions.includes('system.configure') ? await getResetPreview() : null;
  const recent = await prisma.frontiExecution.findMany({ where: { userId: user.id, ...(delegaciones === '1' ? { authorizationKind: {in:['DELEGATION','DYNAMIC']} } : {}) }, orderBy: { createdAt: 'desc' }, take: 25, select: { id: true, authorizationKind: true, expiresAt: true, authorizedAt: true, cancelledAt: true, steps:{select:{status:true}}, createdAt: true } });
  const uses = detail?.authorizationKind==='DYNAMIC' ? await prisma.frontiExecution.findMany({where:{parentDelegationId:detail.id,userId:user.id},select:{id:true,reservedMinorUnits:true,createdAt:true,steps:{select:{status:true}}},orderBy:{createdAt:'desc'},take:100}) : [];
  const label: Record<string,string> = { PREPARED:'Por autorizar', AUTHORIZED:'Autorizado', SUCCEEDED:'Completado', PARTIAL:'Parcial / en curso', INTERVENTION:'Requiere revisión', CANCELLED:'Cancelado', RUNNING:'En curso', PENDING:'Pendiente', CHANGED:'El registro cambió' };
  return <div className="mx-auto max-w-5xl space-y-5">
    <header><h1 className="text-xl font-semibold">Solicitudes de Fronti</h1><p className="text-sm text-slate-600">Tu autorización, tus permisos y un resultado por cada paso. Los datos físicos deben haber sido comprobados por ti.</p></header>
    <Link href="/coordinacion" className="underline">Volver a Coordinación</Link>
    <DisclosureCard title="Opciones avanzadas · Delegaciones" contentClassName="space-y-2 p-4"><p className="text-sm">Autoriza de 1 a 12 acciones con sus registros, destinatarios, importes y cantidades exactos. Duración máxima: 31 días. No admite comodines, ampliación del alcance ni repetición de pasos completados. Conserva las comprobaciones físicas y aprobaciones del procedimiento original.</p><details><summary>Comandos avanzados</summary><p className="text-sm">En Fronti: /delegar seguido de un objeto con objective, availableAt, expiresAt y steps. Las fechas deben incluir zona horaria. Crear la delegación no ejecuta ni programa acciones. Utilízala después con /usar-delegacion ID y revócala con /revocar-delegacion ID.</p></details><ul className="list-inside list-disc text-sm">{DELEGATION_STOPS.map(stop=><li key={stop}>{stop}</li>)}</ul><Link className="underline" href="?delegaciones=1">Ver mis últimas 25 delegaciones</Link></DisclosureCard>
    {detail?.delegationPolicy && <section className="card space-y-3 p-4"><h2 className="font-semibold">Delegación dinámica: {detail.objective}</h2><p>Vigencia: {formatDateTime(detail.availableAt!)} a {formatDateTime(detail.expiresAt)}. {detail.cancelledAt?'Revocada':detail.expiresAt<=new Date()?'Caducada':'Autorizada'}.</p><p>Usos reservados: {uses.length} / {detail.delegationPolicy.maxExecutions}. Acciones: {uses.reduce((n,use)=>n+use.steps.length,0)} / {detail.delegationPolicy.maxActions}.</p>{detail.delegationPolicy.budget && <p>Presupuesto reservado: {uses.reduce((n,use)=>n+use.reservedMinorUnits,0)} / {detail.delegationPolicy.budget.maxMinorUnits} {detail.delegationPolicy.budget.currency==='USD'?'centavos USD':'pesos CLP'}. Las reservas no se devuelven automáticamente tras errores o cancelación.</p>}<details><summary>Acciones, ámbito y campos autorizados</summary><pre className="overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(detail.delegationPolicy.rules,null,2)}</pre></details><p className="break-all text-sm">Revocar: /revocar-delegacion {detail.id}. Cada uso exige tu sesión vigente y los permisos originales. No se ejecuta sin una solicitud de uso ni aporta confirmaciones de otra persona.</p><ul>{uses.map(use=><li key={use.id}><Link className="underline" href={`?ejecucion=${use.id}`}>{formatDateTime(use.createdAt)} · {use.steps.filter(step=>step.status==='SUCCEEDED').length}/{use.steps.length} pasos completados</Link></li>)}</ul></section>}
    {detail?.authorizationKind === 'DELEGATION' && <section className="card space-y-2 p-4"><h2 className="font-semibold">Delegación: {detail.objective ?? 'Objetivo no disponible'}</h2><p>Vigencia: {formatDateTime(detail.availableAt!)} a {formatDateTime(detail.expiresAt)}.</p><p>{detail.cancelledAt ? 'Revocada' : detail.expiresAt <= new Date() ? 'Caducada' : detail.availableAt! > new Date() ? 'Vigencia futura' : 'Vigente'} · Límite: {detail.steps.length} acciones exactas, una ejecución de cada paso.</p><p className="break-all text-sm">Ejecutar: /usar-delegacion {detail.id}<br/>Revocar: /revocar-delegacion {detail.id}</p><details><summary>Alcance y datos autorizados</summary><ol className="space-y-3">{detail.steps.map((step,i)=><li key={i}><p>{i+1}. {step.label}</p><dl className="break-words text-sm">{Object.entries(step.parameters ?? {}).map(([key,value])=><div key={key}><dt className="font-medium">{key}</dt><dd className="whitespace-pre-wrap">{Array.isArray(value)?value.join(', '):value}</dd></div>)}</dl></li>)}</ol></details></section>}
    {card&&<section className="card space-y-3 p-4"><h2 className="font-semibold">{card.title}</h2><p className="whitespace-pre-wrap text-sm">{card.detail}</p><FrontiExecutionControls executionId={detail!.id} canAuthorize={Boolean(['PREPARED','AUTHORIZED','PARTIAL'].includes(detail!.status)&&pending?.status==='PENDING'&&!protectedAction)} canCancel={Boolean(detail!.steps.some(step=>['PENDING','RUNNING'].includes(step.status)))}/></section>}
    {detail && <section className="card space-y-3 p-4"><h2 className="font-semibold">Resultado: {label[detail.status] ?? detail.status}</h2><p className="text-sm">{formatDateTime(detail.createdAt)}</p><ol className="space-y-2">{detail.steps.map((step,i)=><li key={i}>{i+1}. {FRONTI_ACTIONS.find(a=>a.name===step.action)?.label ?? 'Procedimiento'}: {label[step.status] ?? step.status}{step.result && typeof step.result==='object' && 'message' in step.result ? <p className="text-sm text-slate-600">{String(step.result.message)}</p> : null}{step.result && typeof step.result==='object' && 'href' in step.result && typeof step.result.href==='string' && /^\/(tareas|libro)\//.test(step.result.href) ? <Link className="block text-sm underline" href={step.result.href}>Abrir registro original</Link> : null}{step.startedAt && <p className="text-xs text-slate-500">Inicio: {formatDateTime(step.startedAt)}{step.completedAt ? ` · Fin: ${formatDateTime(step.completedAt)} · Duración registrada: ${step.completedAt.getTime()-step.startedAt.getTime()} ms` : ' · Sin resultado final registrado'}</p>}</li>)}</ol><p className="text-sm">El resultado queda en esta solicitud y en el asunto original. Cancelar afecta a los pasos pendientes y conserva lo realizado.</p></section>}
    {detail && protectedAction && !detail.cancelledAt && detail.expiresAt > new Date() && <section className="card space-y-3 p-4"><h2 className="font-semibold">Completar paso protegido: {protectedAction.label}</h2><p className="text-sm">Estos datos se envían al procedimiento original. No se incluyen en el chat ni en el historial de Fronti. Sólo se ejecutará este paso; los demás conservarán su estado.</p><dl className="break-words text-sm">{Object.entries(pending?.parameters ?? {}).map(([key,value])=><div key={key}><dt className="font-medium">{key}</dt><dd>{Array.isArray(value)?value.join(', '):value}</dd></div>)}</dl>{resetPreview && <pre className="overflow-auto text-xs">{JSON.stringify(resetPreview,null,2)}</pre>}<ActionForm action={completeProtectedFrontiStep} className="space-y-3"><input type="hidden" name="executionId" value={detail.id}/><input type="hidden" name="position" value={pendingIndex}/><input type="hidden" name="authorization" value="AUTHORIZE_DISPLAYED_STEP"/>{protectedAction.protectedInputs.map(field=><label key={field} className="block text-sm">{(({file:'Archivo de horario',phrase:'Escribe DEJAR EN CERO para autorizar la eliminación mostrada',logoutAcknowledged:'Escribe CERRAR_MI_SESION para cerrar tu sesión al completar este paso',currentPassword:'Contraseña actual',newPassword:'Nueva contraseña',confirmPassword:'Confirmar nueva contraseña',password:'Nueva contraseña del usuario',apiKey:'Clave del proveedor',smtpPassword:'Contraseña SMTP (vacío conserva la actual)',inboundPassword:'Contraseña de entrada (vacío conserva la actual)'} as Record<string,string>))[field]??field}<input className="mt-1 block w-full rounded border p-2" name={field} type={field==='file'?'file':['phrase','logoutAcknowledged'].includes(field)?'text':'password'} autoComplete="off" required={!['smtpPassword','inboundPassword'].includes(field)}/></label>)}{protectedAction.protectedOutput && <p className="text-sm">Las credenciales generadas se mostrarán una sola vez aquí. Si se pierde la respuesta, utiliza el procedimiento de restablecer contraseña; no vuelvas a crear el usuario.</p>}<SubmitButton>Autorizar y completar este paso</SubmitButton></ActionForm></section>}
    <DisclosureCard title={delegaciones === '1' ? 'Tus últimas 25 delegaciones' : 'Tus últimas 25 solicitudes'} count={recent.length} defaultOpen={delegaciones === '1'} contentClassName="p-4">{recent.length ? <ul className="space-y-2">{recent.map(r=><li key={r.id}><Link className="underline" href={`?ejecucion=${r.id}`}>{formatDateTime(r.createdAt)} · {r.authorizationKind === 'DELEGATION' ? 'Delegación · ' : ''}{!r.cancelledAt && r.expiresAt <= new Date() && executionStatus(r) !== 'SUCCEEDED' ? 'Caducada · ' : ''}{r.authorizationKind==='DYNAMIC'?'Delegación dinámica':label[executionStatus(r)]??executionStatus(r)}</Link></li>)}</ul>:<p>No hay procedimientos registrados.</p>}</DisclosureCard>
    <DisclosureCard title="Acciones disponibles" contentClassName="space-y-2 p-4"><p className="mb-3 text-sm text-slate-600">Cada acción conserva tus permisos y las revisiones del procedimiento original.</p><ul className="grid gap-2 sm:grid-cols-2">{FRONTI_ACTIONS.filter(a=>user.isSystemAdmin||!a.permission||user.permissions.some(permission=>permission===a.permission)).map(a=><li key={a.name} className="rounded border p-2 text-sm">{a.label}{a.physical&&<span className="block text-xs text-slate-600">Requiere hechos declarados por una persona.</span>}</li>)}</ul></DisclosureCard>
  </div>;
}
