import 'server-only';
import { randomUUID } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import type { CurrentUser } from '@/server/auth/current-user';
import { ForbiddenError, NotFoundError, RuleError } from '@/server/errors';
import { assertReceptionOperationPermission } from './reception-operation-gate';

export const LOST_FOUND_STATUSES=['EN_CUSTODIA','ENTREGADO','DISPUESTO'] as const;
export type LostFoundStatus=(typeof LOST_FOUND_STATUSES)[number];
function canView(user:CurrentUser){return user.roleKey==='ADMINISTRADOR_SISTEMA'||user.permissions.includes('custody.view')||user.permissions.includes('custody.manage');}
function canManage(user:CurrentUser){return user.roleKey==='ADMINISTRADOR_SISTEMA'||user.permissions.includes('custody.manage');}
async function guard(user:CurrentUser,write=false){if(write?!canManage(user):!canView(user))throw new ForbiddenError();if(write)await assertReceptionOperationPermission(user,'custody.manage');}
async function eligibleCustodian(id:string){return prisma.user.findFirst({where:{id,active:true,deletedAt:null,hiddenFromSelectors:false,role:{operational:true}},select:{id:true,name:true}});}
export async function listLostFound(user:CurrentUser,input:{status?:string;q?:string}={}){await guard(user);return prisma.lostFoundItem.findMany({where:{isDemo:false,...(input.status&&LOST_FOUND_STATUSES.includes(input.status as LostFoundStatus)?{status:input.status}:{}),...(input.q?.trim()?{OR:[{item:{contains:input.q.trim(),mode:'insensitive'}},{foundLocation:{contains:input.q.trim(),mode:'insensitive'}},{custodyLocation:{contains:input.q.trim(),mode:'insensitive'}}]}:{})},include:{registeredBy:{select:{name:true}},custodian:{select:{name:true}},closedBy:{select:{name:true}},events:{orderBy:{createdAt:'desc'},take:30}},orderBy:[{status:'asc'},{foundAt:'desc'}],take:200});}
export async function lostFoundTeam(user:CurrentUser){await guard(user,true);return prisma.user.findMany({where:{active:true,deletedAt:null,hiddenFromSelectors:false,role:{operational:true}},select:{id:true,name:true},orderBy:{name:'asc'},take:300});}
export async function createLostFound(user:CurrentUser,input:{requestKey:string;item:string;foundLocation:string;foundAt:Date;custodyLocation:string;custodianId?:string}){await guard(user,true);if(!input.item.trim()||!input.foundLocation.trim()||!input.custodyLocation.trim())throw new RuleError('Indica el objeto, dónde se encontró y dónde queda en custodia.');if(input.foundAt>new Date(Date.now()+5*60000))throw new RuleError('La fecha del hallazgo no puede estar en el futuro.');const repeated=await prisma.lostFoundItem.findUnique({where:{requestKey:input.requestKey}});if(repeated){if(repeated.registeredById!==user.id)throw new ForbiddenError();return repeated;}const custodian=input.custodianId?await eligibleCustodian(input.custodianId):null;if(input.custodianId&&!custodian)throw new RuleError('Selecciona un usuario operativo activo como responsable de custodia.');try{return await prisma.$transaction(async tx=>{const row=await tx.lostFoundItem.create({data:{requestKey:input.requestKey,item:input.item.trim(),foundLocation:input.foundLocation.trim(),foundAt:input.foundAt,custodyLocation:input.custodyLocation.trim(),registeredById:user.id,custodianId:custodian?.id,events:{create:{actorId:user.id,action:'REGISTRAR',note:`Custodia: ${input.custodyLocation.trim()}${custodian?' · Responsable: '+custodian.name:''}`}}}});await tx.auditLog.create({data:{entity:'LostFoundItem',entityId:row.id,action:'CREAR',userId:user.id,sessionId:user.sessionId,summary:`Objeto olvidado #${row.humanId} registrado`,reason:input.foundLocation.trim()}});return row;});}catch(error:unknown){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const row=await prisma.lostFoundItem.findUnique({where:{requestKey:input.requestKey}});if(row?.registeredById===user.id)return row;}throw error;}}
export async function changeLostFound(user:CurrentUser,input:{id:string;version:number;action:'MOVER'|'ENTREGAR'|'DISPONER'|'REABRIR';custodyLocation?:string;custodianId?:string;note:string;evidenceNote?:string}){await guard(user,true);const note=input.note.trim();if(!note)throw new RuleError('Indica el motivo o resultado.');return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "LostFoundItem" WHERE "id"=${input.id} FOR UPDATE`;const current=await tx.lostFoundItem.findUnique({where:{id:input.id}});if(!current)throw new NotFoundError();if(current.version!==input.version)throw new RuleError('El registro cambió. Actualiza antes de continuar.');const final=['ENTREGAR','DISPONER'].includes(input.action);if(final&&current.status!=='EN_CUSTODIA')throw new RuleError('El objeto ya tiene un cierre registrado.');if(input.action==='REABRIR'&&current.status==='EN_CUSTODIA')throw new RuleError('El objeto ya está en custodia.');if(final&&!input.evidenceNote?.trim())throw new RuleError('Registra la evidencia o referencia de la entrega/disposición. No incluyas datos personales innecesarios.');let custodianId=current.custodianId;if(input.custodianId){const person=await eligibleCustodian(input.custodianId);if(!person)throw new RuleError('Selecciona un usuario operativo activo como responsable de custodia.');custodianId=person.id;}const next=input.action==='ENTREGAR'?'ENTREGADO':input.action==='DISPONER'?'DISPUESTO':'EN_CUSTODIA';const data:Prisma.LostFoundItemUncheckedUpdateManyInput={status:next,version:{increment:1},...(input.custodyLocation?.trim()?{custodyLocation:input.custodyLocation.trim()}:{}),custodianId,...(final?{finalAction:note,evidenceNote:input.evidenceNote!.trim(),closedById:user.id,closedAt:new Date()}:{finalAction:null,evidenceNote:null,closedById:null,closedAt:null})};const updated=await tx.lostFoundItem.updateMany({where:{id:current.id,version:input.version},data});if(!updated.count)throw new RuleError('Otra persona actualizó el registro. Recarga.');await tx.lostFoundEvent.create({data:{itemId:current.id,actorId:user.id,action:input.action,note:`${note}${input.evidenceNote?.trim()?' · Evidencia: '+input.evidenceNote.trim():''}`}});await tx.auditLog.create({data:{entity:'LostFoundItem',entityId:current.id,action:input.action==='REABRIR'?'REABRIR':'CAMBIO_ESTADO',userId:user.id,sessionId:user.sessionId,summary:`Objeto olvidado #${current.humanId}: ${input.action}`,reason:note,before:{status:current.status,custodyLocation:current.custodyLocation,custodianId:current.custodianId},after:{status:next,custodyLocation:input.custodyLocation?.trim()||current.custodyLocation,custodianId}}});return tx.lostFoundItem.findUniqueOrThrow({where:{id:current.id}});});}
export function newLostFoundKey(){return randomUUID();}
