'use client';
import {useState} from 'react';
import {ActionForm,Field,Input,Select,Textarea} from '@/components/ui/form';
import {SubmitButton} from '@/components/ui/button';
import {Dialog} from '@/components/ui/dialog';
import {createLostFoundAction,changeLostFoundAction} from '@/components/operational/navigation-action';
type Person={id:string;name:string};
export function NewLostFoundForm({requestKey,team}:{requestKey:string;team:Person[]}){return <Dialog title="Registrar objeto encontrado" trigger="Registrar objeto" width="sm" description="Registra sólo la información necesaria para identificar y custodiar el objeto."><ActionForm action={createLostFoundAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="requestKey" value={requestKey}/><Field label="Objeto" name="item"><Input name="item" required maxLength={240} placeholder="Ej.: mochila negra"/></Field><Field label="Lugar del hallazgo" name="foundLocation"><Input name="foundLocation" required maxLength={240}/></Field><Field label="Fecha y hora del hallazgo" name="foundAt"><Input name="foundAt" type="datetime-local" required/></Field><Field label="Ubicación de custodia" name="custodyLocation"><Input name="custodyLocation" required maxLength={240} placeholder="Ej.: gabinete de Recepción"/></Field><Field label="Responsable de custodia" name="custodianId"><Select name="custodianId" options={[{value:'',label:'Sin responsable individual'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field><p className="text-xs text-slate-600">No registres documento, teléfono, correo u otros datos personales salvo que sean indispensables para el procedimiento.</p><SubmitButton>Guardar en custodia</SubmitButton></ActionForm></Dialog>}
export function LostFoundAction({id,version,action,team,currentLocation,currentCustodian}:{id:string;version:number;action:'MOVER'|'ENTREGAR'|'DISPONER'|'REABRIR';team:Person[];currentLocation:string;currentCustodian?:string|null}){const [location,setLocation]=useState(currentLocation);const final=action==='ENTREGAR'||action==='DISPONER';const labels={MOVER:'Mover / cambiar responsable',ENTREGAR:'Registrar entrega',DISPONER:'Registrar disposición final',REABRIR:'Reabrir custodia'};return <Dialog title={labels[action]} trigger={labels[action]} triggerVariant="secondary" triggerSize="sm" width="sm"><ActionForm action={changeLostFoundAction} closeOnSuccess refreshOnSuccess><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="action" value={action}/>{!final&&<><Field label="Ubicación de custodia" name="custodyLocation"><Input name="custodyLocation" required value={location} onChange={e=>setLocation(e.target.value)} maxLength={240}/></Field><Field label="Responsable de custodia" name="custodianId"><Select name="custodianId" defaultValue={currentCustodian??''} options={[{value:'',label:'Sin responsable individual'},...team.map(p=>({value:p.id,label:p.name}))]}/></Field></>}<Field label={final?'Resultado / disposición':'Motivo'} name="note"><Textarea name="note" required maxLength={2000} rows={3}/></Field>{final&&<Field label="Evidencia o referencia" name="evidenceNote" hint="Ej.: acta interna, fotografía registrada o referencia del procedimiento. Evita datos personales innecesarios."><Textarea name="evidenceNote" required maxLength={1000} rows={2}/></Field>}<SubmitButton>{final?'Cerrar custodia':'Guardar cambio'}</SubmitButton></ActionForm></Dialog>}
