import { scheduleLabel, scheduleClock, collaboratorReference } from '@/domain/schedule-display';
import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { redirect } from 'next/navigation';
import { requireSchedulePageUser } from '@/server/auth/schedule';
import { getScheduleBoard, getScheduleDepartments, getSchedulePlan } from '@/server/services/schedules';
import { getScheduleCatalog } from '@/server/services/schedule-catalog';
import { scheduleAreaIds, assertScheduleArea } from '@/server/services/schedule-access';
import { coverageSlots, scheduledAt, EXTRA_LABELS, SLOT_LABELS, dateDays, holidayDates, plannedMinutes, scheduleAllowed } from '@/domain/schedule';
import { hotelDateKey } from '@/domain/time';
import { formatCalendarDate, formatDateTime, formatTime } from '@/lib/format';
import { StatTile } from '@/components/ui/card';
import { ViewTabs } from '@/components/layout/view-tabs';
import { ScheduleCalendar } from '@/components/schedule/calendar';
import { AcknowledgeScheduleForm, ApplyScheduleImportForm, RefreshScheduleImportForm, NewSchedulePlanForm, PublishScheduleForm, ScheduleUploadForm, type CalendarPlan, type CalendarSlot } from '@/components/schedule/schedule-forms';
import { ScheduleCollaboratorForm, ScheduleCoverageForm, ScheduleGrantForm, ScheduleHolidayForm, ScheduleTemplateForm } from '@/components/schedule/catalog-forms';

export const metadata = { title: 'Equipo y horarios' };
export const dynamic = 'force-dynamic';
type Params = { area?: string; malla?: string; seccion?: string };
export default async function SchedulePage({ searchParams }: { searchParams: Promise<Params> }) {
  const user = await requireSchedulePageUser(); const params = await searchParams; const departments = await getScheduleDepartments(user);
  const focusDepartmentId = params.malla && !params.area ? (await getSchedulePlan(user, params.malla)).departmentId : null;
  const department = params.area ? departments.find((d) => d.id === params.area) : focusDepartmentId ? departments.find((d) => d.id === focusDepartmentId) : departments.find((d) => d.key === 'RECEPCION') ?? departments[0];
  if (params.area && !department) redirect('/sin-permisos');
  const section = ['colaboradores', 'plantillas', 'cobertura', 'configuracion'].includes(params.seccion ?? '') ? params.seccion! : 'calendario';
  const base = `/equipo${department ? `?area=${department.id}` : ''}`;
  const scope = await scheduleAreaIds(user); const writable = !!department && (!scope || scope.includes(department.id));
  const catalogAllowed = writable && scheduleAllowed(user, 'schedule.catalog.manage'); const configure = scheduleAllowed(user, 'schedule.configure');
  if (section !== 'calendario' && !catalogAllowed && !(section === 'configuracion' && configure)) redirect('/sin-permisos');
  const tab = (s: string) => `${base}${base.includes('?') ? '&' : '?'}seccion=${s}`;
  return <div className="mx-auto max-w-[1600px] space-y-4"><header><h1 className="text-xl font-semibold text-petrol-900">Equipo y horarios</h1><p className="text-sm text-slate-600">Organiza los horarios y revisa cuántas personas cubren cada área.</p></header><div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">Aquí organizas quién trabaja y a qué hora. Cada persona confirma su asistencia al iniciar su turno en Recepción; publicar un horario no abre Recepción ni Caja.</div>
    {department ? <><form action="/equipo" className="flex flex-wrap items-end gap-3"><label className="min-w-[180px] text-sm font-medium text-slate-700">Área<select className="input-base mt-1 w-full" name="area" defaultValue={department.id}>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><input name="seccion" type="hidden" value={section} /><button className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-medium" type="submit">Consultar área</button></form><ViewTabs label="Secciones de Equipo y horarios" activeHref={tab(section)} tabs={[{ label: 'Calendario', href: tab('calendario') }, ...(catalogAllowed ? [{ label: 'Colaboradores', href: tab('colaboradores') }, { label: 'Plantillas', href: tab('plantillas') }, { label: 'Cobertura mínima', href: tab('cobertura') }] : []), ...(configure ? [{ label: 'Alcance y feriados', href: tab('configuracion') }] : [])]} />
      {section === 'calendario' ? <CalendarSection user={user} departmentId={department.id} focusId={params.malla} /> : <CatalogSection user={user} departmentId={department.id} section={section} departments={departments} scope={scope} />}
    </> : <div className="card p-6 text-sm text-slate-600">{scheduleAllowed(user, 'schedule.manage') ? 'No tienes un área habilitada. El administrador puede asignar el área principal de tu cuenta o un alcance adicional.' : 'Aún no hay un colaborador vinculado a tu cuenta o un área habilitada para consultar.'}</div>}
  </div>;
}
async function CalendarSection({ user, departmentId, focusId }: { user: Awaited<ReturnType<typeof requireSchedulePageUser>>; departmentId: string; focusId?: string }) {
  const board = await getScheduleBoard(user, departmentId, focusId); const now = new Date(); const today = hotelDateKey(now);
  const plan: CalendarPlan | null = board.selected ? { id: board.selected.id, humanId: board.selected.humanId, version: board.selected.version, status: board.selected.status, startDate: board.selected.startDate.toISOString().slice(0, 10), endDate: board.selected.endDate.toISOString().slice(0, 10) } : null;
  const people = [...board.collaborators];
  for (const s of board.slots) if (!people.some((p) => p.id === s.collaboratorId)) { const p = s.collaborator; people.push({ id: p.id, employeeCode: p.employeeCode, name: p.name, username: p.user?.username ?? null, functionName: s.functionName, weeklyMinutes: p.weeklyMinutes, userId: p.userId, active: false, minRestMinutes: 0, version: 0, createdAt: new Date(), updatedAt: new Date() }); }
  const slots: CalendarSlot[] = board.slots.map((s) => ({ id: s.id, collaboratorId: s.collaboratorId, kind: s.kind, code: s.code, templateId: s.templateId, startTime: s.startTime, endTime: s.endTime, crossesMidnight: s.crossesMidnight, extraKind: s.extraKind, extraMinutes: s.extraMinutes, extraStatus: s.extraStatus, reportedExtraMinutes: s.reportedExtraMinutes, note: s.note, breakMinutes: s.breakMinutes, breakPaid: s.breakPaid, date: s.date.toISOString().slice(0, 10), startAt: s.startAt?.toISOString() ?? null, endAt: s.endAt?.toISOString() ?? null, plannedMinutes: plannedMinutes(s) }));
  const holidays = board.holidays.map((h) => ({ date: h.date.toISOString().slice(0, 10), name: h.name }));
  const current = coverageSlots(board.contextSlots).filter((s) => scheduledAt(s, now));
  const mine = board.acknowledgments.find((a) => a.userId === user.id); const days = plan ? dateDays(plan.startDate, plan.endDate) : [];
  return <><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{board.plans.map((p) => <Link key={p.id} href={`/equipo?area=${departmentId}&malla=${p.id}`} className={`rounded border px-3 py-2 text-xs ${p.id === plan?.id ? 'border-petrol-400 bg-petrol-50 font-semibold text-petrol-900' : 'border-slate-200 bg-white text-slate-600'}`}>#{p.humanId} · {formatCalendarDate(p.startDate)}–{formatCalendarDate(p.endDate)} · {p.status === 'PUBLICADO' ? 'Publicado' : 'Borrador'}</Link>)}</div>{board.canManage && <NewSchedulePlanForm departmentId={departmentId} today={today} requestKey={randomUUID()} />}</div>
    {plan ? <><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Horario #{plan.humanId} · {plan.status === 'PUBLICADO' ? 'Publicada' : 'Borrador'} · revisión {plan.version}</p>{board.canPublish && plan.status !== 'PUBLICADO' && <PublishScheduleForm plan={plan} requestKey={randomUUID()} gaps={board.gaps.length} />}</div>
      {mine && !mine.acknowledgedAt && <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><p>Tu horario requiere revisión · versión {mine.version}. Confirmar recepción no acredita asistencia.</p><AcknowledgeScheduleForm planId={plan.id} version={mine.version} /></div>}
      {board.team && <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><StatTile label="Colaboradores programados" value={new Set(slots.map((s) => s.collaboratorId)).size} /><StatTile label="Periodos sin cubrir" value={board.gaps.length} /><StatTile label="Extras por aprobar" value={slots.filter((s) => s.extraStatus === 'PENDIENTE').length} /><StatTile label="Días feriados del periodo" value={holidays.filter((h) => days.includes(h.date)).length} /></div>}
      <ScheduleCalendar key={plan.id} plan={plan} people={people.map(({ id, name, employeeCode, functionName, weeklyMinutes, userId, username }) => ({ id, name, employeeCode, functionName, weeklyMinutes, userId, username }))} templates={board.templates.map(({ id, code, label, startTime, endTime, crossesMidnight }) => ({ id, code, label, startTime, endTime, crossesMidnight }))} slots={slots} holidays={holidays} canManage={board.canManage && (plan.status !== 'PUBLICADO' || board.canPublish)} canApprove={board.canApprove} currentUserId={user.id} canReportOwn={scheduleAllowed(user, 'schedule.self.view')} now={now.toISOString()} totals={board.totals} />
      {board.team && <section className="card space-y-2 p-4"><h2 className="font-semibold text-petrol-900">Cobertura y coordinación</h2>{!board.rules.length ? <p className="text-sm text-amber-800">Sin cobertura mínima configurada. El sistema no puede determinar si hay personal suficiente.{scheduleAllowed(user, 'schedule.catalog.manage') && <> <Link className="underline" href={`/equipo?area=${departmentId}&seccion=cobertura`}>Definir franjas y funciones.</Link></>}</p> : !board.gaps.length ? <p className="text-sm text-green-800">La programación cubre las reglas configuradas del área.</p> : <details><summary className="cursor-pointer text-sm font-medium text-amber-900">{board.gaps.length} periodos con falta de personal · ver detalle</summary><ul className="mt-3 space-y-2 text-sm">{board.gaps.map((gap, i) => <li key={i} className="rounded bg-amber-50 p-2 text-amber-900"><strong>{gap.name}</strong> · {formatDateTime(gap.startAt)} → {formatDateTime(gap.endAt)} · {gap.scheduled} de {gap.required} personas requeridas.</li>)}</ul></details>}<p className="text-xs text-slate-600">La cobertura utiliza el horario completo y extras aprobados. No acredita presencia física.</p>{current.length > 0 && <div><h3 className="mt-3 text-sm font-semibold">Programados en la franja actual</h3><ul className="mt-1 space-y-1 text-sm">{current.map((s) => <li key={s.id}>{people.find((p) => p.id === s.collaboratorId)?.name ?? 'Colaborador'} · {s.code} · {formatTime(s.startAt)}–{formatTime(s.endAt)}</li>)}</ul></div>}</section>}
      {holidays.some((h) => days.includes(h.date)) && <section className="card p-4"><h2 className="font-semibold text-petrol-900">Quién está programado en feriados</h2><ul className="mt-2 space-y-2 text-sm">{holidays.filter((h) => days.includes(h.date)).map((h) => <li key={h.date}><strong>{formatCalendarDate(h.date)} · {h.name}</strong><p className="text-slate-600">{board.contextSlots.filter((s) => holidayDates(s, [h]).length).map((s) => `${people.find((p) => p.id === s.collaboratorId)?.name ?? 'Colaborador'} (${s.code}${s.extraKind !== 'NINGUNO' ? ` · ${s.extraStatus.toLowerCase()}` : ''})`).join(' · ') || 'Sin personal programado.'}</p></li>)}</ul></section>}
      {board.canManage && <section className="card space-y-3 p-4"><h2 className="font-semibold text-petrol-900">Cargar un horario</h2><p className="text-sm text-slate-600">Se admiten horarios con fechas en columnas o una fila por asignación. Los nombres deben coincidir exactamente con colaboradores registrados; la plantilla CSV utiliza sus códigos. Un archivo no reemplaza casillas existentes. Las asignaciones pasadas o ya iniciadas se omiten y permanecen visibles en la revisión.</p><Link className="text-sm text-petrol-700 underline" href="/api/equipo/plantilla">Descargar plantilla CSV</Link><ScheduleUploadForm planId={plan.id} />{board.imports.map((draft) => {
        const issues = Array.isArray(draft.issues) ? draft.issues.map(String) : ['No se pudo leer la revisión.']; const rows = Array.isArray(draft.rows) ? draft.rows : []; const omittedRows = draft.omittedRows;
        return <article key={draft.id} className="space-y-2 rounded border border-slate-200 p-3"><h3 className="font-medium">{draft.fileName} · {rows.length} asignaciones reconocidas</h3><RefreshScheduleImportForm importId={draft.id} /><p className="text-xs text-slate-500">Revisión sobre versión {draft.baseVersion} · {formatDateTime(draft.createdAt)}</p><p className="text-sm text-slate-600">{rows.length - omittedRows.length} coincidencias vigentes · {omittedRows.length} omitidas por pertenecer al pasado o haber comenzado. Solo se incorporan las vigentes; las casillas existentes se conservan.</p><details><summary className="cursor-pointer text-sm">Ver coincidencias reconocidas</summary><ul className="mt-2 text-xs">{rows.map((r, i) => { const row = r as { source?: { name?: string; employeeCode?: string; date?: string; code?: string; startTime?: string; endTime?: string; crossesMidnight?: boolean }; issue?: string }; return <li key={i} className="border-b border-slate-100 py-1">{row.source?.name ?? row.source?.employeeCode} · {row.source?.date} · {row.source && scheduleLabel({ ...row.source, code: row.source.code ?? '', crossesMidnight: Boolean(row.source.startTime && row.source.endTime && row.source.endTime <= row.source.startTime) })}{omittedRows.includes(i) && <span className="text-amber-800"> · Omitida: pertenece al pasado o ya comenzó.</span>}{row.issue && <span className="text-red-700"> · {row.issue}</span>}</li>; })}</ul></details>{issues.length ? <details><summary className="text-sm font-medium text-red-800">{issues.length} observaciones por resolver</summary><ul className="mt-2 list-inside list-disc text-xs text-red-800">{issues.map((issue, i) => <li key={i}>{issue}</li>)}</ul></details> : draft.baseVersion !== plan.version ? <p className="text-sm text-amber-800">El horario cambió. Usa «Volver a revisar coincidencias» para actualizar esta revisión.</p> : rows.length === omittedRows.length ? <p className="text-sm text-slate-600">No quedan asignaciones futuras para incorporar.</p> : <ApplyScheduleImportForm plan={plan} importId={draft.id} requestKey={randomUUID()} />}</article>;
      })}</section>}
      {(board.canManage || board.canPublish) && <section className="card p-4"><h2 className="font-semibold text-petrol-900">Cambios y recepción del horario</h2><details className="mt-2"><summary className="cursor-pointer text-sm">Historial · últimos 50 cambios</summary><ol className="mt-2 space-y-2 text-xs text-slate-600">{board.events.map((event) => <li key={event.id}><strong>{event.actor.name}</strong> · {event.action.replaceAll('_', ' ').toLowerCase()} · revisión {event.version} · {formatDateTime(event.createdAt)}{event.reason && <p>{event.reason}</p>}<details><summary className="cursor-pointer">Ver valores anteriores y nuevos</summary><div className="mt-1 space-y-2 rounded bg-slate-50 p-2"><p><strong>Antes:</strong> {describeScheduleChange(event.before, people)}</p><p><strong>Después:</strong> {describeScheduleChange(event.after, people)}</p></div></details></li>)}</ol></details><ul className="mt-3 space-y-1 text-xs text-slate-600">{board.acknowledgments.filter((a, i, all) => all.findIndex((b) => b.userId === a.userId) === i).map((a) => <li key={a.id}>{a.user.name} · revisión {a.version} · {a.acknowledgedAt ? `recibida ${formatDateTime(a.acknowledgedAt)}` : 'pendiente de confirmar'}</li>)}</ul></section>}
    </> : <div className="card p-6 text-sm text-slate-600">{board.canManage ? 'Crea una malla y registra los colaboradores y plantillas del área para comenzar.' : 'No hay horarios publicados disponibles en esta área.'}</div>}
  </>;
}
async function CatalogSection({ user, departmentId, section, departments, scope }: { user: Awaited<ReturnType<typeof requireSchedulePageUser>>; departmentId: string; section: string; departments: { id: string; name: string }[]; scope: string[] | null }) {
  await assertScheduleArea(user, departmentId, section === 'configuracion' ? 'schedule.configure' : 'schedule.catalog.manage'); const data = await getScheduleCatalog(user, departmentId, section === 'configuracion'); const areas = departments.filter((d) => !scope || scope.includes(d.id));
  if (section === 'colaboradores') return <section className="card space-y-4 p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold text-petrol-900">Colaboradores del área</h2><ScheduleCollaboratorForm areas={areas} accounts={data.accounts} departmentId={departmentId} /></div><ul className="divide-y divide-slate-100">{data.collaborators.map((person) => <li key={person.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><strong className="text-sm">{person.name}</strong><p className="text-xs text-slate-600">{collaboratorReference(person) ? `${collaboratorReference(person)} · ` : ''}{person.functionName} · {person.active ? 'Activo' : 'Inactivo'} · {person.userId ? 'Cuenta vinculada' : 'Histórico sin usuario: requiere vinculación'}</p></div><ScheduleCollaboratorForm areas={areas} accounts={data.accounts} departmentId={departmentId} person={person} editable={!scope || person.memberships.every((m) => scope.includes(m.departmentId))} /></li>)}</ul></section>;
  if (section === 'plantillas') return <section className="card space-y-4 p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold text-petrol-900">Tipos de turno del área</h2><ScheduleTemplateForm departmentId={departmentId} /></div><p className="text-sm text-slate-600">Recepción incluye RD01, RD02 y RN01 según las horas definidas. Las horas y la cobertura consideran el horario completo, sin descuentos por descansos. No hay colaboradores ni jornadas cargados automáticamente.</p><ul className="divide-y divide-slate-100">{data.templates.map((t) => <li key={t.id} className="flex flex-wrap justify-between gap-3 py-3"><div><strong className="text-sm">{t.code} · {t.label}</strong><p className="text-xs text-slate-600">{scheduleClock(t)} · revisión {t.revision} · {t.active ? 'Vigente' : 'Histórica'}</p></div>{t.active && <ScheduleTemplateForm departmentId={departmentId} template={t} />}</li>)}</ul></section>;
  if (section === 'cobertura') return <section className="card space-y-4 p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold text-petrol-900">Cobertura mínima</h2><ScheduleCoverageForm departmentId={departmentId} /></div><ul className="divide-y divide-slate-100">{data.coverage.map((r) => <li key={r.id} className="flex flex-wrap justify-between gap-3 py-3"><div><strong className="text-sm">{r.name}</strong><p className="text-xs text-slate-600">{r.minimum} personas · {r.functionName || 'Cualquier función'} · {r.startTime}–{r.endTime}{r.crossesMidnight ? ' (+1 día)' : ''} · {r.active ? 'Activa' : 'Inactiva'}</p></div><ScheduleCoverageForm departmentId={departmentId} rule={r} /></li>)}</ul><p className="text-xs text-slate-600">Las brechas orientan la decisión del supervisor. Publicar una malla con brechas exige dejar un motivo.</p></section>;
  return <div className="grid gap-4 xl:grid-cols-2"><section className="card space-y-3 p-4"><h2 className="font-semibold text-petrol-900">Alcance adicional por cuenta</h2><ScheduleGrantForm areas={departments} accounts={data.accounts} /><ul className="space-y-1 text-xs text-slate-600">{data.grants.map((g) => <li key={`${g.userId}:${g.departmentId}`}>{g.user.name} · {g.department.name}</li>)}</ul></section><section className="card space-y-3 p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-petrol-900">Feriados del alojamiento</h2><ScheduleHolidayForm /></div><p className="text-sm text-slate-600">Catálogo nacional 2026 precargado. Revisa feriados extraordinarios, locales y años posteriores; se administran aquí con su fuente.</p><ul className="divide-y divide-slate-100">{data.holidays.map((h) => <li key={h.id} className="flex items-center justify-between gap-3 py-2"><div className="text-xs"><strong>{formatCalendarDate(h.date)} · {h.name}</strong><p>{h.active ? 'Activo' : 'Inactivo'}</p></div><ScheduleHolidayForm holiday={{ ...h, date: h.date.toISOString().slice(0, 10) }} /></li>)}</ul></section></div>;
}

function describeScheduleChange(value: unknown, people: { id: string; name: string }[]): string {
  if (value == null) return 'Sin asignación anterior.';
  if (Array.isArray(value)) return value.map((v) => describeScheduleChange(v, people)).join(' · ') || 'Sin asignaciones.';
  if (typeof value !== 'object') return 'Cambio registrado.';
  const row = value as Record<string, unknown>;
  if (Array.isArray(row.slots)) return `${row.status === 'PUBLICADO' ? 'Horario publicado' : 'Horario'} · ${row.slots.length} asignaciones.`;
  if (typeof row.collaboratorId === 'string') {
    const name = people.find((p) => p.id === row.collaboratorId)?.name ?? 'Colaborador';
    const date = typeof row.date === 'string' ? formatCalendarDate(row.date.slice(0, 10)) : '';
    const kind = SLOT_LABELS[row.kind as keyof typeof SLOT_LABELS] ?? 'Asignación';
    const hours = ` ${scheduleClock({ startTime: typeof row.startTime === 'string' ? row.startTime : null, endTime: typeof row.endTime === 'string' ? row.endTime : null, crossesMidnight: row.crossesMidnight === true })}`;
    const extra = row.extraKind !== 'NINGUNO' && typeof row.extraKind === 'string' ? ` · ${EXTRA_LABELS[row.extraKind]}: ${EXTRA_LABELS[String(row.extraStatus)]}${row.extraMinutes ? ` (${row.extraMinutes} min)` : ''}` : '';
    return `${name} · ${date} · ${row.code || kind}${hours}${extra}${row.cancelledAt ? ' · Cancelada' : ''}${row.note ? ` · ${row.note}` : ''}`;
  }
  if (row.status) return row.status === 'PUBLICADO' ? 'Horario publicado.' : 'Borrador.';
  if (row.importId) return `Carga incorporada · ${Array.isArray(row.assignments) ? row.assignments.length : row.count ?? ''} asignaciones · ${Array.isArray(row.omitted) ? row.omitted.length : 0} omitidas por haber comenzado o pertenecer al pasado.`;
  return 'Cambio registrado en el horario.';
}
