import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requirePageUser } from '@/server/auth/guard';
import { getSupervisionCenter, getTeamPerformance } from '@/server/services/supervision-center';
import { listOperationalUsers } from '@/server/services/users';
import { supervisionAction } from '@/server/actions/supervision-center';
import { ActionForm } from '@/components/ui/form';
import { SubmitButton } from '@/components/ui/button';
import { Card, CardHeader, CardScroll, EmptyState } from '@/components/ui/card';
import { formatDateTime } from '@/lib/format';
import { TASK_STATUS_LABEL, PRIORITY_LABEL } from '@/domain/labels';
import { TaskStatusDialog } from '@/components/operational/task-actions';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Centro de Supervisión' };
function Field({ name, label, type = 'text', required = true }: { name: string; label: string; type?: string; required?: boolean }) {
  return <label className="block text-sm">{label}<input className="input-base mt-1 w-full" name={name} type={type} required={required} /></label>;
}
function Text({ name, label }: { name: string; label: string }) { return <label className="block text-sm">{label}<textarea className="input-base mt-1 w-full" name={name} required rows={3} /></label>; }
function Command({ value, id }: { value: string; id?: string }) { return <><input type="hidden" name="command" value={value} />{id && <input type="hidden" name="id" value={id} />}</>; }
function Priority() { return <label className="block text-sm">Prioridad<select name="priority" className="input-base w-full" defaultValue="MEDIA">{Object.entries(PRIORITY_LABEL).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function Visibility() { return <label className="block text-sm">Visibilidad<select name="visibility" className="input-base w-full"><option value="PRIVADO">Privado: sólo el autor</option><option value="SUPERVISION">Compartido con Supervisión</option></select></label>; }
export default async function Center({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await requirePageUser();
  if (!user.permissions.includes('supervision.center')) redirect('/sin-permisos');
  const [data, users, params] = await Promise.all([getSupervisionCenter(user), listOperationalUsers(), searchParams]);
  const q = (params.q ?? '').toLowerCase();
  const matches = (text: string) => text.toLowerCase().includes(q);
  const editable = !user.isSystemAdmin && user.roleOperational;
  const can = (p: typeof user.permissions[number]) => editable && user.permissions.includes(p);
  const people = users.map(u => <option key={u.id} value={u.id}>{u.name}</option>);
  const start = params.desde ? new Date(params.desde) : new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  const end = params.hasta ? new Date(`${params.hasta}T23:59:59Z`) : new Date();
  const performance = params.persona && user.permissions.includes('supervision.performance') && Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) && start < end ? await getTeamPerformance(user, params.persona, start, end) : null;
  return <div className="mx-auto max-w-7xl space-y-4">
    <header><h1 className="text-2xl font-semibold text-petrol-900">Centro de Supervisión</h1><p className="text-sm text-slate-600">Turno propio, decisiones y seguimiento del equipo. {formatDateTime(new Date())}</p></header>
    <nav className="flex flex-wrap gap-4 text-sm text-petrol-700"><Link href="/supervision">Alertas, entregas, validaciones y comunicados</Link><a href="#tareas">Tareas</a><a href="#notas">Notas y seguimientos</a><a href="#auditorias">Auditorías sorpresa</a><a href="#rendimiento">Rendimiento</a></nav>
    <form className="grid gap-2 rounded-xl bg-white p-4 sm:grid-cols-4"><Field name="q" label="Buscar" required={false} /><label>Responsable<select name="responsable" className="input-base w-full"><option value="">Todos</option>{people}</select></label><label>Estado<select name="estado" className="input-base w-full"><option value="">Todos</option>{Object.entries(TASK_STATUS_LABEL).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><button className="rounded-lg bg-petrol-700 p-2 text-white">Filtrar</button></form>
    <Card><CardHeader title="Mi turno de Supervisión" /><div className="space-y-3 p-4">
      {data.shift ? <><p><strong>{data.shift.status === 'ACTIVO' ? 'En gestión' : 'Entregado'}</strong> · {user.name} · Inicio {formatDateTime(data.shift.startedAt)}</p><p className="whitespace-pre-wrap">{data.shift.priorities}</p>
        {can('supervision.shift') && (data.shift.status === 'ACTIVO' ? <ActionForm action={supervisionAction}><Command value="entregar" id={data.shift.id} /><Text name="note" label="Nota de entrega y asuntos que continúan" /><SubmitButton>Entregar turno</SubmitButton></ActionForm> : <ActionForm action={supervisionAction}><Command value="finalizar" id={data.shift.id} /><SubmitButton>Finalizar turno de Supervisión</SubmitButton></ActionForm>)}
      </> : can('supervision.shift') ? <ActionForm action={supervisionAction}><Command value="iniciar" /><Text name="priorities" label="Prioridades del turno" /><SubmitButton>Iniciar turno de Supervisión</SubmitButton></ActionForm> : <p>Consulta técnica. No participa en turnos operativos.</p>}
      <div className="grid gap-2 sm:grid-cols-3">{data.operational.blocks.filter(b => b.rows.length).map(b => <Link className="rounded-lg border p-2 text-sm" key={b.key} href="/supervision">{b.title}: {b.rows.length}</Link>)}</div>
    </div></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader title="Tareas supervisadas" /><div id="tareas" className="p-4">
        {can('task.assign') && <details><summary className="cursor-pointer font-medium text-petrol-700">Crear tarea</summary><ActionForm action={supervisionAction}><Command value="tarea" /><Field name="title" label="Título" /><Text name="description" label="Instrucción" /><Text name="acceptanceCriteria" label="Criterio de cumplimiento" /><label>Responsable principal<select name="assigneeId" className="input-base w-full" required>{people}</select></label><label>Colaboradores<select name="collaboratorIds" className="input-base w-full" multiple>{people}</select></label><Priority /><Field name="dueAt" label="Fecha y hora límite" type="datetime-local" /><label className="block"><input type="checkbox" name="evidenceRequired" /> Requerir evidencia</label><SubmitButton>Asignar tarea</SubmitButton></ActionForm></details>}
      </div><CardScroll>{data.tasks.filter(t => matches(`${t.title} ${t.assignee?.name}`) && (!params.responsable || t.assigneeId === params.responsable) && (!params.estado || t.status === params.estado)).map(t => <div className="space-y-2 border-t p-4" key={t.id}><Link className="font-medium text-petrol-700" href={`/tareas/${t.id}`}>{t.title}</Link><p className="text-sm">{TASK_STATUS_LABEL[t.status]} · {PRIORITY_LABEL[t.priority]} · {t.assignee?.name} · {formatDateTime(t.dueAt)}</p><p className="text-sm">Cumplimiento: {t.acceptanceCriteria}</p>{can('task.validate') && <TaskStatusDialog taskId={t.id} currentStatus={t.status} />}</div>)}{!data.tasks.length && <EmptyState message="Aún no hay tareas supervisadas." />}</CardScroll></Card>
      <Card><CardHeader title="Notas y seguimientos de Supervisión" /><div id="notas" className="p-4">{can('supervision.notes') && <details><summary className="cursor-pointer font-medium text-petrol-700">Crear nota o seguimiento</summary><ActionForm action={supervisionAction}><Command value="nota" /><Field name="title" label="Asunto" /><Text name="body" label="Contenido" /><Visibility /><Priority /><Field name="nextReviewAt" label="Próxima revisión (para seguimiento)" type="datetime-local" required={false} /><SubmitButton>Guardar</SubmitButton></ActionForm></details>}</div><CardScroll>{data.notes.filter(n => matches(n.title + n.body)).map(n => <article key={n.id} className="space-y-1 border-t p-4"><strong>{n.title}</strong><p className="text-xs">{n.visibility === 'PRIVADO' ? 'Privado' : 'Supervisión'} · {PRIORITY_LABEL[n.priority]}{n.nextReviewAt && ` · Revisar ${formatDateTime(n.nextReviewAt)}`}</p><p className="whitespace-pre-wrap text-sm">{n.body}</p></article>)}{!data.notes.length && <EmptyState message="Sin notas visibles para tu usuario." />}</CardScroll></Card>
    </div>
    <Card><CardHeader title="Auditorías sorpresa" /><div id="auditorias" className="space-y-4 p-4">
      {can('supervision.inspections') && <div className="grid gap-4 md:grid-cols-2"><details><summary className="cursor-pointer font-medium">Configurar plantilla</summary><ActionForm action={supervisionAction}><Command value="plantilla" /><Field name="name" label="Nombre de la plantilla" /><Field name="area" label="Área de control" /><Text name="points" label="Lista de comprobación (un punto por línea)" /><SubmitButton>Guardar plantilla</SubmitButton></ActionForm></details><details><summary className="cursor-pointer font-medium">Iniciar auditoría reservada</summary><ActionForm action={supervisionAction}><Command value="auditoria" /><label>Plantilla<select name="templateId" className="input-base w-full" required>{data.templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Field name="title" label="Título" /><Text name="scope" label="Alcance" /><Text name="sample" label="Muestra seleccionada" /><label>Personas revisadas<select name="reviewedPeople" multiple className="input-base w-full">{people}</select></label><SubmitButton>Iniciar sin avisar al equipo</SubmitButton></ActionForm></details></div>}
      {data.inspections.filter(i => matches(i.title)).map(i => <details key={i.id} className="rounded-xl border p-3"><summary className="cursor-pointer font-medium">{i.title} · {i.closedAt ? 'Cerrada' : 'En preparación'}</summary><p className="my-2 text-sm">{i.scope} · Muestra: {i.sample}</p>{i.points.map(p => <div key={p.id} className="my-2 rounded-lg bg-slate-50 p-3"><p>{p.text}</p>{!i.closedAt && i.auditorId === user.id ? <ActionForm action={supervisionAction}><Command value="punto" id={p.id} /><select name="result" className="input-base" defaultValue={p.result}><option value="PENDIENTE">Pendiente</option><option value="CUMPLE">Cumple</option><option value="OBSERVACION">Observación</option><option value="INCUMPLIMIENTO">Incumplimiento</option><option value="NO_APLICA">No aplica</option></select><select name="severity" className="input-base" defaultValue={p.severity}><option value="BAJA">Baja</option><option value="MEDIA">Media</option><option value="ALTA">Alta</option><option value="CRITICA">Crítica</option></select><Field name="observation" label="Hallazgo u observación" required={false} /><Field name="evidence" label="Evidencia o referencia verificable" required={false} /><SubmitButton>Guardar punto</SubmitButton></ActionForm> : <><p className="text-sm">{({ PENDIENTE: 'Pendiente', CUMPLE: 'Cumple', OBSERVACION: 'Observación', INCUMPLIMIENTO: 'Incumplimiento', NO_APLICA: 'No aplica' })[p.result]} · {p.observation}</p>{p.evidence && <p className="text-sm">Evidencia: {p.evidence}</p>}{can('supervision.corrective') && ['OBSERVACION', 'INCUMPLIMIENTO'].includes(p.result) && <details><summary>Crear medida correctiva</summary><ActionForm action={supervisionAction}><Command value="medida" /><input type="hidden" name="pointId" value={p.id} /><Field name="title" label="Título público de la medida" /><Text name="instruction" label="Instrucción que recibirá la persona" /><Text name="criteria" label="Criterio de cumplimiento" /><select name="assigneeId" className="input-base w-full">{people}</select><Field name="dueAt" label="Vencimiento" type="datetime-local" /><SubmitButton>Crear medida y tarea</SubmitButton></ActionForm></details>}{p.measures.map(m => <Link key={m.id} className="block text-sm text-petrol-700" href={`/tareas/${m.taskId}`}>{m.task.title} · {TASK_STATUS_LABEL[m.task.status]}</Link>)}</>}</div>)}{!i.closedAt && i.auditorId === user.id && <ActionForm action={supervisionAction}><Command value="cerrar-auditoria" id={i.id} /><Text name="result" label="Resultado final" /><Visibility /><SubmitButton>Cerrar auditoría</SubmitButton></ActionForm>}</details>)}
      {!data.inspections.length && <EmptyState message="Sin auditorías visibles." />}
    </div></Card>
    <Card><CardHeader title="Rendimiento operativo por periodo" /><div id="rendimiento" className="space-y-3 p-4"><form className="grid gap-3 sm:grid-cols-4"><label>Persona<select className="input-base w-full" name="persona" required><option value="">Seleccionar</option>{people}</select></label><Field name="desde" label="Desde" type="date" /><Field name="hasta" label="Hasta" type="date" /><button className="rounded-lg bg-petrol-700 p-2 text-white">Consultar periodo</button></form>{performance ? <><p className="text-sm">{performance.formula}</p><p>Validadas: {performance.validated}/{performance.denominator} · Realizadas en plazo: {performance.onTime}/{performance.denominator} · Actualmente devueltas: {performance.returned}/{performance.denominator}</p><p className="text-sm">Turnos de Recepción iniciados en el periodo: {performance.shifts.length}. Carga registrada: {performance.tasks.length} tareas. Ausencias y periodos no comparables: no determinados por estos datos.</p><ul>{performance.tasks.map(t => <li key={t.id}><Link href={`/tareas/${t.id}`} className="text-sm text-petrol-700">{t.title} · {TASK_STATUS_LABEL[t.status]}</Link></li>)}</ul></> : <EmptyState message="Selecciona una persona y un periodo. No se calcula una nota global." />}</div></Card>
    <Card><CardHeader title="Entregas de Supervisión" /><CardScroll>{data.handovers.map(h => <details key={h.id} className="border-t p-4"><summary className="cursor-pointer">Entrega del {formatDateTime(h.createdAt)}</summary><p className="whitespace-pre-wrap text-sm">{h.note}</p><p className="text-xs text-slate-500">Copia conservada al enviar la entrega.</p></details>)}{!data.handovers.length && <EmptyState message="Sin entregas de Supervisión." />}</CardScroll></Card>
  </div>;
}
